<?php $this->layout()->title = 'Edit Link' ?>
<?php $this->scriptManager()->add(['autocomplete', 'base_editor', 'edit_links']) ?>
<div class="edit_container">
  <?=$this->render('geeby-deeby/edit-link/index.phtml')?>
</div>
<hr />
<b>Related Items:</b>
<form onsubmit="Link.link('Item'); return false;">
  <label>Item: <input id="link_item_id" class="Item_ID" /></label>
  <input type="submit" value="Link" />
</form>
<div id="item_list">
  <?=$this->render('geeby-deeby/edit-link/item-list.phtml')?>
</div>
<hr />
<b>Related Series:</b>
<form onsubmit="Link.link('Series'); return false;">
  <label>Series: <input id="link_series_id" class="Series_ID" /></label>
  <input type="submit" value="Link" />
</form>
<div id="series_list">
  <?=$this->render('geeby-deeby/edit-link/series-list.phtml')?>
</div>
<hr />
<b>Related People:</b>
<form onsubmit="Link.link('Person'); return false;">
  <label>Person: <input id="link_person_id" class="Person_ID" /></label>
  <input type="submit" value="Link" />
</form>
<div id="person_list">
  <?=$this->render('geeby-deeby/edit-link/person-list.phtml')?>
</div>
