<? $this->layout()->title = 'Edit Link' ?>
<? $this->headScript()->appendFile($this->basePath() . '/js/autocomplete.js') ?>
<? $this->headScript()->appendFile($this->basePath() . '/js/base_editor.js') ?>
<? $this->headScript()->appendFile($this->basePath() . '/js/edit_links.js') ?>
<? $this->headScript()->appendFile($this->basePath() . '/js/edit_link.js') ?>
<div class="edit_container">
  <?=$this->render('geeby-deeby/edit-link/index.phtml')?>
</div>
<hr />
<b>Related Items:</b>
<br />
<input id="link_item_id" class="Item_ID" />
<button onclick="linkItem();">Link</button>
<div id="link_item_list">
  <?=$this->render('geeby-deeby/edit-link/item-list.phtml')?>
</div>
<hr />
<b>Related Series:</b>
<br />
<input id="link_series_id" class="Series_ID" />
<button onclick="linkSeries();">Link</button>
<div id="link_series_list">
  <?=$this->render('geeby-deeby/edit-link/series-list.phtml')?>
</div>
<hr />
<b>Related People:</b>
<br />
<input id="link_person_id" class="Person_ID" />
<button onclick="linkPerson();">Link</button>
<div id="link_person_list">
  <?=$this->render('geeby-deeby/edit-link/person-list.phtml')?>
</div>
