<div id="editForm">
  <input type="hidden" id="Link_ID" value="<?=$link['Link_ID']?>" />
  <table class="edit">
    <tr>
      <th>Link Name:</th>
      <td><input type="text" id="Link_Name" value="<?=isset($link['Link_Name']) ? $this->escapeHtml($link['Link_Name']) : ''?>" /></td>
    </tr>
    <tr>
      <th>URL:</th>
      <td><input type="text" id="URL" value="<?=isset($link['URL']) ? $this->escapeHtml($link['URL']) : ''?>" /></td>
    </tr>
    <tr>
      <th>Link Type:</th>
      <td><?=$this->render('geeby-deeby/edit-link/type-select.phtml', ['linkTypes' => $linkTypes, 'selected' => $link['Link_Type_ID'] ?? null])?></td>
    </tr>
    <tr>
      <th>Date Checked<br/>(YYYY-MM-DD):</th>
      <td><input type="text" id="Date_Checked" value="<?=isset($link['Date_Checked']) ? $this->escapeHtml($link['Date_Checked']) : date('Y-m-d')?>" /></td>
    </tr>
    <tr>
      <th>Description:</th>
      <td><textarea id="Description"><?=isset($link['Description']) ? $this->escapeHtml($link['Description']) : ''?></textarea></td>
    </tr>
  </table>
  <button id="save_link" onclick="Link.save();">Save</button>
  <div id="save_link_status"></div>
</div>
