<? if (isset($itemsLinks) && count($itemsLinks) > 0): ?>
  <? foreach ($itemsLinks as $current): ?>
    <table class="list_item">
      <tr>
        <td>
          <a href="<?=$this->url('edit/item', array('id' => $current['Item_ID']))?>"><?=$this->escapeHtml($current['Item_Name'])?></a><br />
        </td>
        <td>
          <a class="ui-icon ui-icon-trash" href="#" onclick="Link.unlink('Item', <?=$current['Item_ID']?>); return false;">
          </a>
        </td>
      </tr>
    </table>
  <? endforeach; ?>
<? else: ?>
  No relevant items.
<? endif; ?>