<?php if (isset($itemsLinks) && count($itemsLinks) > 0): ?>
  <?php foreach ($itemsLinks as $current): ?>
    <table class="list_item">
      <tr>
        <td>
          <a href="<?=$this->url('edit/item', ['id' => $current['Item_ID']])?>"><?=$this->escapeHtml($current['Item_Name'])?></a><br />
        </td>
        <td>
          <?=
            $this->iconButton(
                'trash',
                "Link.unlink('Item', " . $current['Item_ID'] . ')',
                'Unlink item: ' . $current['Item_Name']
            )
      ?>
        </td>
      </tr>
    </table>
  <?php endforeach; ?>
<?php else: ?>
  No relevant items.
<?php endif; ?>