<? $this->layout()->title = 'Edit Links' ?>
<? $this->scriptManager()->add(['base_editor', 'edit_links']) ?>

<div class="row">
  <div class="col-md-3">
    <p><b>Links:</b></p>
    <button id="add_link" type="button" onclick="Link.edit('NEW');">Add Link</button>
    <br /><br />
    <div id="link_list"><?=$this->render('geeby-deeby/edit-link/render-links.phtml')?></div>
  </div>
  <div class="col-md-3">
    <p><b>Link Types:</b></p>
    <button id="add_link_type" type="button" onclick="LinkType.edit('NEW');">Add Link Type</button>
    <br /><br />
    <div id="link_type_list"><?=$this->render('geeby-deeby/edit-link/render-types.phtml')?></div>
  </div>
</div>