<?php if (isset($seriesLinks) && count($seriesLinks) > 0): ?>
  <?php foreach ($seriesLinks as $current): ?>
    <table class="list_item">
      <tr>
        <td>
          <a href="<?=$this->url('edit/series', ['id' => $current['Series_ID']])?>"><?=$this->escapeHtml($current['Series_Name'])?></a><br />
        </td>
        <td>
          <a class="ui-icon ui-icon-trash" href="#" onclick="Link.unlink('Series', <?=$current['Series_ID']?>); return false;">
          </a>
        </td>
      </tr>
    </table>
  <?php endforeach; ?>
<?php else: ?>
  No relevant series.
<?php endif; ?>