<div id="editForm">
  <input type="hidden" id="Link_Type_ID" value="<?=$linkType['Link_Type_ID']?>" />
  <table class="edit">
    <tr>
      <th scope="row">Link Type:</th>
      <td><input type="text" id="Link_Type" value="<?=isset($linkType['Link_Type']) ? $this->escapeHtml($linkType['Link_Type']) : ''?>" /></td>
    </tr>
  </table>
  <button id="save_link_type" onclick="LinkType.save();">Save</button>
  <div id="save_link_type_status"></div>
</div>
