<form id="editForm" onsubmit="LinkType.save(); return false;">
  <input type="hidden" id="Link_Type_ID" value="<?=$linkType['Link_Type_ID']?>" />
  <table class="edit">
    <tr>
      <th scope="row"><label for="Link_Type">Link Type:</label></th>
      <td><input type="text" id="Link_Type" value="<?=isset($linkType['Link_Type']) ? $this->escapeHtml($linkType['Link_Type']) : ''?>" /></td>
    </tr>
  </table>
  <input type="submit" value="Save" />
  <div id="save_link_type_status"></div>
</form>
