<?php if (isset($itemsFiles) && count($itemsFiles) > 0): ?>
  <?php foreach ($itemsFiles as $current): ?>
    <table class="list_item">
      <tr>
        <td>
          <a href="<?=$this->url('edit/item', ['id' => $current['Item_ID']])?>"><?=$this->escapeHtml($current['Item_Name'])?></a><br />
        </td>
        <td>
          <a class="ui-icon ui-icon-trash" href="#" onclick="File.unlink('Item', <?=$current['Item_ID']?>); return false;">
          </a>
        </td>
      </tr>
    </table>
  <?php endforeach; ?>
<?php else: ?>
  No relevant items.
<?php endif; ?>