<? $this->headScript()->prependFile($this->basePath() . '/js/edit_files.js') ?>
<h1>Edit Files</h1>
<table>
  <tr>
    <td>
      <p><b>Files:</b></p>
      <button id="add_file" type="button" onclick="editFile('NEW');">Add File</button>
      <br /><br />
      <div id="file_list"><?=$this->render('geeby-deeby/edit-file/render-files.phtml')?></div>
    </td>
    <td>
      <p><b>File Types:</b></p>
      <button id="add_file_type" type="button" onclick="editFileType('NEW');">Add File Type</button>
      <br /><br />
      <div id="file_type_list"><?=$this->render('geeby-deeby/edit-file/render-types.phtml')?></div>
    </td>
  </tr>
</table>