<? $this->layout()->title = 'Edit Files' ?>
<? $this->scriptManager()->add(['base_editor', 'edit_files']) ?>
<div class="row">
  <div class="col-md-3">
      <p><b>Files:</b></p>
      <button id="add_file" type="button" onclick="File.edit('NEW');">Add File</button>
      <br /><br />
      <div id="file_list"><?=$this->render('geeby-deeby/edit-file/render-files.phtml')?></div>
  </div>
  <div class="col-md-3">
      <p><b>File Types:</b></p>
      <button id="add_file_type" type="button" onclick="FileType.edit('NEW');">Add File Type</button>
      <br /><br />
      <div id="file_type_list"><?=$this->render('geeby-deeby/edit-file/render-types.phtml')?></div>
    </td>
  </div>
</div>