<?php if (isset($peopleFiles) && count($peopleFiles) > 0): ?>
  <?php foreach ($peopleFiles as $current): ?>
    <?php $currentName = $this->showperson($current); ?>
    <table class="list_item">
      <tr>
        <td>
          <a href="<?=$this->url('edit/person', ['id' => $current['Person_ID']])?>">
            <?=$this->escapeHtml($currentName)?>
          </a><br />
        </td>
        <td>
          <?=$this->iconButton(
            'trash',
            "File.unlink('Person', " . $current['Person_ID'] . ")",
            'Unlink person: ' . $currentName
          )?>
        </td>
      </tr>
    </table>
  <?php endforeach; ?>
<?php else: ?>
  No relevant people.
<?php endif; ?>