<?php if (isset($peopleFiles) && count($peopleFiles) > 0): ?>
  <?php foreach ($peopleFiles as $current): ?>
    <table class="list_item">
      <tr>
        <td>
          <a href="<?=$this->url('edit/person', ['id' => $current['Person_ID']])?>">
            <?=$this->escapeHtml($this->showperson($current))?>
          </a><br />
        </td>
        <td>
          <a class="ui-icon ui-icon-trash" href="#" onclick="File.unlink('Person', <?=$current['Person_ID']?>); return false;">
          </a>
        </td>
      </tr>
    </table>
  <?php endforeach; ?>
<?php else: ?>
  No relevant people.
<?php endif; ?>