<? if (isset($peopleFiles) && count($peopleFiles) > 0): ?>
  <? foreach ($peopleFiles as $current): ?>
    <table class="list_item">
      <tr>
        <td>
          <a href="<?=$this->url('edit/person', array('id' => $current['Person_ID']))?>">
            <?=$this->escapeHtml($this->showperson($current))?>
          </a><br />
        </td>
        <td>
          <a class="ui-icon ui-icon-trash" href="#" onclick="unlinkPerson(<?=$current['Person_ID']?>); return false;">
          </a>
        </td>
      </tr>
    </table>
  <? endforeach; ?>
<? else: ?>
  No relevant people.
<? endif; ?>