<?php if (isset($seriesFiles) && count($seriesFiles) > 0): ?>
  <?php foreach ($seriesFiles as $current): ?>
    <table class="list_item">
      <tr>
        <td>
          <a href="<?=$this->url('edit/series', ['id' => $current['Series_ID']])?>"><?=$this->escapeHtml($current['Series_Name'])?></a><br />
        </td>
        <td>
          <?=
            $this->iconButton(
                'trash',
                "File.unlink('Series', " . $current['Series_ID'] . ')',
                'Unlink series: ' . $current['Series_Name']
            )
      ?>
        </td>
      </tr>
    </table>
  <?php endforeach; ?>
<?php else: ?>
  No relevant series.
<?php endif; ?>