<? if (isset($fileTypes) && !empty($fileTypes)): ?>
  <select id="<?=!empty($idPrefix) ? $this->escapeHtml($idPrefix) : ''?>File_Type_ID">
    <? foreach ($fileTypes as $current): ?>
      <option value="<?=$current['File_Type_ID']?>"<?=($current['File_Type_ID'] == $selected) ? ' selected="selected"' : ''?>>
        <?=$this->escapeHtml($current['File_Type'])?>
      </option>
    <? endforeach; ?>
  </select>
<? else: ?>
  Please define file types.
<? endif; ?>