<form id="editForm" onsubmit="FileType.save(); return false;">
  <input type="hidden" id="File_Type_ID" value="<?=$fileType['File_Type_ID']?>" />
  <table class="edit">
    <tr>
      <th scope="row"><label for="File_Type">File Type:</label></th>
      <td><input type="text" id="File_Type" value="<?=isset($fileType['File_Type']) ? $this->escapeHtml($fileType['File_Type']) : ''?>" /></td>
    </tr>
  </table>
  <input type="submit" id="save_file_type" value="Save" />
  <div id="save_file_type_status"></div>
</form>
