<div id="editForm">
  <input type="hidden" id="File_Type_ID" value="<?=$fileType['File_Type_ID']?>" />
  <table class="edit">
    <tr>
      <th scope="row">File Type:</th>
      <td><input type="text" id="File_Type" value="<?=isset($fileType['File_Type']) ? $this->escapeHtml($fileType['File_Type']) : ''?>" /></td>
    </tr>
  </table>
  <button id="save_file_type" onclick="FileType.save();">Save</button>
  <div id="save_file_type_status"></div>
</div>
