<?php if (isset($fileTypes) && count($fileTypes) > 0): ?>
  <select id="<?=!empty($idPrefix) ? $this->escapeHtml($idPrefix) : ''?>File_Type_ID">
    <?php foreach ($fileTypes as $current): ?>
      <option value="<?=$current['File_Type_ID']?>"<?=($current['File_Type_ID'] == $selected) ? ' selected="selected"' : ''?>>
        <?=$this->escapeHtml($current['File_Type'])?>
      </option>
    <?php endforeach; ?>
  </select>
<?php else: ?>
  Please define file types.
<?php endif; ?>