<div class="footer">
  <p>
    Comments/questions/corrections?  Contact <a href="mailto:demian.katz@villanova.edu">Demian Katz</a>
    or read <a href="<?=$this->url('about')?>">About the Project</a>.<br />
    Want to learn more?  Listen to our <a href="<?=$this->url('podcast')?>">podcast</a>.<br />
    <a href="<?=$this->basePath()?>"><?=$this->escapeHtml($this->layout()->siteTitle)?></a>
    (c) 2012-<?=$this->escapeHtml(date('Y'))?> Villanova University; powered by <a href="https://github.com/demiankatz/Geeby-Deeby">Geeby-Deeby</a>.
  </p>
</div>