<?php if (isset($addresses) && count($addresses) > 0): ?>
  <?php foreach ($addresses as $current): ?>
    <table class="list_item">
      <tr>
        <td>
          <?=$this->escapeHtml($current['Country_Name'] . (empty($current['City_Name']) ? '' : ' -- ' . $current['City_Name']) . (empty($current['Street']) ? '' : ' -- ' . $current['Street']))?>
        </td>
        <td>
          <a class="ui-icon ui-icon-trash" href="#" onclick="Publisher.unlink('Address', <?=$current['Address_ID']?>); return false;">
          </a>
        </td>
      </tr>
    </table>
  <?php endforeach; ?>
<?php else: ?>
  No addresses set.
<?php endif; ?>
