<?php if (isset($addresses) && count($addresses) > 0): ?>
  <?php foreach ($addresses as $current): ?>
    <?php $currentAddress = $current['Country_Name'] . (empty($current['City_Name']) ? '' : ' -- ' . $current['City_Name']) . (empty($current['Street']) ? '' : ' -- ' . $current['Street']); ?>
    <table class="list_item">
      <tr>
        <td>
          <?=$this->escapeHtml($currentAddress)?>
        </td>
        <td>
          <?=$this->iconButton(
    'trash',
    "Publisher.unlink('Address', " . $current['Address_ID'] . ")",
    'Delete address: ' . $currentAddress
)?>
        </td>
      </tr>
    </table>
  <?php endforeach; ?>
<?php else: ?>
  No addresses set.
<?php endif; ?>
