<? $this->layout()->title = 'Edit Publisher Editor' ?>
<? $this->headScript()->prependFile($this->basePath() . '/js/edit_publisher_details.js') ?>
<div class="edit_container" style="width: 800px;">
  <?=$this->render('geeby-deeby/edit-publisher/index.phtml')?>
</div>
<hr />
<ul class="nav nav-tabs">
  <li class="active"><a href="#addr-tab"><span>Addresses</span></a></li>
  <li><a href="#imprints-tab"><span>Imprints</span></a></li>
</ul>
<div class="tab-content">
  <div id="addr-tab" class="tab-pane active">
    <div class="edit_container">
      <table class="edit">
        <tr><th>Country:</th><td><?=$this->render('geeby-deeby/edit-country/select.phtml')?></td></tr>
        <tr><th>City:</th><td><?=$this->render('geeby-deeby/edit-city/select.phtml')?></td></tr>
        <tr><th>Street:</th><td><input type="text" id="Street" /></td></tr>
        <tr><th></th><td><button onclick="addAddress();">Add</button></td></tr>
      </table>
    </div>
    <div id="address_list">
      <?=$this->render('geeby-deeby/edit-publisher/address-list.phtml')?>
    </div>
  </div>

  <div id="imprints-tab" class="tab-pane">
    <b>Imprint:</b> <input type="text" id="Imprint" />
    <button onclick="addImprint();">Add</button>
    <div id="imprint_list">
      <?=$this->render('geeby-deeby/edit-publisher/imprint-list.phtml')?>
    </div>
  </div>
</div>