<?php $this->layout()->title = 'Edit Publisher Editor' ?>
<?php $this->scriptManager()->add(['base_editor', 'edit_publishers']) ?>
<div class="edit_container" style="width: 800px;">
  <?=$this->render('geeby-deeby/edit-publisher/index.phtml')?>
</div>
<hr />
<ul class="nav nav-tabs">
  <li class="active"><a href="#addr-tab" data-toggle="tab"><span>Addresses</span></a></li>
  <li><a href="#imprints-tab" data-toggle="tab"><span>Imprints</span></a></li>
</ul>
<div class="tab-content">
  <div id="addr-tab" class="tab-pane active">
    <div class="edit_container">
      <table class="edit">
        <tr><th scope="row">Country:</th><td><?=$this->render('geeby-deeby/edit-country/select.phtml')?></td></tr>
        <tr><th scope="row">City:</th><td><?=$this->render('geeby-deeby/edit-city/select.phtml')?></td></tr>
        <tr><th scope="row">Street:</th><td><input type="text" id="Street" /></td></tr>
        <tr><td></td><td><button onclick="Publisher.link('Address');">Add</button></td></tr>
      </table>
    </div>
    <div id="address_list">
      <?=$this->render('geeby-deeby/edit-publisher/address-list.phtml')?>
    </div>
  </div>

  <div id="imprints-tab" class="tab-pane">
    <b>Imprint:</b> <input type="text" id="Imprint" />
    <button onclick="Publisher.link('Imprint');">Add</button>
    <div id="imprint_list">
      <?=$this->render('geeby-deeby/edit-publisher/imprint-list.phtml')?>
    </div>
  </div>
</div>