<?php if (isset($imprints) && count($imprints) > 0): ?>
  <?php foreach ($imprints as $current): ?>
    <table class="list_item">
      <tr>
        <td>
          <?=$this->escapeHtml($current['Imprint_Name'])?>
        </td>
        <td>
          <?=
            $this->iconButton(
                'trash',
                "Publisher.unlink('Imprint', " . $current['Imprint_ID'] . ")",
                'Delete imprint: ' . $current['Imprint_Name']
            )
      ?>
        </td>
      </tr>
    </table>
  <?php endforeach; ?>
<?php else: ?>
  No imprints set.
<?php endif; ?>
