<? if (isset($imprints) && count($imprints) > 0): ?>
  <? foreach ($imprints as $current): ?>
    <table class="list_item">
      <tr>
        <td>
          <?=$this->escapeHtml($current['Imprint_Name'])?>
        </td>
        <td>
          <a class="ui-icon ui-icon-trash" href="#" onclick="deleteImprint(<?=$current['Imprint_ID']?>); return false;">
          </a>
        </td>
      </tr>
    </table>
  <? endforeach; ?>
<? else: ?>
  No imprints set.
<? endif; ?>
