<?php if (isset($imprints) && count($imprints) > 0): ?>
  <?php foreach ($imprints as $current): ?>
    <table class="list_item">
      <tr>
        <td>
          <?=$this->escapeHtml($current['Imprint_Name'])?>
        </td>
        <td>
          <a class="ui-icon ui-icon-trash" href="#" onclick="Publisher.unlink('Imprint', <?=$current['Imprint_ID']?>); return false;">
          </a>
        </td>
      </tr>
    </table>
  <?php endforeach; ?>
<?php else: ?>
  No imprints set.
<?php endif; ?>
