<div id="editForm">
  <input type="hidden" id="Publisher_ID" value="<?=$publisher['Publisher_ID']?>" />
  <table class="edit">
    <tr>
      <th>Publisher:</th>
      <td><input type="text" id="Publisher_Name" value="<?=isset($publisher['Publisher_Name']) ? $this->escapeHtml($publisher['Publisher_Name']) : ''?>" /></td>
    </tr>
  </table>
  <button id="save_publisher" onclick="savePublisher();">Save</button>
  <div id="save_publisher_status"></div>
</div>
