<? $this->layout()->title = 'Edit Publisher List' ?>
<? $this->headScript()->appendFile($this->basePath() . '/js/base_editor.js') ?>
<? $this->headScript()->appendFile($this->basePath() . '/js/edit_publishers.js') ?>
<p><b>Publishers:</b></p>
<button id="add_publisher" type="button" onclick="Publisher.edit('NEW');">Add Publisher</button>
<br /><br />
<div id="publisher_list"><?=$this->render('geeby-deeby/edit-publisher/render-publishers.phtml')?></div>
