<?php if (count($publishers) < 1): ?>
  <p>No publishers listed in this database yet.</p>
<?php else: ?>
  <h2>
    <?=$this->firstLetterMenu($publishers, 'Publisher_Name'); ?>
  </h2>
  <?php $currentLetter = false;
  foreach ($publishers as $i => $current): ?>
    <?php $first = $this->firstletter($current['Publisher_Name']); ?>
    <?php if ($currentLetter !== $first): $currentLetter = $first; ?>
      <?php if ($i > 0): ?>
        <a name="<?=$this->escapeHtml($currentLetter)?>"/>
        <h2><?=$this->escapeHtml($currentLetter)?><a href="#" style="float:right">Back to Top &uarr;</a></h2>
      <?php endif; ?>
    <?php endif; ?>
    <a href="<?=$this->url('edit/publisher', ['id' => $current['Publisher_ID']])?>">
      <?=$this->escapeHtml($this->fixtitle($current['Publisher_Name']))?>
    </a><br />
  <?php endforeach; ?>
<?php endif; ?>