<?php
    $title = $this->showperson($person);
    $this->layout()->title = 'Person Full Text - ' . $title;
?>

<p>
  <a href="<?=$this->url('person', ['id' => $person['Person_ID']])?>">
    [Back to Person]
  </a>
</p>

<?php if (count($items) < 1): ?>
  <p>No full-text items are currently associated with this person.</p>
<?php else: ?>
  <h2>Full Text Items Associated with "<?=$this->escapeHtml($title)?>"</h2>

  <ul class="person-full-text">
    <?php foreach ($items as $item): ?>
      <li>
        <a href="<?=$this->url('item', ['id' => $item['Item_ID']])?>">
          <?=$this->escapeHtml(
              $this->fixtitle($item['Item_Name'])
          )?>
        </a>
      </li>
    <?php endforeach; ?>
  </ul>
<?php endif; ?>
