<?php
    $this->layout()->title = ($bioMode ? 'Biography' : 'Person') . ' List';
?>
<?php if (count($people) < 1): ?>
  <p>No <?=$bioMode ? 'biographies' : 'people'?> listed in this database yet.</p>
<?php else: ?>
  <h2>
    <?=$this->firstLetterMenu($people, 'Last_Name'); ?>
  </h2>
  <?php $currentLetter = false;
  foreach ($people as $i => $current): ?>
    <?php $first = $this->firstletter($current['Last_Name']); ?>
    <?php if ($currentLetter !== $first): $currentLetter = $first; ?>
      <?php if($i > 0): ?>
        <a name="<?=$this->escapeHtml($currentLetter)?>"/>
        <h2><?=$this->escapeHtml($currentLetter)?><a href="#" style="float:right">Back to Top &uarr;</a></h2>
      <?php endif ?>
    <?php endif; ?>
    <a href="<?=$this->url('person', ['id' => $current['Person_ID']])?>">
      <?=$this->escapeHtml($this->showperson($current))?>
    </a><br />
  <?php endforeach; ?>
<?php endif; ?>