<?
    $this->headTitle(($bioMode ? 'Biography' : 'Person') . ' List - ');
?>
<h1><?=$bioMode ? 'Biography' : 'Person'?> List</h1>
<? if (count($people) < 1): ?>
  <p>No <?=$bioMode ? 'biographies' : 'people'?> listed in this database yet.</p>
<? else: ?>
  <? $currentLetter = false; foreach ($people as $current): ?>
    <? $first = $this->firstletter($current['Last_Name']); if ($currentLetter !== $first): $currentLetter = $first; ?>
      <h2><?=$this->escapeHtml($currentLetter)?></h2>
    <? endif; ?>
    <a href="<?=$this->url('person', array('id' => $current['Person_ID']))?>">
      <?=$this->escapeHtml($this->showperson($current))?>
    </a><br />
  <? endforeach; ?>
<? endif; ?>