<?php
    $title = $this->showperson($person);
    $this->layout()->title = 'Person - ' . $title;
    $this->layout()->toggleLink = $this->toggleLink('edit/person', $person['Person_ID']);
    $displayedSomething = false;
?>
<?php $realNameCount = count($realNames); ?>
<?php if ($realNameCount > 0): $displayedSomething = true; ?>
  <p><b>Pseudonym For:</b>
    <?php $i = 0; ?>
    <?php foreach ($realNames as $realName): $i++; ?>
      <a href="<?=$this->url('person', ['id' => $realName['Person_ID']])?>"><?=$this->showperson($realName)?></a><?=$i < $realNameCount ? '; ' : ''?>
    <?php endforeach; ?>
  </p>
<?php endif; ?>

<?php $pseudoCount = count($pseudonyms); ?>
<?php if ($pseudoCount > 0): $displayedSomething = true; ?>
  <p><b><?=$pseudoCount > 1 ? 'Pseudonyms' : 'Pseudonym'?>:</b>
    <?php $i = 0; ?>
    <?php foreach ($pseudonyms as $pseudonym): $i++; ?>
      <a href="<?=$this->url('person', ['id' => $pseudonym['Person_ID']])?>"><?=$this->showperson($pseudonym)?></a><?=$i < $pseudoCount ? '; ' : ''?>
    <?php endforeach; ?>
  </p>
<?php endif; ?>

<?php $uriCount = count($uris); ?>
<?php if ($uriCount > 0): $displayedSomething = true; ?>
  <p><b>External Identifier<?php if ($uriCount > 1): ?>s<?php endif; ?>:</b>
    <?php $i = 0; ?>
    <?php foreach ($uris as $uri): $i++ ?>
      <a href="<?=$this->escapeHtmlAttr($uri['URI'])?>"><?=$this->escapeHtml($uri['URI'])?></a><?=$i < $uriCount ? ', ' : ''?>
    <?php endforeach; ?>
  </p>
<?php endif; ?>

<?php if (!empty($person['Biography'])): $displayedSomething = true; ?>
  <?php /* Don't escape biography -- contains HTML. */ ?>
  <p><?=$person['Biography']?></p>
<?php endif; ?>

<?php if (count($credits) > 0 || count($citations) > 0): $displayedSomething = true; ?>
  <?php $sorts = [ 'series', 'title', 'year' ];
  $sort = $this->sort ?? $sorts[0]; ?>
  <div class="pull-right" style="padding:12px 0;">
    Sort by:
    <div class="btn-group" style="margin-top:-4px;">
      <?php foreach ($sorts as $current): ?>
        <a href="?sort=<?=urlencode($current)?>" class="btn btn-<?=$sort == $current ? 'primary' : 'default'?>"><?=ucwords($current)?></a>
      <?php endforeach; ?>
    </div>
  </div>
  <?=$this->render('geeby-deeby/person/innerList.phtml', ['title' => $title, 'sort' => $sort, 'list' => $citations, 'labelPrefix' => 'Cited'])?>
  <?=$this->render('geeby-deeby/person/innerList.phtml', ['title' => $title, 'sort' => $sort, 'list' => $credits, 'labelPrefix' => 'Credited'])?>
<?php endif; ?>

<?php if (count($files) > 0): $displayedSomething = true;?>
  <h2>Related Documents</h2>
  <?php $type = false; ?>
  <?php foreach ($files as $file): ?>
    <?php if ($type !== $file['File_Type']): $type = $file['File_Type']; ?>
      <h3 class="filetype"><?=$this->escapeHtml($type)?></h3>
    <?php endif; ?>
    <p class="file">
      <a target="_new" href="<?=$this->escapeHtml($file['File_Path'])?>">
        <?=$this->escapeHtml($this->fixtitle($file['File_Name']))?>
      </a>
      <?php if (!empty($file['Description'])): ?>
        <br /><?=$file['Description']?>
      <?php endif; ?>
    </p>
  <?php endforeach; ?>
<?php endif; ?>

<?php if (count($bibliography) > 0): $displayedSomething = true;?>
  <h2>Bibliography of Items About "<?=$this->escapeHtml($title)?>"</h2>
  <?php $type = false; ?>
  <?php foreach ($bibliography as $bib): ?>
    <?php if ($type !== $bib['Material_Type_Plural_Name']): $type = $bib['Material_Type_Plural_Name']; ?>
      <h3 class="materialType"><?=$this->escapeHtml($type)?></h3>
    <?php endif; ?>
    <span class="item"><a href="<?=$this->url('item', ['id' => $bib['Item_ID']])?>"><?=$this->fixtitle($bib['Item_Name'])?></a></span><br />
  <?php endforeach; ?>
<?php endif; ?>

<?php if (count($links) > 0): $displayedSomething = true;?>
  <h2>Related Links</h2>
  <?php foreach ($links as $link): ?>
    <p class="link">
      <a href="<?=$this->escapeHtml($link['URL'])?>"><?=$this->fixtitle($link['Link_Name'])?></a><br />
      <?php if (!empty($link['Description'])): ?><?=$link['Description']?><br /><?php endif; ?>
      <span class="url"><?=$this->escapeHtml($link['URL'])?></span>
      (last verified: <?=$this->escapeHtml($link['Date_Checked'])?>)
    </p>
  <?php endforeach; ?>
<?php endif; ?>

<?php if (!$displayedSomething): ?><p>No further information on this person is available at the moment.</p><?php endif; ?>
