<?
    $title = $this->showperson($person);
    $this->layout()->title = 'Person - ' . $title;
    $displayedSomething = false;
?>
<? $realNameCount = count($realNames); if ($realNameCount > 0): $displayedSomething = true; ?>
  <p><b>Pseudonym For:</b>
    <? $i = 0; foreach ($realNames as $realName): $i++; ?>
      <a href="<?=$this->url('person', array('id' => $realName['Person_ID']))?>"><?=$this->showperson($realName)?></a><?=$i < $realNameCount ? '; ' : ''?>
    <? endforeach; ?>
  </p>
<? endif; ?>

<? $pseudoCount = count($pseudonyms); if ($pseudoCount > 0): $displayedSomething = true; ?>
  <p><b><?=$pseudoCount > 1 ? 'Pseudonyms' : 'Pseudonym'?>:</b>
    <? $i = 0; foreach ($pseudonyms as $pseudonym): $i++; ?>
      <a href="<?=$this->url('person', array('id' => $pseudonym['Person_ID']))?>"><?=$this->showperson($pseudonym)?></a><?=$i < $pseudoCount ? '; ' : ''?>
    <? endforeach; ?>
  </p>
<? endif; ?>

<? if (!empty($person['Biography'])): $displayedSomething = true; ?>
  <? /* Don't escape biography -- contains HTML. */ ?>
  <p><?=$person['Biography']?></p>
<? endif; ?>

<? if (count($credits) > 0): $displayedSomething = true; ?>
  <? $sorts = [ 'series', 'title', 'year' ]; $sort = isset($this->sort) ? $this->sort : $sorts[0]; ?>
  <div class="pull-right" style="padding:12px 0;">
    Sort by: 
    <div class="btn-group" style="margin-top:-4px;">
      <? foreach ($sorts as $current): ?>
        <a href="?sort=<?=urlencode($current)?>" class="btn btn-<?=$sort == $current ? 'primary' : 'default'?>"><?=ucwords($current)?></a>
      <? endforeach; ?>
    </div>
  </div>
  <?=$this->render('geeby-deeby/person/innerList.phtml', array('title' => $title, 'sort' => $sort, 'list' => $citations, 'labelPrefix' => 'Cited'))?>
  <?=$this->render('geeby-deeby/person/innerList.phtml', array('title' => $title, 'sort' => $sort, 'list' => $credits, 'labelPrefix' => 'Credited'))?>
<? endif; ?>

<? if (count($files) > 0): $displayedSomething = true;?>
  <h2>Related Documents</h2>
  <? $type = false; foreach ($files as $file): ?>
    <? if ($type !== $file['File_Type']): $type = $file['File_Type']; ?>
      <h3 class="filetype"><?=$this->escapeHtml($type)?></h3>
    <? endif; ?>
    <p class="file">
      <a target="_new" href="<?=$this->escapeHtml($file['File_Path'])?>">
        <?=$this->escapeHtml($this->fixtitle($file['File_Name']))?>
      </a>
      <? if (!empty($file['Description'])): ?>
        <br /><?=$file['Description']?>
      <? endif; ?>
    </p>
  <? endforeach; ?>
<? endif; ?>

<? if (count($bibliography) > 0): $displayedSomething = true;?>
  <h2>Bibliography of Items About "<?=$this->escapeHtml($title)?>"</h2>
  <? $type = false; foreach ($bibliography as $bib): ?>
    <? if ($type !== $bib['Material_Type_Plural_Name']): $type = $bib['Material_Type_Plural_Name']; ?>
      <h3 class="materialType"><?=$this->escapeHtml($type)?></h3>
    <? endif; ?>
    <span class="item"><a href="<?=$this->url('item', array('id' => $bib['Item_ID']))?>"><?=$this->fixtitle($bib['Item_Name'])?></a></span><br />
  <? endforeach; ?>
<? endif; ?>

<? if (count($links) > 0): $displayedSomething = true;?>
  <h2>Related Links</h2>
  <? foreach ($links as $link): ?>
    <p class="link">
      <a href="<?=$this->escapeHtml($link['URL'])?>"><?=$this->fixtitle($link['Link_Name'])?></a><br />
      <? if (!empty($link['Description'])): ?><?=$link['Description']?><br /><? endif; ?>
      <span class="url"><?=$this->escapeHtml($link['URL'])?></span>
      (last verified: <?=$this->escapeHtml($link['Date_Checked'])?>)
    </p>
  <? endforeach; ?>
<? endif; ?>

<? if (!$displayedSomething): ?><p>No further information on this person is available at the moment.</p><? endif; ?>
