<?
    $this->headTitle('Language List - ');
?>
<h1>Language List</h1>
<? if (count($languages) < 1): ?>
  <p>No languages listed in this database yet.</p>
<? else: ?>
  <? $currentLetter = false; foreach ($languages as $current): ?>
    <? $first = $this->firstletter($current['Language_Name']); if ($currentLetter !== $first): $currentLetter = $first; ?>
      <h2><?=$this->escapeHtml($currentLetter)?></h2>
    <? endif; ?>
    <a href="<?=$this->url('language', array('id' => $current['Language_ID']))?>">
      <?=$this->escapeHtml($this->fixtitle($current['Language_Name']))?>
    </a><br />
  <? endforeach; ?>
<? endif; ?>