<?php
    $this->layout()->title = 'Language List';
?>
<?php if (count($languages) < 1): ?>
  <p>No languages listed in this database yet.</p>
<?php else: ?>
  <h2>
    <?=$this->firstLetterMenu($languages, 'Language_Name'); ?>
  </h2>
  <?php $currentLetter = false; foreach ($languages as $i => $current): ?>
    <?php $first = $this->firstletter($current['Language_Name']); ?>
    <?php if ($currentLetter !== $first): $currentLetter = $first; ?>
      <?php if ($i > 0): ?>
        <a name="<?=$this->escapeHtml($currentLetter)?>"/>
        <h2><?=$this->escapeHtml($currentLetter)?><a href="#" style="float:right">Back to Top &uarr;</a></h2>
      <?php endif; ?>
    <?php endif; ?>
    <a href="<?=$this->url('language', ['id' => $current['Language_ID']])?>">
      <?=$this->escapeHtml($this->fixtitle($current['Language_Name']))?>
    </a><br />
  <?php endforeach; ?>
<?php endif; ?>