<?
    $this->layout()->title = 'Language List';
?>
<? if (count($languages) < 1): ?>
  <p>No languages listed in this database yet.</p>
<? else: ?>
  <h2>
    <?=$this->firstLetterMenu($languages, 'Language_Name'); ?>
  </h2>
  <? $currentLetter = false; foreach ($languages as $i=>$current): ?>
    <? $first = $this->firstletter($current['Language_Name']); ?>
    <? if ($currentLetter !== $first): $currentLetter = $first; ?>
      <? if ($i > 0): ?>
        <a name="<?=$this->escapeHtml($currentLetter)?>"/>
        <h2><?=$this->escapeHtml($currentLetter)?><a href="#" style="float:right">Back to Top &uarr;</a></h2>
      <? endif; ?>
    <? endif; ?>
    <a href="<?=$this->url('language', array('id' => $current['Language_ID']))?>">
      <?=$this->escapeHtml($this->fixtitle($current['Language_Name']))?>
    </a><br />
  <? endforeach; ?>
<? endif; ?>