<?xml version="1.0" encoding="UTF-8"?>
<project name="gbdb" basedir="." default="main">
  <property name="sh" value="/bin/sh" />
  <property name="tmp" value="/tmp" />
  <property name="package"  value="${phing.project.name}" override="true" />
  <property name="builddir" value="${tmp}/build/${phing.project.name}" override="true" />
  <property name="srcdir"   value="${project.basedir}" override="true" />
  <property name="gbdburl" value="http://localhost" />
  <property name="gbdbdb" value="gbdb_test" />
  <property name="gbdbdbuser" value="gbdbtest" />
  <property name="gbdbdbpass" value="gbdbtestpass" />
  <property name="mysqlhost" value="localhost" />
  <property name="mysqlport" value="3306" />
  <property name="mysqlprotocol" value="" />
  <property name="mysqlrootuser" value="root" />
  <property name="mysqlrootpass" value="password" />
  <property name="phpunit_command" value="${srcdir}/vendor/bin/phpunit" />
  <property name="phpunit_extra_params" value="" />
  <property name="screenshot_dir" value="" /><!-- set to a directory name to capture screenshots of failed tests -->
  <property name="snooze_multiplier" value="1" /><!-- can be used to slow down Mink tests; increase when tests fail on slow systems -->
  <property name="default_test_timeout" value="5000" /><!-- default timeout (in ms) for Mink tests; increase when tests fail on slow systems -->

  <property name="mysqlconnectionargs" value="-h ${mysqlhost} -P ${mysqlport} -u ${mysqlrootuser}" />
  <!-- Add password if not empty -->
  <if>
    <not>
      <equals arg1="${mysqlrootpass}" arg2="" />
    </not>
    <then>
      <property name="mysqlconnectionargs" override="true" value="${mysqlconnectionargs} -p${mysqlrootpass}" />
    </then>
  </if>
  <!-- Add protocol if not empty -->
  <if>
    <not>
      <equals arg1="${mysqlprotocol}" arg2="" />
    </not>
    <then>
      <property name="mysqlconnectionargs" override="true" value="${mysqlconnectionargs} --protocol ${mysqlprotocol}" />
    </then>
  </if>

  <!-- Main Target -->
  <target name="main" description="main target">
    <trycatch property="exceptionmsg">
      <try>
        <phingcall target="startup" />
        <phingcall target="ci-tasks" />
        <phingcall target="shutdown" />
      </try>
      <catch>
        <phingcall target="shutdown" />
        <fail>Unexpected error during continuous integration tasks -- ${exceptionmsg}</fail>
      </catch>
    </trycatch>
  </target>

  <!-- Continuous Integration Tasks -->
  <target name="ci-tasks" description="continuous integration tasks">

    <!-- Create dirs -->
    <mkdir dir="${builddir}/reports"/>

    <!-- Call standard tasks -->
    <phingcall target="php-cs-fixer-dryrun"/>
    <phingcall target="phpcs"/>
    <phingcall target="phpstan-checkstyle" />
    <phingcall target="rector-console"/>
  </target>

  <!-- Quality Assurance PHP Tasks -->
  <target name="qa-console" description="quality assurance tasks">
    <phingcall target="phpunitfast"/>
    <phingcall target="php-cs-fixer-dryrun"/>
    <phingcall target="phpcs-console"/>
    <phingcall target="phpstan-console" />
    <phingcall target="rector-console"/>
  </target>

  <!-- Fix PHP Tasks -->
  <target name="fix-php" description="quality assurance php tasks">
    <!-- Rector may introduce style issues, so run it first -->
    <phingcall target="rector"/>
    <phingcall target="php-cs-fixer"/>
    <phingcall target="phpcbf"/>
  </target>

  <!-- PHP CodeSniffer -->
  <target name="phpcbf">
    <exec executable="${srcdir}/vendor/bin/phpcbf" escape="false" passthru="true" checkreturn="true">
      <arg line="--cache=${srcdir}/tests/phpcs.cache.json --standard=${srcdir}/tests/phpcs.xml" />
    </exec>    
  </target>
  <target name="phpcs">
    <exec executable="${srcdir}/vendor/bin/phpcs" escape="false"> 
      <arg line="--cache=${srcdir}/tests/phpcs.cache.json --standard=${srcdir}/tests/phpcs.xml --report=checkstyle &gt; ${builddir}/reports/checkstyle.xml" />
    </exec>
  </target>
  <target name="phpcs-console">
    <exec executable="${srcdir}/vendor/bin/phpcs" escape="false" passthru="true" checkreturn="true">
      <arg line="--cache=${srcdir}/tests/phpcs.cache.json --standard=${srcdir}/tests/phpcs.xml" />
    </exec>  
  </target>

  <!-- Phpstan -->
  <target name="phpstan-checkstyle">
    <exec executable="${srcdir}/vendor/bin/phpstan" escape="false" passthru="true" checkreturn="true">
      <arg line="--configuration=${srcdir}/tests/phpstan.neon --memory-limit=2G --error-format=checkstyle analyse &gt; ${builddir}/reports/phpstan-checkstyle.xml" />
    </exec>
  </target>
  <target name="phpstan-console">
    <exec executable="${srcdir}/vendor/bin/phpstan" escape="false" passthru="true" checkreturn="true">
      <arg line="--configuration=${srcdir}/tests/phpstan.neon --memory-limit=2G analyse" />
    </exec>
  </target>

  <!-- php-cs-fixer (first task applies fixes, second task simply checks if they are needed) -->
  <target name="php-cs-fixer">
    <exec executable="${srcdir}/vendor/bin/php-cs-fixer" passthru="true" escape="false">
      <arg line="fix --config=${srcdir}/tests/gbdb.php-cs-fixer.php --verbose" />
    </exec>  
    <exec executable="${srcdir}/vendor/bin/php-cs-fixer" passthru="true" escape="false">
      <arg line="fix --config=${srcdir}/tests/gbdb_templates.php-cs-fixer.php --verbose" />
    </exec>  
  </target>
  <target name="php-cs-fixer-dryrun">
    <exec executable="${srcdir}/vendor/bin/php-cs-fixer" passthru="true" escape="false" checkreturn="true">
      <arg line="fix --config=${srcdir}/tests/gbdb.php-cs-fixer.php --dry-run --verbose --diff" />
    </exec>  
    <exec executable="${srcdir}/vendor/bin/php-cs-fixer" passthru="true" escape="false" checkreturn="true">
      <arg line="fix --config=${srcdir}/tests/gbdb_templates.php-cs-fixer.php --dry-run --verbose --diff" />
    </exec>
  </target>

  <!-- PHPUnit without logging output -->
  <target name="phpunitfast" description="Run tests">
    <exec dir="${srcdir}/module/GeebyDeeby/tests" executable="${sh}" passthru="true" checkreturn="true">
      <arg line="-c &apos;${phpunit_command} ${phpunit_extra_params}&apos;" />
      <env key="GBDB_SCREENSHOT_DIR" value="${screenshot_dir}" />
      <env key="GBDB_URL" value="${gbdburl}" />
      <env key="GBDB_SNOOZE_MULTIPLIER" value="${snooze_multiplier}" />
      <env key="GBDB_DEFAULT_TEST_TIMEOUT" value="${default_test_timeout}" />
    </exec>
  </target>

  <!-- Rector -->
  <target name="rector-console">
    <exec executable="${srcdir}/vendor/bin/rector" escape="false" passthru="true" checkreturn="true">
      <arg line="--config=${srcdir}/tests/rector.php --dry-run" />
    </exec>
  </target>
  <target name="rector">
    <exec executable="${srcdir}/vendor/bin/rector" escape="false" passthru="true" checkreturn="true">
      <arg line="--config=${srcdir}/tests/rector.php" />
    </exec>
  </target>

  <!-- Set up test database -->
  <target name="setup_database" description="clean up existing database and users">
    <phingcall target="teardown_database" />
    <exec executable="mysql" passthru="true" checkreturn="true">
      <arg line="${mysqlconnectionargs} -e &quot;CREATE DATABASE IF NOT EXISTS ${gbdbdb}&quot;" />
    </exec>
    <exec executable="mysql" passthru="true" checkreturn="true">
      <arg line="${mysqlconnectionargs} -e &quot;CREATE USER IF NOT EXISTS '${gbdbdbuser}'@'%' IDENTIFIED BY '${gbdbdbpass}'&quot;" />
    </exec>
    <exec executable="mysql" passthru="true" checkreturn="true">
      <arg line="${mysqlconnectionargs} ${gbdbdb} &lt; ${srcdir}/data/mysql.sql" />
    </exec>
    <exec executable="mysql" passthru="true" checkreturn="true">
      <arg line="${mysqlconnectionargs} -e &quot;GRANT ALL ON ${gbdbdb}.* TO '${gbdbdbuser}'@'%'&quot;" />
    </exec>
    <touch file="${srcdir}/config/autoload/testdb.local.php" />
    <append destFile="${srcdir}/config/autoload/testdb.local.php" text="&lt;?php return ['geeby-deeby' => ['dbName' => '${gbdbdb}', 'dbUser' => '${gbdbdbuser}', 'dbPass' => '${gbdbdbpass}']]; ?&gt;" />
  </target>

  <!-- Tear down test database -->
  <target name="teardown_database" description="clean up existing database and users">
    <exec executable="mysql" passthru="true">
      <arg line="${mysqlconnectionargs} -e &quot;DROP DATABASE IF EXISTS ${gbdbdb}&quot;" />
    </exec>
    <exec executable="mysql" passthru="true">
      <arg line="${mysqlconnectionargs} -e &quot;DROP USER IF EXISTS '${gbdbdbuser}'@'%'&quot;" />
    </exec>
    <delete file="${srcdir}/config/autoload/testdb.local.php" quiet="true" />
  </target>

  <!-- Set up dependencies -->
  <target name="startup" description="set up dependencies and database">
    <exec executable="composer">
      <arg line="install" />
    </exec>
    <phingcall target="setup_database" />
  </target>

  <!-- Clean up -->
  <target name="shutdown" description="clean up file system and test database">
    <phingcall target="teardown_database" />
  </target>
</project>
