<?
    $title = $materialType['Material_Type_Name'];
    $this->layout()->title = 'Material Type - ' . $title;
    $displayedSomething = false;
?>
<? if (count($series) < 1): ?>
  <p>No information is available about this material type.</p>
<? else: ?>
  <? $currentLetter = false; foreach ($series as $current): ?>
    <? $first = $this->firstletter($current['Series_Name']); if ($currentLetter !== $first): $currentLetter = $first; ?>
      <h2><?=$this->escapeHtml($currentLetter)?></h2>
    <? endif; ?>
    <a href="<?=$this->url('series', array('id' => $current['Series_ID']))?>">
      <?=$this->escapeHtml($this->fixtitle($current['Series_Name']))?>
    </a><br />
  <? endforeach; ?>
<? endif; ?>