<?php
    $this->layout()->title = 'Material Type List';
?>
<?php if (count($materialTypes) < 1): ?>
  <p>No material types listed in this database yet.</p>
<?php else: ?>
  <h2>
    <?=$this->firstLetterMenu($materialTypes, 'Material_Type_Name'); ?>
  </h2>
  <?php $currentLetter = false; ?>
  <?php foreach ($materialTypes as $i => $current): ?>
    <?php $first = $this->firstletter($current['Material_Type_Name']); ?>
    <?php if ($currentLetter !== $first): $currentLetter = $first; ?>
      <?php if ($i > 0): ?>
        <a name="<?=$this->escapeHtml($currentLetter)?>"/>
        <h2><?=$this->escapeHtml($currentLetter)?><a href="#" style="float:right">Back to Top &uarr;</a></h2>
      <?php endif; ?>
    <?php endif; ?>
    <a href="<?=$this->url('material', ['id' => $current['Material_Type_ID']])?>">
      <?=$this->escapeHtml($current['Material_Type_Name'])?>
    </a><br />
  <?php endforeach; ?>
<?php endif; ?>