<h1><?=$this->escapeHtml($this->layout()->siteTitle)?></h1>
<h2>Database</h2>
<p>List Series
  [<a href="<?=$this->url('series')?>">by name</a>,
  <a href="<?=$this->url('categories')?>">by category</a>,
  <a href="<?=$this->url('countries')?>">by country</a>,
  <a href="<?=$this->url('languages')?>">by language</a>,
  <a href="<?=$this->url('materials')?>">by material type</a>,
  <a href="<?=$this->url('publishers')?>">by publisher</a>,
  <a href="<?=$this->url('series', array('extra' => 'Comments'))?>">with comments</a>]
</p>
<p>List People
  [<a href="<?=$this->url('people')?>">by name</a>,
  <a href="<?=$this->url('people', array('extra' => 'Bios'))?>">with biographical notes</a>]
</p>
<p>List Items
  [<a href="<?=$this->url('items')?>">by name</a>,
  <a href="<?=$this->url('platforms')?>">by platform</a>,
  <a href="<?=$this->url('items', array('extra' => 'ByYear'))?>">by year</a>,
  <a href="<?=$this->url('items', array('extra' => 'Reviews'))?>">with reviews</a>]
</p>
<p><a href="<?=$this->url('files')?>">List Files</a></p>
<? /* TODO: List Links */ ?>

<h2>Users</h2>
<p>
  <a href="<?=$this->url('users')?>">List Registered Users</a><br />
  <? /* TODO: browse recent reviews */ ?>
</p>