<?php
  $this->layout()->title = 'Main Menu';
  $this->layout()->toggleLink = $this->toggleLink('edit', null);
?>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.8&appId=619933464777164";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<?php $this->layout()->title = 'Main Menu' ?>
<div data-width="500" style="width: 500px; text-align: right; float: right;" class="fb-page" data-href="https://www.facebook.com/gamebooks.org/" data-tabs="timeline" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><blockquote cite="https://www.facebook.com/gamebooks.org/" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/gamebooks.org/">gamebooks.org</a></blockquote></div>
<h2>Database</h2>
<p>List Series
  [<a href="<?=$this->url('series')?>">by name</a>,
  <a href="<?=$this->url('categories')?>">by category</a>,
  <a href="<?=$this->url('cities')?>">by city</a>,
  <a href="<?=$this->url('countries')?>">by country</a>,
  <a href="<?=$this->url('languages')?>">by language</a>,
  <a href="<?=$this->url('materials')?>">by material type</a>,
  <a href="<?=$this->url('publishers')?>">by publisher</a>,
  <a href="<?=$this->url('series', ['extra' => 'Comments'])?>">with comments</a>,
  <a href="<?=$this->url('series', ['extra' => 'New'])?>">recently added</a>]
</p>
<p>List People
  [<a href="<?=$this->url('people')?>">by name</a>,
  <a href="<?=$this->url('people', ['extra' => 'Bios'])?>">with biographical notes</a>,
  <a href="<?=$this->url('people', ['extra' => 'New'])?>">recently added</a>]
</p>
<p>List Items
  [<a href="<?=$this->url('items')?>">by name</a>,
  <a href="<?=$this->url('platforms')?>">by platform</a>,
  <a href="<?=$this->url('tags')?>">by subject/tag</a>,
  <a href="<?=$this->url('items', ['extra' => 'ByYear'])?>">by year</a>,
  <a href="<?=$this->url('items', ['extra' => 'FullText'])?>">with full text</a>,
  <a href="<?=$this->url('items', ['extra' => 'Reviews'])?>">with reviews</a>,
  <a href="<?=$this->url('items', ['extra' => 'New'])?>">recently added</a>]
</p>
<p><a href="<?=$this->url('files')?>">List Files</a></p>
<p><a href="<?=$this->url('links')?>">List Links</a></p>

<h2>Users</h2>
<p>
  <a href="<?=$this->url('users')?>">List Registered Users</a><br />
  <a href="<?=$this->url('reviews')?>">Browse Recent Reviews</a><br /><br />
  <a href="https://www.facebook.com/gamebooks.org">Follow Us on Facebook</a>
</p>

<h2>About</h2>
<p>
  <a href="<?=$this->url('faqs')?>">Frequently Asked Questions</a><br />
  <a href="<?=$this->url('thanks')?>">Dedications and Acknowledgements</a>
</p>

<div style="clear: right;"><!-- empty --></div>
