<? $this->layout()->title = 'Main Menu'; ?>
<div class="row">
  <div class="col-md-4">
    <h2>Welcome!</h2>
    <p>The Edward T. LeBlanc Dime Novel Bibliography project aims to create a comprehensive online database of dime novels, story papers, reprint libraries and related materials. <a href="<? echo $this->url('about')?>">Learn More &rarr;</a></p>
    <h2>Browse</h2>
    <div class="row">
      <div class="col-sm-6">
        <h3>Series</h3>
        <ul>
          <li><a href="<? echo $this->url('series')?>">by name</a></li>
          <li><a href="<? echo $this->url('categories')?>">by category</a></li>
          <li><a href="<? echo $this->url('cities')?>">by city</a></li>
          <li><a href="<? echo $this->url('countries')?>">by country</a></li>
          <li><a href="<? echo $this->url('languages')?>">by language</a></li>
          <!--  <a href="<? echo $this->url('materials')?>">by material type</a></li> -->
          <li><a href="<? echo $this->url('publishers')?>">by publisher</a></li>
          <li><a href="<? echo $this->url('series', array('extra' => 'Comments'))?>">with comments</a></li>
        </ul>
        <h3>Users</h3>
        <ul>
          <li><a href="<? echo $this->url('users')?>">List Registered Users</a></li>
          <li><a href="<? echo $this->url('reviews')?>">Browse Recent Reviews</a></li>
        </ul>
      </div>
      <div class="col-sm-6">
        <h3>List Items</h3>
        <ul>
          <li><a href="<? echo $this->url('items')?>">by name</a></li>
          <!--  <a href="<? echo $this->url('platforms')?>">by platform</a>, -->
          <li><a href="<? echo $this->url('tags')?>">by subject/tag</a></li>
          <li><a href="<? echo $this->url('items', array('extra' => 'ByYear'))?>">by year</a></li>
          <li><a href="<? echo $this->url('items', array('extra' => 'FullText'))?>">with full text</a></li>
          <li><a href="<? echo $this->url('items', array('extra' => 'Reviews'))?>">with reviews</a></li>
        </ul>
        <h3>List People</h3>
        <ul>
          <li><a href="<? echo $this->url('people')?>">by name</a></li>
          <li><a href="<? echo $this->url('people', array('extra' => 'Bios'))?>">with biographical notes</a></li>
        </ul>
        <!--
        <p><a href="<? echo $this->url('files')?>">List Files</a></p>
        <p><a href="<? echo $this->url('links')?>">List Links</a></p>
        -->
      </div>
    </div>

    <h2>Latest Podcast Episodes</h2>
    <div class="row" style="text-align:center">
      <div class="col-sm-6">
        <? $this->latest = current($episodes['mittie']) ?>
        <? echo $this->partial('geeby-deeby-local/podcast/episode.phtml')?>
      </div>
      <div class="col-sm-6">
        <? $this->latest = current($episodes['professor']) ?>
        <? echo $this->partial('geeby-deeby-local/podcast/episode.phtml')?>
      </div>
    </div>

    <!--
    <h2>Frequently Asked Questions</h2>
    <p>
      <a href="<? echo $this->url('faqs')?>">List All</a>
    </p>
    -->
  </div>
  <div class="col-md-8">
    <a class="twitter-grid" data-limit="5" data-partner="tweetdeck" href="https://twitter.com/crhallberg/timelines/765561012632297472">@DimeNovelBiblio</a> <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
  </div>
</div>