<?php $this->layout()->title = 'Please log in' ?>
<?php if (isset($msg)): ?>
  <div class="error"><?=$this->escapeHtml($msg)?></div>
<?php endif; ?>
<form method="post">
  <table>
    <tr>
      <th scope="row"><label for="username">Username:</label></th>
      <td><input id="username" type="text" name="user"/></td>
    </tr>
    <tr>
      <th scope="row"><label for="password">Password:</label></th>
      <td><input id="password" type="password" name="pass"/></td>
    </tr>
    <tr>
      <td>&nbsp;</td>
      <td><input type="submit" value="Log In"/></td>
    </tr>
  </table>
</form>