<?php $this->layout()->title = 'Please log in' ?>
<?php if (isset($msg)): ?>
  <div class="error"><?=$this->escapeHtml($msg)?></div>
<?php endif; ?>
<form method="post">
  <table>
    <tr>
      <th scope="row">Username:</th>
      <td><input type="text" name="user"/></td>
    </tr>
    <tr>
      <th scope="row">Password:</th>
      <td><input type="password" name="pass"/></td>
    </tr>
    <tr>
      <td>&nbsp;</td>
      <td><input type="submit" value="Log In"/></td>
    </tr>
  </table>
</form>