<? $this->layout()->title = 'Edit Series Attributes' ?>
<? $this->scriptManager()->add(['base_editor', 'edit_attributes']) ?>
<p><b>Series Attributes:</b></p>
<button id="add_series_attribute" type="button" onclick="SeriesAttribute.edit('NEW');">Add Series Attribute</button>
<br /><br />
<div id="series_attribute_list"><?=$this->render('geeby-deeby/edit-series-attribute/render-series-attributes.phtml')?></div>
