<?php if (isset($releaseDates) && count($releaseDates) > 0): ?>
  <?php foreach ($releaseDates as $current): ?>
    <table class="list_item">
      <tr>
        <td>
          <?=$this->formatReleaseDate($current)?>
        </td>
        <td>
          <a class="ui-icon ui-icon-trash" href="#" onclick="Edition.unlink('Date', '<?=$this->escapeHtml(implode(',', [$current['Year'], $current['Month'], $current['Day']]))?>'); return false;">
          </a>
        </td>
      </tr>
    </table>
  <?php endforeach; ?>
<?php else: ?>
  No dates set.
<?php endif; ?>
