<?php if (count($releaseDates ?? []) > 0): ?>
  <?php foreach ($releaseDates as $current): ?>
    <?php $displayDate = $this->formatReleaseDate($current); ?>
    <table class="list_item">
      <tr>
        <td>
          <?=$displayDate?>
        </td>
        <td>
          <?=
            $this->iconButton(
                'trash',
                "Edition.unlink('Date', '" . addslashes(implode(',', [$current->getYear(), $current->getMonth(), $current->getDay()])) . "')",
                'Delete date: ' . $displayDate
            )
          ?>
        </td>
      </tr>
    </table>
  <?php endforeach; ?>
<?php else: ?>
  No dates set.
<?php endif; ?>
