<? $this->headTitle('Edition Editor - ') ?>
<? $this->headScript()->prependFile($this->basePath() . '/js/edit_edition_details.js') ?>
<? $this->headScript()->prependFile($this->basePath() . '/js/ui.tabs.paging.js') ?>
<h1>Edit Edition</h1>
<div class="edit_container" style="width: 800px;">
  <?=$this->render('geeby-deeby/edit-edition/index.phtml')?>
</div>
<hr />
<div id="tabs">
  <ul>
    <li><a href="#credits-tab"><span>Credits</span></a></li>
    <li><a href="#release-tab"><span>Dates</span></a></li>
  </ul>

  <div id="credits-tab" class="edit_tab_contents">
    <p class="disclaimer">Credits added/removed here will affect only this edition of the item;
    to affect ALL editions, please go back to the Item Editor first.</p>
    <div class="edit_container">
      <table class="edit">
        <tr>
          <th>Position:</th>
          <td><input type="text" id="credit_position" /></td>
        </tr>
        <tr>
          <th>Person:</th>
          <td><input id="credit_person" class="Person_ID" /></td>
        </tr>
        <tr>
          <th>Role:</th>
          <td><?=$this->render('geeby-deeby/edit-person/role-select.phtml')?></td>
        </tr>
        <tr>
          <th>Note:</th>
          <td><input id="credit_note" class="Note_ID" /></td>
        </tr>
        <tr>
          <th></th>
          <td><button onclick="saveCredit();">Add</button></td>
        </tr>
      </table>
    </div>
    <div id="credits">
      <?=$this->render('geeby-deeby/edit-item/credits.phtml')?>
    </div>
  </div>

  <div id="release-tab" class="edit_tab_contents">
    <div class="edit_container">
      <table class="edit">
        <tr>
          <th>Month:<br /><span class="note">(1-12, 0 for unknown)</span></th>
          <td><input type="text" id="releaseMonth" /></td>
        </tr>
        <tr>
          <th>Day:<br /><span class="note">(1-31, 0 for unknown)</span></th>
          <td><input type="text" id="releaseDay" /></td>
        </tr>
        <tr>
          <th>Year:<br /><span class="note">(-1 for unreleased)</span></th>
          <td><input type="text" id="releaseYear" /></td>
        </tr>
        <tr>
          <th>Note:</th>
          <td><input id="releaseNote" class="Note_ID" /></td>
        </tr>
        <tr>
          <th></th>
          <td>
            <button onclick="saveReleaseDate();">Add</button>
          </td>
        </tr>
      </table>
    </div>
    <div id="date_list">
      <?=$this->render('geeby-deeby/edit-edition/date-list.phtml')?>
    </div>
  </div>
</div>