<? $this->headTitle('Edition Editor - ') ?>
<? $this->headScript()->prependFile($this->basePath() . '/js/edit_edition_details.js') ?>
<? $this->headScript()->prependFile($this->basePath() . '/js/ui.tabs.paging.js') ?>
<h1>Edit Edition</h1>
<div class="edit_container" style="width: 800px;">
  <?=$this->render('geeby-deeby/edit-edition/index.phtml')?>
</div>
<hr />
<div id="tabs">
  <ul>
    <li><a href="#credits-tab"><span>Credits</span></a></li>
    <li><a href="#codes-tab"><span>Codes/ISBNs</span></a></li>
    <li><a href="#release-tab"><span>Dates</span></a></li>
    <li><a href="#fulltext-tab"><span>Full Text Links</span></a></li>
    <li><a href="#preferred-publisher"><span>Preferred Publisher</span></a></li>
    <li><a href="#preferred-titles"><span>Preferred Titles</span></a></li>
  </ul>

  <div id="credits-tab" class="edit_tab_contents">
    <p class="disclaimer">Credits added/removed here will affect only this edition of the item;
    to affect ALL editions, please go back to the Item Editor first.</p>
    <div class="edit_container">
      <table class="edit">
        <tr>
          <th>Position:</th>
          <td><input type="text" id="credit_position" /></td>
        </tr>
        <tr>
          <th>Person:</th>
          <td><input id="credit_person" class="Person_ID" /></td>
        </tr>
        <tr>
          <th>Role:</th>
          <td><?=$this->render('geeby-deeby/edit-person/role-select.phtml')?></td>
        </tr>
        <tr>
          <th>Note:</th>
          <td><input id="credit_note" class="Note_ID" /></td>
        </tr>
        <tr>
          <th></th>
          <td><button onclick="saveCredit();">Add</button></td>
        </tr>
      </table>
    </div>
    <div id="credits">
      <?=$this->render('geeby-deeby/edit-edition/credits.phtml')?>
    </div>
  </div>

  <div id="codes-tab" class="edit_tab_contents">
    <table>
      <tr>
        <td style="width: 33%;">
          <table class="edit">
            <tr><th>New ISBN</th><td><input type="text" id="isbn" /></td></tr>
            <tr><th>Note:</th><td><input id="isbn_note" class="Note_ID" /></td></tr>
            <tr><th></th><td><button onclick="addISBN();">Add</button></td></tr>
          </table>
          <b>ISBNs:</b>
          <div id="item_isbns">
            <?=$this->render('geeby-deeby/edit-edition/isbn-list.phtml')?>
          </div>
        </td>
        <td style="width: 33%;">
          <table class="edit">
            <tr><th>New OCLC Number:</th><td><input type="text" id="oclc_number" /></td></tr>
            <tr><th>Note:</th><td><input id="oclc_number_note" class="Note_ID" /></td></tr>
            <tr><th></th><td><button onclick="addOCLCNumber();">Add</button></td></tr>
          </table>
          <b>OCLC Numbers:</b>
          <div id="item_oclc_numbers">
            <?=$this->render('geeby-deeby/edit-edition/oclc-number-list.phtml')?>
          </div>
        </td>
        <td>
          <table class="edit">
            <tr><th>New Code</th><td><input type="text" id="product_code" /></td></tr>
            <tr><th>Note:</th><td><input id="product_code_note" class="Note_ID" /></td></tr>
            <tr><th></th><td><button onclick="addProductCode();">Add</button></td></tr>
          </table>
          <b>Product Codes:</b>
          <div id="item_codes">
            <?=$this->render('geeby-deeby/edit-edition/product-code-list.phtml')?>
          </div>
        </td>
      </tr>
    </table>
  </div>

  <div id="release-tab" class="edit_tab_contents">
    <div class="edit_container">
      <table class="edit">
        <tr>
          <th>Month:<br /><span class="note">(1-12, 0 for unknown)</span></th>
          <td><input type="text" id="releaseMonth" /></td>
        </tr>
        <tr>
          <th>Day:<br /><span class="note">(1-31, 0 for unknown)</span></th>
          <td><input type="text" id="releaseDay" /></td>
        </tr>
        <tr>
          <th>Year:<br /><span class="note">(-1 for unreleased)</span></th>
          <td><input type="text" id="releaseYear" /></td>
        </tr>
        <tr>
          <th>Note:</th>
          <td><input id="releaseNote" class="Note_ID" /></td>
        </tr>
        <tr>
          <th></th>
          <td>
            <button onclick="saveReleaseDate();">Add</button>
          </td>
        </tr>
      </table>
    </div>
    <div id="date_list">
      <?=$this->render('geeby-deeby/edit-edition/date-list.phtml')?>
    </div>
  </div>

  <div id="fulltext-tab" class="edit_tab_contents">
    <div class="edit_container">
      Add full text:
      <select id="Full_Text_Source_ID">
        <? foreach ($this->fullTextSources as $current): ?>
          <option value="<?=$current['Full_Text_Source_ID']?>"><?=$this->escapeHtml($current['Full_Text_Source_Name'])?></option>
        <? endforeach; ?>
      </select>
      <input type="text" id="Full_Text_URL" size="50" />
      <button onclick="saveFullText()">Save</button>
    </div>
    <div id="fulltext_list">
      <?=$this->render('geeby-deeby/edit-edition/fulltext-list.phtml')?>
    </div>
  </div>

  <div id="preferred-publisher" class="edit_tab_contents">
    <div class="edit_container">
      <h3>Preferred Publisher</h3>
      <div id="series-publisher-select-container">
        <?=$this->render('geeby-deeby/edit-edition/series-publisher-select.phtml', array('publishers' => $publishers, 'selected' => $edition['Preferred_Series_Publisher_ID']))?>
      </div>
      <button onclick="saveSeriesPublisher()">Save</button>
    </div>
  </div>

  <div id="preferred-titles" class="edit_tab_contents">
    <div class="edit_container">
      <h3>Preferred Item Title</h3>
      <div id="item-alt-title-select-container">
        <?=$this->render('geeby-deeby/edit-edition/item-alt-title-select.phtml', array('itemAltTitles' => $itemAltTitles, 'selected' => $edition['Preferred_Item_AltName_ID']))?>
      </div>
      <input type="text" id="Preferred_Item_Title_Text" size="50" />
      <button onclick="saveItemAltTitle()">Save</button>
      <button onclick="deleteItemAltTitle()">Clear</button>

      <h3>Preferred Series Title</h3>
      <div id="series-alt-title-select-container">
        <?=$this->render('geeby-deeby/edit-edition/series-alt-title-select.phtml', array('seriesAltTitles' => $seriesAltTitles, 'selected' => $edition['Preferred_Series_AltName_ID']))?>
      </div>
      <input type="text" id="Preferred_Series_Title_Text" size="50" />
      <button onclick="saveSeriesAltTitle()">Save</button>
      <button onclick="deleteSeriesAltTitle()">Clear</button>
    </div>
  </div>
</div>