<?php if (isset($fullText) && count($fullText) > 0): ?>
  <?php foreach ($fullText as $current): ?>
    <table class="list_item">
      <tr>
        <td>
          <?=$this->escapeHtml($current['Full_Text_Source_Name'])?>: <a href="<?=$this->escapeHtml($current['Full_Text_URL'])?>"><?=$this->escapeHtml($current['Full_Text_URL'])?></a>
        </td>
        <td>
          <?=
            $this->iconButton(
                'gear',
                "Edition.editLink('FullText', " . $current['Sequence_ID'] . ')',
                'Edit options for URL: ' . $current['Full_Text_URL']
            )
          ?>
        </td>
        <td>
          <?=
            $this->iconButton(
                'trash',
                "Edition.unlink('FullText', " . $current['Sequence_ID'] . ')',
                'Delete full text URL: ' . $current['Full_Text_URL']
            )
          ?>
        </td>
      </tr>
    </table>
  <?php endforeach; ?>
<?php else: ?>
  No full text set.
<?php endif; ?>
