<?php if (count($fullText ?? []) > 0): ?>
  <?php foreach ($fullText as $current): ?>
    <table class="list_item">
      <tr>
        <td>
          <?=$this->escapeHtml($current->getFullTextSource()->getSourceName())?>: <a href="<?=$this->escapeHtml($current->getUrl())?>"><?=$this->escapeHtml($current->getUrl())?></a>
        </td>
        <td>
          <?=
            $this->iconButton(
                'gear',
                "Edition.editLink('FullText', " . $current->getId() . ')',
                'Edit options for URL: ' . $current->getUrl()
            )
          ?>
        </td>
        <td>
          <?=
            $this->iconButton(
                'trash',
                "Edition.unlink('FullText', " . $current->getId() . ')',
                'Delete full text URL: ' . $current->getUrl()
            )
          ?>
        </td>
      </tr>
    </table>
  <?php endforeach; ?>
<?php else: ?>
  No full text set.
<?php endif; ?>
