<?php if (!isset($images) || count($images) < 1): ?>
  No images.
<?php else: ?>
  <table class="list_item">
    <tr><th>Order</th><th colspan="2">Image</th><th>Details</th></tr>
    <?php foreach ($images as $current): ?>
      <tr>
        <td>
          <input class="number" type="text" value="<?=$this->escapeHtml($current['Position'])?>" id="image_order_<?=$this->escapeHtml($current['Sequence_ID'])?>" />
          <button onclick="Edition.reorderLink('Image', { 'sequence_id': <?=$this->escapeHtml($current['Sequence_ID'])?> });">Set</button>
        </td>
        <td>
          <a class="ui-icon ui-icon-trash" href="#" onclick="Edition.unlink('Image', <?=$this->escapeHtml($current['Sequence_ID'])?>); return false;">
          </a>
        </td>
        <td>
          <?php
            $thumb = $current['Thumb_Path'];
            if (empty($thumb)) {
              $thumb = $current['IIIF_URI'] . '/full/,120/0/default.jpg';
            }
            $image = $current['Image_Path'];
            if (empty($image)) {
              $image = $current['IIIF_URI'] . '/full/full/0/default.jpg';
            }
          ?>
          <a target="_imagePopup" href="<?=$this->escapeHtml($image)?>">
            <img src="<?=$this->escapeHtml($thumb)?>" />
          </a>
        </td>
        <td>
          <?php if (!empty($current['Image_Path'])): ?>
            <b>Image Path:</b> <?=$this->escapeHtml($current['Image_Path'])?><br />
          <?php endif; ?>
          <?php if (!empty($current['Thumb_Path'])): ?>
            <b>Thumb Path:</b> <?=$this->escapeHtml($current['Thumb_Path'])?><br />
          <?php endif; ?>
          <?php if (!empty($current['IIIF_URI'])): ?>
            <b>IIIF URI:</b> <?=$this->escapeHtml($current['IIIF_URI'])?><br />
          <?php endif; ?>
          <?php if (!empty($current['Note'])): ?>
            <b>Note:</b> <?=$this->escapeHtml($current['Note'])?>
          <?php endif; ?>
        </td>
      </tr>
    <?php endforeach; ?>
  </table>
<?php endif; ?>