<?php if (count($images ?? []) < 1): ?>
  No images.
<?php else: ?>
  <table class="list_item">
    <tr><th scope="col">Order</th><th colspan="2" scope="col">Image</th><th scope="col">Details</th></tr>
    <?php foreach ($images as $current): ?>
      <tr>
        <td>
          <form onsubmit="Edition.reorderLink('Image', { 'sequence_id': <?=$this->escapeHtml($current['Sequence_ID'])?> }); return false;">
            <label><span class="sr-only">Order: </span><input class="number" type="text" value="<?=$this->escapeHtml($current['Position'])?>" id="image_order_<?=$this->escapeHtml($current['Sequence_ID'])?>" /></label>
            <input type="submit" value="Set" />
          </form>
        </td>
        <td>
          <?=
            $this->iconButton(
                'trash',
                "Edition.unlink('Image', " . $current->getId() . ')',
                ($iiif = $current->getIiifUri())
                  ? "Delete image with IIIF URI: $iiif"
                  : 'Delete image with path: ' . $current->getImagePath()
            )
          ?>
        </td>
        <td>
          <?php
            $thumb = $current->getThumbPath();
            if (empty($thumb)) {
              $thumb = $iiif . '/full/,120/0/default.jpg';
            }
            $image = $current->getImagePath();
            if (empty($image)) {
              $image = $iiif . '/full/full/0/default.jpg';
            }
          ?>
          <a target="_imagePopup" href="<?=$this->escapeHtml($image)?>">
            <span class="sr-only">Open large image</span>
            <img alt="" src="<?=$this->escapeHtml($thumb)?>" />
          </a>
        </td>
        <td>
          <?php if ($imagePath = $current->getImagePath()): ?>
            <b>Image Path:</b> <?=$this->escapeHtml($imagePath)?><br />
          <?php endif; ?>
          <?php if ($thumbPath = $current->getThumbPath()): ?>
            <b>Thumb Path:</b> <?=$this->escapeHtml($thumbPath)?><br />
          <?php endif; ?>
          <?php if ($iiif): ?>
            <b>IIIF URI:</b> <?=$this->escapeHtml($iiif)?><br />
          <?php endif; ?>
          <?php if ($note = $current->getNote()?->getNote()): ?>
            <b>Note:</b> <?=$this->escapeHtml($note)?>
          <?php endif; ?>
        </td>
      </tr>
    <?php endforeach; ?>
  </table>
<?php endif; ?>
