<div id="editEditionForm">
  <input type="hidden" id="Edition_ID" value="<?=$edition['Edition_ID']?>" />
  <table class="edit">
    <tr>
      <th>Edition Name:</th>
      <td><input type="text" id="Edition_Name" value="<?=isset($edition['Edition_Name']) ? $this->escapeHtml($edition['Edition_Name']) : ''?>" /></td>
    </tr>
    <tr>
      <th>Position:</th>
      <td><input type="text" id="Position" value="<?=isset($edition['Position']) ? $this->escapeHtml($edition['Position']) : ''?>" /></td>
    </tr>
    <tr>
      <th>Item:</th>
      <td><input type="text" class="Item_ID" id="Item_ID" value="<?=isset($edition['Item_ID']) ? $this->escapeHtml($edition['Item_ID'] . ': ' . $item['Item_Name']) : ''?>" /></td>
    </tr>
    <tr>
      <th>Series:</th>
      <td><input type="text" class="Series_ID" id="Series_ID" value="<?=isset($edition['Series_ID']) ? $this->escapeHtml($edition['Series_ID'] . ': ' . $series['Series_Name']) : ''?>" /></td>
    </tr>
  </table>
  <button id="save_edition" onclick="saveEdition();">Save</button>
  <div id="save_edition_status"></div>
  <div id="nextAndPrev">
    <? if (isset($next) || isset($previous)): ?>
      <?=$this->render('geeby-deeby/edit-edition/next-and-prev.phtml')?>
    <? endif; ?>
  </div>
</div>
