<div id="editEditionForm" class="form-horizontal" role="form">
  <input type="hidden" id="Edition_ID" value="<?=$edition['Edition_ID']?>" />
  <div class="form-group">
    <label for="Edition_Name" class="col-sm-2 control-label">Edition Name:</label>
    <div class="col-sm-10">
      <input class="form-control" type="text" id="Edition_Name" value="<?=isset($edition['Edition_Name']) ? $this->escapeHtml($edition['Edition_Name']) : ''?>" />
    </div>
  </div>
  <div class="form-group">
    <label for="Edition_Description" class="col-sm-2 control-label">Description:</label>
    <div class="col-sm-10">
      <textarea class="form-control" id="Edition_Description" rows="3"><?=isset($edition['Edition_Description']) ? $this->escapeHtml($edition['Edition_Description']) : ''?></textarea>
    </div>
  </div>
  <div class="form-group">
    <label for="Volume" class="col-sm-2 control-label">Volume:</label>
    <div class="col-sm-10">
      <input class="form-control" type="text" id="Volume" value="<?=isset($edition['Volume']) ? $this->escapeHtml($edition['Volume']) : ''?>" />
    </div>
  </div>
  <div class="form-group">
    <label for="Position" class="col-sm-2 control-label">Position:</label>
    <div class="col-sm-10">
      <input class="form-control" type="text" id="Position" value="<?=isset($edition['Position']) ? $this->escapeHtml($edition['Position']) : ''?>" />
    </div>
  </div>
  <div class="form-group">
    <label for="Replacement_Number" class="col-sm-2 control-label">Replacement Number:</label>
    <div class="col-sm-10">
      <input class="form-control" type="text" id="Replacement_Number" value="<?=isset($edition['Replacement_Number']) ? $this->escapeHtml($edition['Replacement_Number']) : ''?>" />
    </div>
  </div>
  <div class="form-group">
    <label for="Item_ID" class="col-sm-2 control-label">Item:</label>
    <div class="col-sm-10">
      <input class="form-control Item_ID" type="text" id="Edition_Item_ID" value="<?=isset($edition['Item_ID']) ? $this->escapeHtml($edition['Item_ID'] . ': ' . $item['Item_Name']) : ''?>" />
    </div>
  </div>
  <div class="form-group">
    <label for="Series_ID" class="col-sm-2 control-label">Series:</label>
    <div class="col-sm-10">
      <input class="form-control Series_ID" type="text" id="Series_ID" value="<?=isset($edition['Series_ID']) ? $this->escapeHtml($edition['Series_ID'] . ': ' . $series['Series_Name']) : ''?>" />
    </div>
  </div>
  <div class="form-group">
    <label for="Edition_Length" class="col-sm-2 control-label">Length:</label>
    <div class="col-sm-10">
      <input class="form-control" type="text" id="Edition_Length" value="<?=isset($edition['Edition_Length']) ? $this->escapeHtml($edition['Edition_Length']) : ''?>" />
    </div>
  </div>
  <div class="form-group" style="display: none;">
    <label for="Edition_Endings" class="col-sm-2 control-label">Endings:</label>
    <div class="col-sm-10">
      <input class="form-control" type="text" id="Edition_Endings" value="<?=isset($edition['Edition_Endings']) ? $this->escapeHtml($edition['Edition_Endings']) : ''?>" />
    </div>
  </div>
  <div class="form-group">
    <label for="Item_Display_Order" class="col-sm-2 control-label">Display Order in Item:</label>
    <div class="col-sm-10">
      <input class="form-control" type="text" id="Item_Display_Order" value="<?=isset($edition['Item_Display_Order']) ? $this->escapeHtml($edition['Item_Display_Order']) : ''?>" />
    </div>
  </div>
  <div class="collapse" id="parentDetails">
    <div class="form-group">
      <label for="Parent_Edition_ID" class="col-sm-2 control-label">Parent Edition ID (manual edit discouraged):</label>
      <div class="col-sm-10">
        <input class="form-control" type="text" id="Parent_Edition_ID" value="<?=isset($edition['Parent_Edition_ID']) ? $this->escapeHtml($edition['Parent_Edition_ID']) : ''?>" />
      </div>
    </div>
    <div class="form-group">
      <label for="Position_In_Parent" class="col-sm-2 control-label">Position in Parent:</label>
      <div class="col-sm-10">
        <input class="form-control" type="text" id="Position_In_Parent" value="<?=isset($edition['Position_In_Parent']) ? $this->escapeHtml($edition['Position_In_Parent']) : '0'?>" />
      </div>
    </div>
    <div class="form-group">
      <label for="Extent_In_Parent" class="col-sm-2 control-label">Extent in Parent:</label>
      <div class="col-sm-10">
        <input class="form-control" type="text" id="Extent_In_Parent" value="<?=isset($edition['Extent_In_Parent']) ? $this->escapeHtml($edition['Extent_In_Parent']) : ''?>" />
      </div>
    </div>
  </div>
  <? if (count($attributes) > 0): ?>
    <div class="collapse" id="extraAttributes">
      <? foreach ($attributes as $attribute): $attrId = $attribute['Editions_Attribute_ID']; ?>
        <div class="form-group">
          <label for="Edition_Attribute_<?=$attrId?>" class="col-sm-2 control-label"><?=$this->escapeHtml($attribute['Editions_Attribute_Name'])?>:</label>
          <div class="col-sm-10">
            <? if ($attribute['Allow_HTML'] != 1): ?>
              <input class="form-control edition-attribute" type="text" id="Edition_Attribute_<?=$attrId?>" value="<?=isset($attributeValues[$attrId]) ? $this->escapeHtml($attributeValues[$attrId]) : ''?>" />
            <? else: ?>
              <textarea class="form-control edition-attribute" style="width:100%" rows="6" id="Edition_Attribute_<?=$attrId?>"><?=isset($attributeValues[$attrId]) ? $this->escapeHtml($attributeValues[$attrId]) : ''?></textarea>
            <? endif; ?>
          </div>
        </div>
      <? endforeach; ?>
    </div>
  <? endif; ?>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button data-toggle="collapse" data-target="#parentDetails">Toggle Parent Details</button>
      <? if (count($attributes) > 0): ?>
        <button data-toggle="collapse" data-target="#extraAttributes">Toggle Additional Attributes</button>
      <? endif; ?>
      <button id="save_edition" onclick="Edition.save();">Save</button>
    </div>
  </div>
  <div id="save_edition_status"></div>
  <div id="nextAndPrev">
    <? if (isset($next) || isset($previous)): ?>
      <?=$this->render('geeby-deeby/edit-edition/next-and-prev.phtml')?>
    <? endif; ?>
  </div>
</div>
