<?php if (isset($ISBNs) && count($ISBNs) > 0): ?>
  <?php foreach ($ISBNs as $current): ?>
    <table class="list_item">
      <tr>
        <td>
          <?php if (!empty($current['ISBN'])): ?><?=$this->escapeHtml($current['ISBN'])?> / <?php endif; ?><?=$this->escapeHtml($current['ISBN13'])?><?php if (strlen($current['Note']) > 0): ?> (<?=$this->escapeHtml($current['Note'])?>)<?php endif; ?>
        </td>
        <td>
          <?=
            $this->iconButton(
                'trash',
                "Edition.unlink('ISBN', " . $current['Sequence_ID'] . ')',
                'Delete ISBN: ' . (empty($current['ISBN']) ? $current['ISBN13'] : $current['ISBN'])
            )
          ?>
        </td>
      </tr>
    </table>
  <?php endforeach; ?>
<?php else: ?>
  No ISBNs set.
<?php endif; ?>