<?php if (count($isbns ?? []) > 0): ?>
  <?php foreach ($isbns as $current): ?>
    <table class="list_item">
      <tr>
        <td>
          <?php if ($isbn10 = $current->getIsbn10()): ?><?=$this->escapeHtml($isbn10)?> / <?php endif; ?><?=$this->escapeHtml($current->getIsbn13())?><?php if ($note = $current->getNote()?->getNote()): ?> (<?=$this->escapeHtml($note)?>)<?php endif; ?>
        </td>
        <td>
          <?=
            $this->iconButton(
                'trash',
                "Edition.unlink('ISBN', " . $current->getId() . ')',
                'Delete ISBN: ' . ($isbn10 ? $isbn10 : $current->getIsbn13())
            )
          ?>
        </td>
      </tr>
    </table>
  <?php endforeach; ?>
<?php else: ?>
  No ISBNs set.
<?php endif; ?>