<select id="Preferred_Item_Title_ID">
  <option value="NEW">Choose a title from the drop-down or enter a new one in the box below.</option>
  <?php if (isset($itemAltTitles) && count($itemAltTitles) > 0): ?>
    <?php foreach ($itemAltTitles as $current): ?>
      <option value="<?=$current['Sequence_ID']?>"<?=(isset($selected) && $current['Sequence_ID'] == $selected) ? ' selected="selected"' : ''?>>
        <?=$this->escapeHtml($current['Item_AltName'])?>
      </option>
    <?php endforeach; ?>
  <?php endif; ?>
</select>