<?php if (isset($oclcNumbers) && count($oclcNumbers) > 0): ?>
  <?php foreach ($oclcNumbers as $current): ?>
    <table class="list_item">
      <tr>
        <td>
          <?=$this->escapeHtml($current['OCLC_Number'])?><?php if (strlen($current['Note']) > 0): ?> (<?=$this->escapeHtml($current['Note'])?>)<?php endif; ?>
        </td>
        <td>
          <?=
            $this->iconButton(
                'trash',
                "Edition.unlink('OCLCNumber', " . $current['Sequence_ID'] . ')',
                'Delete OCLC number: ' . $current['OCLC_Number']
            )
          ?>
        </td>
      </tr>
    </table>
  <?php endforeach; ?>
<?php else: ?>
  No OCLC numbers set.
<?php endif; ?>