<? if (isset($oclcNumbers) && count($oclcNumbers) > 0): ?>
  <? foreach ($oclcNumbers as $current): ?>
    <table class="list_item">
      <tr>
        <td>
          <?=$this->escapeHtml($current['OCLC_Number'])?><? if (strlen($current['Note']) > 0): ?> (<?=$this->escapeHtml($current['Note'])?>)<? endif; ?>
        </td>
        <td>
          <a class="ui-icon ui-icon-trash" href="#" onclick="deleteOCLCNumber(<?=$current['Sequence_ID']?>); return false;">
          </a>
        </td>
      </tr>
    </table>
  <? endforeach; ?>
<? else: ?>
  No OCLC numbers set.
<? endif; ?>