<?php if (count($oclcNumbers ?? []) > 0): ?>
  <?php foreach ($oclcNumbers as $current): ?>
    <table class="list_item">
      <tr>
        <td>
          <?=$this->escapeHtml($current->getOclcNumber())?><?php if ($note = $current->getNote()?->getNote()): ?> (<?=$this->escapeHtml($note)?>)<?php endif; ?>
        </td>
        <td>
          <?=
            $this->iconButton(
                'trash',
                "Edition.unlink('OCLCNumber', " . $current->getId() . ')',
                'Delete OCLC number: ' . $current->getOclcNumber()
            )
          ?>
        </td>
      </tr>
    </table>
  <?php endforeach; ?>
<?php else: ?>
  No OCLC numbers set.
<?php endif; ?>