<?php if (isset($editionPlatforms) && count($editionPlatforms) > 0): ?>
  <?php foreach ($editionPlatforms as $current): ?>
    <table class="list_item">
      <tr>
        <td>
          <?=$this->escapeHtml($current['Platform'])?>
        </td>
        <td>
          <a class="ui-icon ui-icon-trash" href="#" onclick="Edition.unlink('Platform', <?=$current['Platform_ID']?>); return false;">
          </a>
        </td>
      </tr>
    </table>
  <?php endforeach ?>
<?php else: ?>
  No platforms set.
<?php endif; ?>
