<?php if (isset($editionPlatforms) && count($editionPlatforms) > 0): ?>
  <?php foreach ($editionPlatforms as $current): ?>
    <table class="list_item">
      <tr>
        <td>
          <?=$this->escapeHtml($current['Platform'])?>
        </td>
        <td>
          <?=
            $this->iconButton(
                'trash',
                "Edition.unlink('Platform', " . $current['Platform_ID'] . ")",
                'Unlink platform: ' . $current['Platform']
            )
      ?>
        </td>
      </tr>
    </table>
  <?php endforeach ?>
<?php else: ?>
  No platforms set.
<?php endif; ?>
