<?php if (isset($productCodes) && count($productCodes) > 0): ?>
  <?php foreach ($productCodes as $current): ?>
    <table class="list_item">
      <tr>
        <td>
          <?=$this->escapeHtml($current['Product_Code'])?><?php if (strlen($current['Note']) > 0): ?> (<?=$this->escapeHtml($current['Note'])?>)<?php endif; ?>
        </td>
        <td>
          <?=$this->iconButton(
            'trash',
            "Edition.unlink('ProductCode', " . $this->escapeHtml($current['Sequence_ID']) . ")",
            'Delete product code: ' . $current['Product_Code']
          )?>
        </td>
      </tr>
    </table>
  <?php endforeach; ?>
<?php else: ?>
  No product codes set.
<?php endif; ?>