<?php if (count($productCodes ?? []) > 0): ?>
  <?php foreach ($productCodes as $current): ?>
    <table class="list_item">
      <tr>
        <td>
          <?=$this->escapeHtml($current->getProductCode())?><?php if ($note = $current->getNote()?->getNote()): ?> (<?=$this->escapeHtml($note)?>)<?php endif; ?>
        </td>
        <td>
          <?=
            $this->iconButton(
                'trash',
                "Edition.unlink('ProductCode', " . $current->getId() . ')',
                'Delete product code: ' . $current->getProductCode()
            )
          ?>
        </td>
      </tr>
    </table>
  <?php endforeach; ?>
<?php else: ?>
  No product codes set.
<?php endif; ?>