<select id="Preferred_Series_Title_ID">
  <option value="NEW">Choose a title from the drop-down or enter a new one in the box below.</option>
  <?php if (isset($seriesAltTitles) && count($seriesAltTitles) > 0): ?>
    <?php foreach ($seriesAltTitles as $current): ?>
      <option value="<?=$current['Sequence_ID']?>"<?=(isset($selected) && $current['Sequence_ID'] == $selected) ? ' selected="selected"' : ''?>>
        <?=$this->escapeHtml($current['Series_AltName'])?>
      </option>
    <?php endforeach; ?>
  <?php endif; ?>
</select>