<select id="<?=!empty($idPrefix) ? $this->escapeHtml($idPrefix) : ''?>Series_Publisher_ID">
  <option value="">-- none --</option>
  <?php if (isset($publishers) && count($publishers) > 0): ?>
    <?php foreach ($publishers as $current): ?>
      <option value="<?=$current['Series_Publisher_ID']?>"<?=(isset($selected) && $current['Series_Publisher_ID'] == $selected) ? ' selected="selected"' : ''?>>
          <?=$this->escapeHtml($current['Publisher_Name'])?>
          <?php if (!empty($current['Country_Name']) || !empty($current['Imprint_Name']) || !empty($current['Note'])): ?>
            (<?php
              $city = (empty($current['City_Name']) ? '' : ' -- ' . $current['City_Name']);
              $street = (empty($current['Street']) ? '' : ' -- ' . $current['Street']);
              $address = $current['Country_Name'] . $city . $street;
              echo strlen($current['Imprint_Name']) > 0 ? $this->escapeHtml($current['Imprint_Name']) . ((strlen($address) > 0 || strlen($current['Note']) > 0) ? ': ' : '') : '';
              echo strlen($address) > 0 ? $this->escapeHtml($address) : '';
              echo strlen($current['Note']) > 0 ? ((strlen($address) > 0 || strlen($current['Imprint_Name']) > 0) ? ' - ' : '') . $this->escapeHtml($current['Note']) : '';
              ?>)
          <?php endif; ?>
       </option>
    <?php endforeach; ?>
  <?php endif; ?>
</select>