<?=$this->doctype(); ?>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <?=$this->headTitle($this->layout()->title .' - '. $this->config('siteTitle')) ?>

    <?=$this->headLink()
            ->prependStylesheet($this->basePath() . '/css/ui-lightness/jquery-ui-1.7.2.custom.css')
            ->prependStylesheet($this->basePath() . '/css/geeby-deeby.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
            ->prependStylesheet($this->basePath() . '/css/fonts.css')
    ?>

    <? // Set global path for Javascript code: ?>
    <?=$this->headScript()->prependScript("basePath = '" . rtrim($this->basePath(), '/') . "';"); ?>

    <?=$this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9'))
           ->prependFile($this->basePath() . '/js/bootstrap.min.js')
           ->prependFile($this->basePath() . '/js/jquery-ui.js')
           ->prependFile($this->basePath() . '/js/jquery.js');
    ?>
  </head>
  <body>
    <header>
      <div class="container">
        <?=$this->render('partials/header.phtml')?>
      </div>
    </header>
    <div class="container main">
      <h1><?=$this->layout()->title ?></h1>
      <div class="content">
        <?=$this->content; ?>
        <?=$this->render('partials/modal.phtml')?>
      </div>
      <footer>
        <?=$this->render('partials/footer.phtml')?>
      </footer>
    </div>
  </body>
</html>
