<? echo $this->doctype(); ?>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <? echo $this->headTitle($this->config('siteTitle')) ?>

    <? echo $this->headLink()
           ->prependStylesheet($this->basePath() . '/css/ui-lightness/jquery-ui-autocomplete.css')
           ->prependStylesheet($this->basePath() . '/css/ui-lightness/jquery-ui-1.7.2.custom.css')
           ->prependStylesheet($this->basePath() . '/css/geeby-deeby.css')
           ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
    ?>

    <?
      // Set global path for Javascript code:
      $this->headScript()->prependScript("basePath = '" . rtrim($this->basePath(), '/') . "';");
    ?>

    <? echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
           ->prependFile($this->basePath() . '/js/bootstrap.min.js')
           ->prependFile($this->basePath() . '/js/jquery-ui.js')
           ->prependFile($this->basePath() . '/js/jquery.js');
    ?>
  </head>
  <body>
    <div class="container">
      <header class="clearfix">
        <?=$this->render('partials/header.phtml')?>
      </header>
      <? echo $this->content; ?>
      <?=$this->render('partials/footer.phtml')?>
    </div>
  </body>
</html>
