<?php $this->layout()->title = 'Approve New Users / Content' ?>
<?php $this->scriptManager()->add(['autocomplete', 'approve']) ?>
<?php $displayedSomething = false; ?>
<?php if (count($newUsers) > 0): $displayedSomething = true; ?>
  <h2>New Users</h2>
  <table>
    <tr>
      <th id="approvalUsername" scope="col">Username</th>
      <th id="approvalFullname" scope="col">Full Name</th>
      <th id="approvalEmail" scope="col">Email</th>
      <th id="approvalPerson" scope="col">Person Record</th>
      <th id="approvalOptions" scope="col">Options</th>
    </tr>
    <?php foreach ($newUsers as $i => $current): ?>
      <tr id="NewUser_<?=$current['User_ID']?>">
        <td>
          <span id="usernameLabel<?=$i?>" class="sr-only"><?=$this->escapeHtml($current['Username'])?></span>
          <input aria-labelledby="usernameLabel<?=$i?> approvalUsername" form="approveForm<?=$i?>" type="text" id="Username_<?=$current['User_ID']?>" value="<?=$this->escapeHtml($current['Username'])?>"/>
        </td>
        <td><input aria-labelledby="usernameLabel<?=$i?> approvalFullname" form="approveForm<?=$i?>" type="text" id="Name_<?=$current['User_ID']?>" value="<?=$this->escapeHtml($current['Name'])?>"/></td>
        <td><input aria-labelledby="usernameLabel<?=$i?> approvalEmail" form="approveForm<?=$i?>" type="email" id="Address_<?=$current['User_ID']?>" value="<?=$this->escapeHtml($current['Address'])?>"/></td>
        <td><input aria-labelledby="usernameLabel<?=$i?> approvalPerson" form="approveForm<?=$i?>" class="Person_ID" id="Person_ID_<?=$current['User_ID']?>" value="-1 (normal user)"/></td>
        <td id="UserButtons_<?=$current['User_ID']?>">
          <form id="approveForm<?=$i?>" onsubmit="approveUser(<?=$current['User_ID']?>); return false;">
            <input type="submit" value="Approve" />
          </form>
          <button onclick="rejectUser(<?=$current['User_ID']?>);">Reject</button>
        </td>
      </tr>
    <?php endforeach; ?>
  </table>
<?php endif; ?>
<?php if (count($pendingReviews) > 0): $displayedSomething = true; ?>
  <h2>New Item Reviews</h2>
  <table class="approve">
    <tr>
      <th scope="col">Item / User</th>
      <th id="reviewLabel" scope="col">Review</th>
      <th scope="col">Options</th>
    </tr>
    <?php foreach ($pendingReviews as $i => $current): ?>
      <tr id="PendingReview_<?=$current['User_ID']?>_<?=$current['Item_ID']?>">
        <td id="reviewItem<?=$i?>"><?=$this->escapeHtml($current['Item_Name'])?><br /><?=$this->escapeHtml($current['Username'])?></td>
        <td>
          <textarea aria-labelledby="reviewItem<?=$i?> reviewLabel" id="ReviewText_<?=$current['User_ID']?>_<?=$current['Item_ID']?>" rows="8" cols="60"><?=$this->escapeHtml($current['Review'])?></textarea>
        </td>
        <td id="ReviewButtons_<?=$current['User_ID']?>_<?=$current['Item_ID']?>" style="text-align: center">
          <button onclick="approveReview(<?=$current['User_ID']?>, <?=$current['Item_ID']?>);">Approve</button>
          <button onclick="rejectReview(<?=$current['User_ID']?>, <?=$current['Item_ID']?>);">Reject</button>
        </td>
      </tr>
    <?php endforeach; ?>
  </table>
<?php endif; ?>
<?php if (count($pendingComments) > 0): $displayedSomething = true; ?>
  <h2>New Series Comments</h2>
  <table class="approve">
    <tr>
      <th scope="col">Series / User</th>
      <th id="commentLabel" scope="col">Comment</th>
      <th scope="col">Options</th>
    </tr>
    <?php foreach ($pendingComments as $i => $current): ?>
      <tr id="PendingComment_<?=$current['User_ID']?>_<?=$current['Series_ID']?>">
        <td id="commentSeries<?=$i?>"><?=$this->escapeHtml($current['Series_Name'])?><br /><?=$this->escapeHtml($current['Username'])?></td>
        <td>
          <textarea aria-labelledby="commentSeries<?=$i?> commentLabel" id="CommentText_<?=$current['User_ID']?>_<?=$current['Series_ID']?>" rows="8" cols="60"><?=$this->escapeHtml($current['Review'])?></textarea>
        </td>
        <td id="CommentButtons_<?=$current['User_ID']?>_<?=$current['Series_ID']?>" style="text-align: center">
          <button onclick="approveComment(<?=$current['User_ID']?>, <?=$current['Series_ID']?>);">Approve</button>
          <button onclick="rejectComment(<?=$current['User_ID']?>, <?=$current['Series_ID']?>);">Reject</button>
        </td>
      </tr>
    <?php endforeach; ?>
  </table>
<?php endif; ?>
<?php if (!$displayedSomething): ?>
  <p>No pending approvals.</p>
<?php endif; ?>