<?php if (count($this->selectedCitations) == 0): ?>
  No citations.
<?php else: ?>
  <table>
    <?php foreach ($this->selectedCitations as $current): ?>
      <tr>
        <td>
          <?=$this->escapeHtml($current['Citation'])?>
        </td>
        <td>
          <?=
            $this->iconButton(
                'trash',
                "ItemCreator.unlink('Citation', " . $current['Citation_ID'] . ')',
                'Unlink citation: ' . $current['Citation']
            )
        ?>
        </td>
      </tr>
    <?php endforeach; ?>
  </table>
<?php endif; ?>