<form id="editForm" onsubmit="Platform.save(); return false;">
  <input type="hidden" id="Platform_ID" value="<?=$platform['Platform_ID']?>" />
  <table class="edit">
    <tr>
      <th scope="row"><label for="Platform_Name">Platform:</label></th>
      <td><input type="text" id="Platform_Name" value="<?=isset($platform['Platform']) ? $this->escapeHtml($platform['Platform']) : ''?>" /></td>
    </tr>
  </table>
  <input type="submit" value="Save" />
  <div id="save_platform_status"></div>
</form>
