<?php if (isset($platforms) && count($platforms) > 0): ?>
  <select id="<?=!empty($idPrefix) ? $this->escapeHtml($idPrefix) : ''?>Platform_ID">
    <?php foreach ($platforms as $current): ?>
      <option value="<?=$current['Platform_ID']?>"<?=(isset($selected) && $current['Platform_ID'] == $selected) ? ' selected="selected"' : ''?>>
        <?=$this->escapeHtml($current['Platform'])?>
      </option>
    <?php endforeach; ?>
  </select>
<?php else: ?>
  Please define platforms.
<?php endif; ?>