<div id="editForm">
  <input type="hidden" id="Material_Type_ID" value="<?=$material['Material_Type_ID']?>" />
  <table class="edit">
    <tr>
      <th scope="row">Name (singular):</th>
      <td><input type="text" id="Material_Type_Name" value="<?=isset($material['Material_Type_Name']) ? $this->escapeHtml($material['Material_Type_Name']) : ''?>" /></td>
    </tr>
    <tr>
      <th scope="row">Name (plural):</th>
      <td><input type="text" id="Material_Type_Plural_Name" value="<?=isset($material['Material_Type_Plural_Name']) ? $this->escapeHtml($material['Material_Type_Plural_Name']) : ''?>" /></td>
    </tr>
    <tr>
      <th scope="row">RDF Class (optional URI):</th>
      <td><input type="text" id="Material_Type_RDF_Class" value="<?=isset($material['Material_Type_RDF_Class']) ? $this->escapeHtml($material['Material_Type_RDF_Class']) : ''?>" /></td>
    </tr>
    <tr>
      <th scope="row">Set as default:</th>
      <td><input type="checkbox" id="Default" value="1" <?=isset($material['Default']) && $material['Default'] == 1 ? 'checked="checked" ' : ''?>/></td>
    </tr>
  </table>
  <button id="save_material_type" onclick="MaterialType.save();">Save</button>
  <div id="save_material_type_status"></div>
</div>
