<? $this->layout()->title = 'Edit Material Types' ?>
<? $this->headScript()->appendFile($this->basePath() . '/js/base_editor.js') ?>
<? $this->headScript()->appendFile($this->basePath() . '/js/edit_materials.js') ?>
<p><b>Material Types:</b></p>
<button id="add_material_type" type="button" onclick="MaterialType.edit('NEW');">Add Material Type</button>
<br /><br />
<div id="material_type_list"><?=$this->render('geeby-deeby/edit-material-type/render-material-types.phtml')?></div>
