<? if (isset($materials) && count($materials) > 0): ?>
  <select class="form-control" id="<?=!empty($idPrefix) ? $this->escapeHtml($idPrefix) : ''?>Material_Type_ID">
    <? foreach ($materials as $current): ?>
      <? $isSelected = (isset($selected) && !empty($selected)) ? ($current['Material_Type_ID'] == $selected) : ($current['Default'] == 1) ?>
      <option value="<?=$current['Material_Type_ID']?>"<?=$isSelected ? ' selected="selected"' : ''?>>
        <?=$this->escapeHtml($current['Material_Type_Name'])?>
      </option>
    <? endforeach; ?>
  </select>
<? else: ?>
  Please define material types.
<? endif; ?>