<?php if (isset($materials) && count($materials) > 0): ?>
  <select id="<?=!empty($idPrefix) ? $this->escapeHtml($idPrefix) : ''?>Material_Type_ID">
    <?php foreach ($materials as $current): ?>
      <?php $isSelected = (isset($selected) && !empty($selected)) ? ($current->getId() == $selected) : $current->isDefault() ?>
      <option value="<?=$current->getId()?>"<?=$isSelected ? ' selected="selected"' : ''?>>
        <?=$this->escapeHtml($current->getSingularName())?>
      </option>
    <?php endforeach; ?>
  </select>
<?php else: ?>
  Please define material types.
<?php endif; ?>