<?
    $title = $country['Country_Name'];
    $this->headTitle('Country - ' . $title . ' - ');
    $displayedSomething = false;
?>
<h1><?=$this->escapeHtml($title)?></h1>

<? if (count($series) < 1): ?>
  <p>No information is available about this country.</p>
<? else: ?>
  <? $currentLetter = false; foreach ($series as $current): ?>
    <? $first = $this->firstletter($current['Series_Name']); if ($currentLetter !== $first): $currentLetter = $first; ?>
      <h2><?=$this->escapeHtml($currentLetter)?></h2>
    <? endif; ?>
    <a href="<?=$this->url('series', array('id' => $current['Series_ID']))?>">
      <?=$this->escapeHtml($this->fixtitle($current['Series_Name']))?>
    </a><br />
  <? endforeach; ?>
<? endif; ?>