<?
    $this->headTitle('Country List - ');
?>
<h1>Country List</h1>
<? if (count($countries) < 1): ?>
  <p>No countries listed in this database yet.</p>
<? else: ?>
  <? $currentLetter = false; foreach ($countries as $current): ?>
    <? $first = $this->firstletter($current['Country_Name']); if ($currentLetter !== $first): $currentLetter = $first; ?>
      <h2><?=$this->escapeHtml($currentLetter)?></h2>
    <? endif; ?>
    <a href="<?=$this->url('country', array('id' => $current['Country_ID']))?>">
      <?=$this->escapeHtml($this->fixtitle($current['Country_Name']))?>
    </a><br />
  <? endforeach; ?>
<? endif; ?>