<?php
    $this->layout()->title = 'Country List';
?>
<?php if (count($countries) < 1): ?>
  <p>No countries listed in this database yet.</p>
<?php else: ?>
  <h2>
    <?=$this->firstLetterMenu($countries, 'Country_Name'); ?>
  </h2>
  <?php $currentLetter = false; foreach ($countries as $i => $current): ?>
    <?php $first = $this->firstletter($current['Country_Name']); ?>
    <?php if ($currentLetter !== $first): $currentLetter = $first; ?>
      <?php if ($i > 0): ?>
        <a name="<?=$this->escapeHtml($currentLetter)?>"/>
        <h2><?=$this->escapeHtml($currentLetter)?><a href="#" style="float:right">Back to Top &uarr;</a></h2>
      <?php endif; ?>
    <?php endif; ?>
    <a href="<?=$this->url('country', ['id' => $current['Country_ID']])?>">
      <?=$this->escapeHtml($this->fixtitle($current['Country_Name']))?>
    </a><br />
  <?php endforeach; ?>
<?php endif; ?>