<?php
$title = $country['Country_Name'];
$this->layout()->title = 'Country - ' . $title;
$displayedSomething = false;
?>
<?php if (count($series) < 1): ?>
  <p>No information is available about this country.</p>
<?php else: ?>
  <h2>
    <?=$this->firstLetterMenu($series, 'Series_Name'); ?>
  </h2>
  <?php $currentLetter = false;
    foreach ($series as $i => $current): ?>
    <?php $first = $this->firstletter($current['Series_Name']); ?>
    <?php if ($currentLetter !== $first): $currentLetter = $first; ?>
      <?php if ($i > 0): ?>
        <h2><?=$this->escapeHtml($currentLetter)?><a href="#" style="float:right">Back to Top &uarr;</a></h2>
      <?php endif; ?>
    <?php endif; ?>
    <a href="<?=$this->url('series', ['id' => $current['Series_ID']])?>">
      <?=$this->escapeHtml($this->fixtitle($current['Series_Name']))?>
    </a><br />
  <?php endforeach; ?>
<?php endif; ?>