<?php
$this->layout()->title = 'Search Results - ISBN';
?>
<?php if (count($results) < 1): ?>
  <p>No results found for <?=$this->escapeHtml($this->layout()->query)?>.</p>
<?php else: ?>
  <p>
    <?php foreach ($results as $result): ?>
      <a href="<?=$this->url('item', ['id' => $result['Item_ID']])?>">
        <?=$this->escapeHtml($this->fixtitle($result['Item_Name']))?>
      </a>
      (<?=empty($result['ISBN']) ? '' : $this->escapeHtml($result['ISBN']) . ' / '?><?=$this->escapeHtml($result['ISBN13'])?>)
      <br />
    <?php endforeach; ?>
  </p>
<?php endif; ?>