<?php
    $this->layout()->title = 'Search Results - ISBN';
?>
<?php if (count($results) < 1): ?>
  <p>No results found for <?=$this->escapeHtml($this->layout()->query)?>.</p>
<?php else: ?>
  <h2>ISBNs</h2>
  <ol>
    <?php foreach ($results as $result): ?>
      <li>
        <a href="<?=$this->url('item', ['id' => $result['Item_ID']])?>">
          <?=$this->escapeHtml($this->fixtitle($result['Item_Name']))?>
        </a>
        (<?=empty($result['ISBN']) ? '' : $this->escapeHtml($result['ISBN']) . ' / '?><?=$this->escapeHtml($result['ISBN13'])?>)
      </li>
    <?php endforeach; ?>
  </ol>
<?php endif; ?>