<div class="col-md-3">
  <h2><?=$this->title ?></h2>
  <?php foreach ($this->items as $i => $current): ?>
    <div class="result row">
      <span class="number col-md-1"><?=$i + 1 ?></span>
      <a class="col-md-10" href="<?=$this->url(strtolower($this->prefix), ['id' => $current[$this->prefix . '_ID']])?>">
        <?=$this->escapeHtml($this->fixtitle($current[$this->prefix . '_Name'] ?? $current[$this->prefix . '_AltName']))?>
      </a>
    </div>
    <?php if ($this->prefix === 'Item'): ?>
      <div class="result row hidden creators" data-loaded="0" data-item-id="<?=$current[$this->prefix . '_ID']?>">
        <span class="col-md-1">&nbsp;</span>
        <span class="col-md-10 values"></span>
      </div>
    <?php endif; ?>
  <?php endforeach; ?>
</div>