<?php
    $this->layout()->title = 'Search Results - Person';
?>

<?php if (count($people) > 0): ?>
  <p>
    <?php foreach ($people as $current): ?>
      <a href="<?=$this->url('person', ['id' => $current['Person_ID']])?>">
        <?=$this->escapeHtml($this->showperson($current))?>
      </a><br />
    <?php endforeach; ?>
  </p>
<?php else: ?>
  <p>No results found for <?=$this->escapeHtml($this->layout()->query)?>.</p>
<?php endif; ?>