<?php
    $this->layout()->title = 'Search Results - Person';
?>

<?php if (count($people) > 0): ?>
  <h2>People</h2>
  <ol>
    <?php foreach ($people as $current): ?>
      <li>
        <a href="<?=$this->url('person', ['id' => $current['Person_ID']])?>">
          <?=$this->escapeHtml($this->showperson($current))?>
        </a>
      </li>
    <?php endforeach; ?>
    </ol>
<?php else: ?>
  <p>No results found for <?=$this->escapeHtml($this->layout()->query)?>.</p>
<?php endif; ?>