<?
    $this->headTitle('Search Results - Title - ');
    $empty = true;
?>
<h1>Search Results - Title</h1>
<? if (count($series) > 0): $empty = false; ?>
  <h2>Series</h2>
  <p>
    <? foreach ($series as $current): ?>
      <a href="<?=$this->url('series', array('id' => $current['Series_ID']))?>">
        <?=$this->escapeHtml($this->fixtitle($current['Series_Name']))?>
      </a><br />
    <? endforeach; ?>
  </p>
<? endif; ?>
<? if (count($seriesAltTitles) > 0): $empty = false; ?>
  <h2>Series Alternate Titles</h2>
  <p>
    <? foreach ($seriesAltTitles as $current): ?>
      <a href="<?=$this->url('series', array('id' => $current['Series_ID']))?>">
        <?=$this->escapeHtml($this->fixtitle($current['Series_AltName']))?>
      </a><br />
    <? endforeach; ?>
  </p>
<? endif; ?>
<? if (count($items) > 0): $empty = false; ?>
  <h2>Items</h2>
  <p>
    <? foreach ($items as $current): ?>
      <a href="<?=$this->url('item', array('id' => $current['Item_ID']))?>">
        <?=$this->escapeHtml($this->fixtitle($current['Item_Name']))?>
      </a><br />
    <? endforeach; ?>
  </p>
<? endif; ?>
<? if (count($itemsAltTitles) > 0): $empty = false; ?>
  <h2>Item Alternate Titles</h2>
  <p>
    <? foreach ($itemsAltTitles as $current): ?>
      <a href="<?=$this->url('item', array('id' => $current['Item_ID']))?>">
        <?=$this->escapeHtml($this->fixtitle($current['Item_AltName']))?>
      </a><br />
    <? endforeach; ?>
  </p>
<? endif; ?>
<? if ($empty): ?>
  <p>No results found for <?=$this->escapeHtml($this->layout()->query)?>.</p>
<? endif; ?>