<?
    $this->headTitle('Search Results - Title - ');
    $empty = true;
    $lists = array(
      'Series' => $series,
      'Series Alternate Titles' => $seriesAltTitles,
      'Item' => $items,
      'Item Alternate Titles' => $itemsAltTitles,
    );
?>
<h1>Search Results - Title</h1>
<div class="results row">
  <? foreach($lists as $title=>$results): ?>
    <? if (count($results) > 0): $empty = false; ?>
      <? $prefix = explode(' ', $title); ?>
      <?=$this->render('geeby-deeby/search/list.phtml', array('title'=>$title,'items'=>$results,'prefix'=>$prefix[0])) ?>
    <? endif; ?>
  <? endforeach; ?>
  <? if ($empty): ?>
    <p>No results found for <?=$this->escapeHtml($this->layout()->query)?>.</p>
  <? endif; ?>
</div>