<? if (isset($adaptedFrom) && count($adaptedFrom) > 0): ?>
  <? foreach ($adaptedFrom as $current): ?>
    <table class="list_item">
      <tr>
        <td>
          <a href="<?=$this->url('edit/item', array('id' => $current['Item_ID']))?>#adaptations-tab">
            <?=$this->escapeHtml($current['Item_Name'])?>
          </a>
        </td>
        <td>
          <a class="ui-icon ui-icon-trash" href="#" onclick="Item.unlink('Adaptation', <?=$current['Item_ID']?>, 'From'); return false;">
          </a>
        </td>
      </tr>
    </table>
  <? endforeach; ?>
<? else: ?>
  No relevant items.
<? endif; ?>
