<?php if (isset($adaptedInto) && count($adaptedInto) > 0): ?>
  <?php foreach ($adaptedInto as $current): ?>
    <table class="list_item">
      <tr>
        <td>
          <a href="<?=$this->url('edit/item', ['id' => $current['Item_ID']])?>#adaptations-tab">
            <?=$this->escapeHtml($current['Item_Name'])?>
          </a>
        </td>
        <td>
          <?=
            $this->iconButton(
                'trash',
                "Item.unlink('Adaptation', " . $current['Item_ID'] . ", 'Into')",
                'Unlink adaptation into: ' . $current['Item_Name']
            )
          ?>
        </td>
      </tr>
    </table>
  <?php endforeach; ?>
<?php else: ?>
  No relevant items.
<?php endif; ?>
