<?php if (!isset($creators) || count($creators) < 1): ?>
  No creators.
<?php else: ?>
  <table class="list_item">
    <tr><th colspan="3" scope="col">Creator</th></tr>
    <?php foreach ($creators as $current): ?>
      <tr>
        <td>
          <?=$this->escapeHtml($current['Role_Name'])?>:
          <a href="<?=$this->url('edit/person', ['id' => $current['Person_ID']])?>">
            <?=$this->escapeHtml($this->showperson($current))?>
          </a>
        </td>
        <td>
          <a class="ui-icon ui-icon-gear" href="#" onclick="Item.editLink('Creator', <?=$current['Item_Creator_ID']?>); return false;">
          </a>
        </td>
        <td>
          <a class="ui-icon ui-icon-trash" href="#" onclick="Item.unlink('Creator', '<?=$this->escapeHtml($current['Person_ID'])?>,<?=$this->escapeHtml($current['Role_ID'])?>'); return false;">
          </a>
        </td>
      </tr>
    <?php endforeach; ?>
  </table>
<?php endif; ?>