<?php if (!isset($creators) || count($creators) < 1): ?>
  No creators.
<?php else: ?>
  <table class="list_item">
    <tr><th colspan="3" scope="col">Creator</th></tr>
    <?php foreach ($creators as $current): ?>
      <?php $currentName = $this->showperson($current); ?>
      <tr>
        <td>
          <?=$this->escapeHtml($current['Role_Name'])?>:
          <a href="<?=$this->url('edit/person', ['id' => $current['Person_ID']])?>">
            <?=$this->escapeHtml($currentName)?>
          </a>
        </td>
        <td>
          <?=$this->iconButton(
            'gear',
            "Item.editLink('Creator', '" . $this->escapeHtml($current['Person_ID']) . ',' . $this->escapeHtml($current['Role_ID']) . "')",
            'Edit options for ' . $current['Role_Name'] . ': ' . $currentName
          )?>
        </td>
        <td>
          <?=$this->iconButton(
            'trash',
            "Item.unlink('Creator', '" . $this->escapeHtml($current['Person_ID']) . ',' . $this->escapeHtml($current['Role_ID']) . "')",
            'Unlink ' . $current['Role_Name'] . ': ' . $currentName
          )?>
        </td>
      </tr>
    <?php endforeach; ?>
  </table>
<?php endif; ?>