<?php if (!isset($credits) || count($credits) < 1): ?>
  No credits.
<?php else: ?>
  <table class="list_item">
    <tr><th scope="col">Order</th><th colspan="2" scope="col">Credit</th></tr>
    <?php foreach ($credits as $current): ?>
      <?php $currentName = $this->showperson($current); ?>
      <tr>
        <td>
          <input class="number" type="text" value="<?=$this->escapeHtml($current['Position'])?>" id="credit_order_<?=$this->escapeHtml($current['Person_ID'])?>_<?=$this->escapeHtml($current['Role_ID'])?>" />
          <button onclick="Item.reorderLink('Credit', { 'person_id': <?=$this->escapeHtml($current['Person_ID'])?>, 'role_id': <?=$this->escapeHtml($current['Role_ID'])?> });">Set</button>
        </td>
        <td>
          <?=$this->iconButton(
            'trash',
            "Item.unlink('Credit', '" . $current['Person_ID'] . ',' . $current['Role_ID'] . "')",
            'Unlink ' . $current['Role_Name'] . ': ' . $currentName
          )?>
        </td>
        <td>
          <?=$this->escapeHtml($current['Role_Name'])?>:
          <a href="<?=$this->url('edit/person', ['id' => $current['Person_ID']])?>">
            <?=$this->escapeHtml($currentName)?>
          </a>
          <?php if (!empty($current['Note'])): ?>
            (<?=$this->escapeHtml($current['Note'])?>)
          <?php endif; ?>
        </td>
      </tr>
    <?php endforeach; ?>
  </table>
<?php endif; ?>