<?php if (!isset($credits) || count($credits) < 1): ?>
  No credits.
<?php else: ?>
  <table class="list_item">
    <tr><th>Order</th><th colspan="2">Credit</th></tr>
    <?php foreach ($credits as $current): ?>
      <tr>
        <td>
          <input class="number" type="text" value="<?=$this->escapeHtml($current['Position'])?>" id="credit_order_<?=$this->escapeHtml($current['Person_ID'])?>_<?=$this->escapeHtml($current['Role_ID'])?>" />
          <button onclick="Item.reorderLink('Credit', { 'person_id': <?=$this->escapeHtml($current['Person_ID'])?>, 'role_id': <?=$this->escapeHtml($current['Role_ID'])?> });">Set</button>
        </td>
        <td>
          <a class="ui-icon ui-icon-trash" href="#" onclick="Item.unlink('Credit', '<?=$this->escapeHtml($current['Person_ID'])?>,<?=$this->escapeHtml($current['Role_ID'])?>'); return false;">
          </a>
        </td>
        <td>
          <?=$this->escapeHtml($current['Role_Name'])?>:
          <a href="<?=$this->url('edit/person', ['id' => $current['Person_ID']])?>">
            <?=$this->escapeHtml($this->showperson($current))?>
          </a>
          <?php if (!empty($current['Note'])): ?>
            (<?=$this->escapeHtml($current['Note'])?>)
          <?php endif; ?>
        </td>
      </tr>
    <?php endforeach; ?>
  </table>
<?php endif; ?>