<?php if (isset($descriptions) && count($descriptions) > 0): ?>
  <?php foreach ($descriptions as $current): ?>
  <table class="list_item">
    <tr>
      <td>
        <?php /* Note: Description is not escaped since it may contain HTML! */ ?>
        <?=$current['Description']?> (Source: <?=$this->descriptionSource()->getName($current['Source'])?>)
      </td>
      <td>
        <a class="ui-icon ui-icon-trash" href="#" onclick="Item.unlink('Description', &quot;<?=$this->escapeHtml($current['Source'])?>&quot;); return false;">
        </a>
      </td>
    </tr>
  </table>
  <?php endforeach; ?>
<?php else: ?>
  No descriptions set.
<?php endif; ?>
