<?php if (isset($descriptions) && count($descriptions) > 0): ?>
  <?php foreach ($descriptions as $current): ?>
  <?php $sourceName = $this->descriptionSource()->getName($current['Source']); ?>
  <table class="list_item">
    <tr>
      <td>
        <?php /* Note: Description is not escaped since it may contain HTML! */ ?>
        <?=$current['Description']?> (Source: <?=$sourceName?>)
      </td>
      <td>
        <?=$this->iconButton(
            'trash',
            "Item.unlink('Description', '" . addslashes($current['Source']) . "')",
            'Delete description from ' . $sourceName
          )?>
      </td>
    </tr>
  </table>
  <?php endforeach; ?>
<?php else: ?>
  No descriptions set.
<?php endif; ?>
