<? $this->headScript()->prependFile($this->basePath() . '/js/edit_item_details.js') ?>
<? $this->headScript()->prependFile($this->basePath() . '/js/ui.tabs.paging.js') ?>
<h1>Edit Item</h1>
<div class="edit_container" style="width: 800px;">
  <?=$this->render('geeby-deeby/edit-item/index.phtml')?>
</div>
<hr />
<div id="tabs">
  <ul>
    <li><a href="#adaptations-tab"><span>Adaptations</span></a></li>
    <li><a href="#alt-titles-tab"><span>Alternate Titles</span></a></li>
    <li><a href="#attached-tab"><span>Attached Items</span></a></li>
    <li><a href="#codes-tab"><span>Codes/ISBNs</span></a></li>
    <li><a href="#credits-tab"><span>Credits</span></a></li>
    <li><a href="#release-tab"><span>Dates</span></a></li>
    <li><a href="#desc-tab"><span>Descriptions</span></a></li>
    <li><a href="#images-tab"><span>Images</span></a></li>
    <li><a href="#platforms-tab"><span>Platforms</span></a></li>
    <li><a href="#bib-tab"><span>References</span></a></li>
    <li><a href="#translations-tab"><span>Translations</span></a></li>
  </ul>

  <div id="adaptations-tab" class="edit_tab_contents">
    <select id="adapt_type">
      <option value='from'>Adapted From</option>
      <option value='into'>Adapted Into</option>
    </select>
    <input id="adapt_name" class="Item_ID" />
    <button onclick="saveAdaptation();">Add Adaptation</button>
    <table>
      <tr>
        <td>
          <b>Adapted From:</b>
          <div id="adapt_from">
            <?=$this->render('geeby-deeby/edit-item/adapted-from-list.phtml')?>
          </div>
        </td>
        <td>
          <b>Adapted Into:</b>
          <div id="adapt_into">
            <?=$this->render('geeby-deeby/edit-item/adapted-into-list.phtml')?>
          </div>
        </td>
      </tr>
    </table>
  </div>

  <div id="alt-titles-tab" class="edit_tab_contents">
    <b>Title:</b> <input type="text" id="Alt_Title" />
    <b>Note: </b> <input id="Alt_Title_Note" class="Note_ID" />
    <button onclick="addAltTitle();">Add</button>
    <div id="alt_title_list">
      <?=$this->render('geeby-deeby/edit-item/alt-title-list.phtml')?>
    </div>
  </div>

  <div id="attached-tab" class="edit_tab_contents">
    <input id="attachment_name" class="Item_ID" />
    <button onclick="addAttachedItem();">Add Item</button>
    <div id="item_list">
      <?=$this->render('geeby-deeby/edit-item/list.phtml')?>
    </div>
  </div>

  <div id="bib-tab" class="edit_tab_contents">
    <p>The current item is about the following items, series and people...</p>
    <b>Item References:</b>
    <input id="item_bib_id" class="Item_ID" />
    <button onclick="addItemReference();">Add Reference</button>
    <div id="item_bib">
      <?=$this->render('geeby-deeby/edit-item/item-ref-list.phtml')?>
    </div>
    <b>Series References:</b>
    <input id="series_bib_id" class="Series_ID" />
    <button onclick="addSeriesReference();">Add Reference</button>
    <div id="series_bib">
      <?=$this->render('geeby-deeby/edit-item/series-ref-list.phtml')?>
    </div>
    <b>Person References:</b>
    <input id="person_bib_id" class="Person_ID" />
    <button onclick="addPersonReference();">Add Reference</button>
    <div id="people_bib">
      <?=$this->render('geeby-deeby/edit-item/person-ref-list.phtml')?>
    </div>
  </div>

  <div id="codes-tab" class="edit_tab_contents">
    <table>
      <tr>
        <td style="width: 50%;">
          <table class="edit">
            <tr><th>New ISBN</th><td><input type="text" id="isbn" /></td></tr>
            <tr><th>Note:</th><td><input id="isbn_note" class="Note_ID" /></td></tr>
            <tr><th></th><td><button onclick="addISBN();">Add</button></td></tr>
          </table>
          <b>ISBNs:</b>
          <div id="item_isbns">
            <?=$this->render('geeby-deeby/edit-item/isbn-list.phtml')?>
          </div>
        </td>
        <td>
          <table class="edit">
            <tr><th>New Code</th><td><input type="text" id="product_code" /></td></tr>
            <tr><th>Note:</th><td><input id="product_code_note" class="Note_ID" /></td></tr>
            <tr><th></th><td><button onclick="addProductCode();">Add</button></td></tr>
          </table>
          <b>Product Codes:</b>
          <div id="item_codes">
            <?=$this->render('geeby-deeby/edit-item/product-code-list.phtml')?>
          </div>
        </td>
      </tr>
    </table>
  </div>

  <div id="credits-tab" class="edit_tab_contents">
    <div class="edit_container">
      <table class="edit">
        <tr>
          <th>Position:</th>
          <td><input type="text" id="credit_position" /></td>
        </tr>
        <tr>
          <th>Person:</th>
          <td><input id="credit_person" class="Person_ID" /></td>
        </tr>
        <tr>
          <th>Role:</th>
          <td><?=$this->render('geeby-deeby/edit-person/role-select.phtml')?></td>
        </tr>
        <tr>
          <th>Note:</th>
          <td><input id="credit_note" class="Note_ID" /></td>
        </tr>
        <tr>
          <th></th>
          <td><button onclick="saveCredit();">Add</button></td>
        </tr>
      </table>
    </div>
    <div id="credits">
      <?=$this->render('geeby-deeby/edit-item/credits.phtml')?>
    </div>
  </div>

  <div id="desc-tab" class="edit_tab_contents">
    <div class="edit_container">
      <table class="edit">
        <tr>
          <th>Description Type:</th>
          <td>
            <select id='DescriptionType'>
              <? foreach ($this->descriptionSource()->getList() as $currentVal => $currentDesc): ?>
                <option value="<?=$this->escapeHtml($currentVal)?>"><?=$this->escapeHtml($currentDesc)?></option>
              <? endforeach; ?>
            </select>
          </td>
        </tr>
        <tr>
          <th>Description:</th>
          <td>
            <textarea id='Description'></textarea>
          </td>
        </tr>
        <tr>
          <th></th>
          <td><button onclick="saveDescription();">Add</button></td>
        </tr>
      </table>
    </div>
    <div id="desc_list">
      <?=$this->render('geeby-deeby/edit-item/description-list.phtml')?>
    </div>
  </div>

  <div id="images-tab" class="edit_tab_contents">
    <div class="edit_container">
      <table class="edit">
        <tr>
          <th>Image Path:</th>
          <td><input type="text" id="image_path" /></td>
        </tr>
        <tr>
          <th>Thumb Path:<br /><span class="note">(leave blank to add &quot;thumb&quot; to image filename)</span></th>
          <td><input type="text" id="thumb_path" /></td>
        </tr>
        <tr>
          <th>Position:</th>
          <td><input type="text" id="image_position" /></td>
        </tr>
        <tr>
          <th>Note:</th>
          <td><input id="image_note" class="Note_ID" /></td>
        </tr>
        <tr>
          <th></th>
          <td><button onclick="saveImage();">Add</button></td>
        </tr>
      </table>
    </div>
    <div id="image_list">
      <?=$this->render('geeby-deeby/edit-item/image-list.phtml')?>
    </div>
  </div>

  <div id="platforms-tab" class="edit_tab_contents">
    <?=$this->render('geeby-deeby/edit-platform/select.phtml')?>
    <button onclick="addPlatform();">Add Platform</button>
    <br/>
    <b>Platforms:</b>
    <div id="platform_list">
    <?=$this->render('geeby-deeby/edit-item/platform-list.phtml')?>
    </div>
  </div>

  <div id="release-tab" class="edit_tab_contents">
    <div class="edit_container">
      <table class="edit">
        <tr>
          <th>Month:<br /><span class="note">(1-12, 0 for unknown)</span></th>
          <td><input type="text" id="releaseMonth" /></td>
        </tr>
        <tr>
          <th>Day:<br /><span class="note">(1-31, 0 for unknown)</span></th>
          <td><input type="text" id="releaseDay" /></td>
        </tr>
        <tr>
          <th>Year:<br /><span class="note">(-1 for unreleased)</span></th>
          <td><input type="text" id="releaseYear" /></td>
        </tr>
        <tr>
          <th>Note:</th>
          <td><input id="releaseNote" class="Note_ID" /></td>
        </tr>
        <tr>
          <th></th>
          <td>
            <button onclick="saveReleaseDate();">Add</button>
          </td>
        </tr>
      </table>
    </div>
    <div id="date_list">
      <?=$this->render('geeby-deeby/edit-item/date-list.phtml')?>
    </div>
  </div>

  <div id="translations-tab" class="edit_tab_contents">
    <select id="trans_type">
      <option value='from'>Translated From</option>
      <option value='into'>Translated Into</option>
    </select>
    <input id="trans_name" class="Item_ID" />
    <button onclick="saveTranslation();">Add Translation</button>
    <table>
      <tr>
        <td>
          <b>Translated From:</b>
          <div id="trans_from">
            <?=$this->render('geeby-deeby/edit-item/trans-from-list.phtml')?>
          </div>
        </td>
        <td>
          <b>Translated Into:</b>
          <div id="trans_into">
            <?=$this->render('geeby-deeby/edit-item/trans-into-list.phtml')?>
          </div>
        </td>
      </tr>
    </table>
  </div>

</div>