<?php
$this->layout()->title = 'Edit Item';
$this->layout()->toggleLink = $this->toggleLink('item', $item['Item_ID']);
$this->scriptManager()->add(['base_editor', 'vendor/autocomplete', 'autocomplete', 'edit_items']);
?>
<div class="edit_container" style="width: 800px;">
  <?=$this->render('geeby-deeby/edit-item/index.phtml')?>
</div>
<hr />
<ul class="nav nav-tabs">
  <li class="active"><a href="#editions-tab" data-toggle="tab"><span>Editions</span></a></li>
  <li><a href="#adaptations-tab" data-toggle="tab"><span>Adaptations</span></a></li>
  <li><a href="#alt-titles-tab" data-toggle="tab"><span>Alternate Titles</span></a></li>
  <li><a href="#attached-tab" data-toggle="tab"><span>Attached Items</span></a></li>
  <li><a href="#creators-tab" data-toggle="tab"><span>Creators</span></a></li>
  <li><a href="#credits-tab" data-toggle="tab"><span>Credits</span></a></li>
  <li><a href="#desc-tab" data-toggle="tab"><span>Descriptions</span></a></li>
  <li><a href="#bib-tab" data-toggle="tab"><span>References</span></a></li>
  <li><a href="#relationships-tab" data-toggle="tab">Relationships</a></li>
  <li><a href="#tags-tab" data-toggle="tab"><span>Subjects/Tags</span></a></li>
  <li><a href="#translations-tab" data-toggle="tab"><span>Translations</span></a></li>
</ul>
<div class="tab-content">
  <div id="editions-tab" class="tab-pane active">
    <div id="editions_list">
      <?=$this->render('geeby-deeby/edit-item/edition-list.phtml')?>
    </div>
  </div>

  <div id="adaptations-tab" class="tab-pane">
    <form onsubmit="Item.link('Adaptation'); return false;">
      <label class="sr-only" for="adapt_type">Relationship Direction:</label>
      <select id="adapt_type">
        <option value='From'>Adapted From</option>
        <option value='Into'>Adapted Into</option>
      </select>
      <label class="sr-only" for="adapt_name">Related Item:</label>
      <input id="adapt_name" class="Item_ID" />
      <input type="submit" value="Add Adaptation" />
    </form>
    <table>
      <tr>
        <td>
          <b>Adapted From:</b>
          <div id="adaptationfrom_list">
            <?=$this->render('geeby-deeby/edit-item/adapted-from-list.phtml')?>
          </div>
        </td>
        <td>
          <b>Adapted Into:</b>
          <div id="adaptationinto_list">
            <?=$this->render('geeby-deeby/edit-item/adapted-into-list.phtml')?>
          </div>
        </td>
      </tr>
    </table>
  </div>

  <div id="alt-titles-tab" class="tab-pane">
    <form onsubmit="Item.link('AltTitle'); return false;">
      <label>Title: <input type="text" id="Alt_Title" /></label>
      <label>Note: <input id="Alt_Title_Note" class="Note_ID" /></label>
      <input type="submit" value="Add" />
    </form>
    <div id="alttitle_list">
      <?=$this->render('geeby-deeby/edit-item/alt-title-list.phtml')?>
    </div>
  </div>

  <div id="attached-tab" class="tab-pane">
    <div class="edit_container">
      <form onsubmit="Item.link('Attachment'); return false;">
        <table class="edit">
          <tr>
            <th scope="row"><label for="attachment_name">Title:</label></th>
            <td><input id="attachment_name" class="Item_ID" /></td>
          </tr>
          <tr>
            <th scope="row"><label for="Attachment_Note">Note:</label></th>
            <td><input id="Attachment_Note" class="Note_ID" /></td>
          </tr>
          <tr>
            <td></td>
            <td><input type="submit" value="Add Item" /></td>
          </tr>
        </table>
      </form>
    </div>
    <div id="attachment_list">
      <p class="error">IMPORTANT: In the vast majority of cases, items should be attached at
          the individual EDITION level, not here at the ITEM level.</p>
      <?=$this->render('geeby-deeby/edit-item/list.phtml')?>
    </div>
  </div>

  <div id="bib-tab" class="tab-pane">
    <p>The current item is about the following items, series and people...</p>
    <form onsubmit="Item.link('AboutItem'); return false;">
    <label>Item References:
    <input id="item_bib_id" class="Item_ID" /></label>
    <input type="submit" value="Add Reference" />
    </form>
    <div id="aboutitem_list">
      <?=$this->render('geeby-deeby/edit-item/item-ref-list.phtml')?>
    </div>
    <form onsubmit="Item.link('AboutSeries'); return false;">
      <label>Series References:
      <input id="series_bib_id" class="Series_ID" /></label>
      <input type="submit" value="Add Reference" />
    </form>
    <div id="aboutseries_list">
      <?=$this->render('geeby-deeby/edit-item/series-ref-list.phtml')?>
    </div>
    <form onsubmit="Item.link('AboutPerson'); return false;">
      <label>Person References:
      <input id="person_bib_id" class="Person_ID" /></label>
      <input type="submit" value="Add Reference" />
    </form>
    <div id="aboutperson_list">
      <?=$this->render('geeby-deeby/edit-item/person-ref-list.phtml')?>
    </div>
  </div>

  <div id="creators-tab" class="tab-pane">
    <p class="disclaimer">This section is for listing known, real people who
    contributed to the creation of this item. Use Credits for listing attributed
    authors.
    </p>
    <div class="edit_container">
      <form onsubmit="Item.link('Creator'); return false">
        <table class="edit">
          <tr>
            <th scope="row"><label for="creator_person">Person:</label></th>
            <td><input id="creator_person" class="Person_ID" /></td>
          </tr>
          <tr>
            <th scope="row"><label for="Creator_Role_ID">Role:</label></th>
            <td><?=$this->render('geeby-deeby/edit-person/role-select.phtml', ['idPrefix' => 'Creator_', 'roles' => $this->roles])?></td>
          </tr>
          <tr>
            <td></td>
            <td><input type="submit" value="Add" /></td>
          </tr>
        </table>
      </form>
    </div>
    <div id="creator_list">
      <?=$this->render('geeby-deeby/edit-item/creators.phtml')?>
    </div>
  </div>

  <div id="credits-tab" class="tab-pane">
    <p class="disclaimer">Credits added/removed here will affect ALL editions of this item;
    to affect a single edition, select it from the Editions tab first.</p>
    <div class="edit_container">
      <form onsubmit="Item.link('Credit'); return false;">
        <table class="edit">
          <tr>
            <th scope="row"><label for="credit_position">Position:</label></th>
            <td><input type="text" id="credit_position" /></td>
          </tr>
          <tr>
            <th scope="row"><label for="credit_person">Person:</label></th>
            <td><input id="credit_person" class="Person_ID" /></td>
          </tr>
          <tr>
            <th scope="row"><label for="Role_ID">Role:</label></th>
            <td><?=$this->render('geeby-deeby/edit-person/role-select.phtml')?></td>
          </tr>
          <tr>
            <th scope="row"><label for="credit_note">Note:</label></th>
            <td><input id="credit_note" class="Note_ID" /></td>
          </tr>
          <tr>
            <td></td>
            <td><input type="submit" value="Add" /></td>
          </tr>
        </table>
      </form>
    </div>
    <div id="credit_list">
      <?=$this->render('geeby-deeby/edit-item/credits.phtml')?>
    </div>
  </div>

  <div id="desc-tab" class="tab-pane">
    <div class="edit_container">
      <form onsubmit="Item.link('Description'); return false;">
        <table class="edit">
          <tr>
            <th scope="row"><label for="DescriptionType">Description Type:</label></th>
            <td>
              <select id='DescriptionType'>
                <?php foreach ($this->descriptionSource()->getList() as $currentVal => $currentDesc): ?>
                  <option value="<?=$this->escapeHtml($currentVal)?>"><?=$this->escapeHtml($currentDesc)?></option>
                <?php endforeach; ?>
              </select>
            </td>
          </tr>
          <tr>
            <th scope="row"><label for="Description">Description:</label></th>
            <td>
              <textarea id='Description'></textarea>
            </td>
          </tr>
          <tr>
            <td></td>
            <td><input type="submit" value="Add" /></td>
          </tr>
        </table>
      </form>
    </div>
    <div id="description_list">
      <?=$this->render('geeby-deeby/edit-item/description-list.phtml')?>
    </div>
  </div>

  <div id="relationships-tab" class="tab-pane">
    <form onsubmit="Item.link('Relationship'); return false;">
      <label class="sr-only" for="relationship_type">Relationship Type:</label>
      <select id="relationship_type">
        <?php foreach ($this->relationships as $value => $label): ?>
          <option value="/<?=$this->escapeHtmlAttr($value)?>"><?=$this->escapeHtml($label)?></option>
        <?php endforeach; ?>
      </select>
      <label class="sr-only" for="target_item">Target Item:</label>
      <input type="text" id="target_item" />
      <input type="submit" value="Add Relationship" />
    </form>
    <hr/>
    <div id="relationship_list">
      <?=$this->render('geeby-deeby/edit-item/relationship-list.phtml')?>
    </div>
  </div>

  <div id="tags-tab" class="tab-pane">
    <div class="edit_container">
      <form onsubmit="Item.link('Tag'); return false;">
        <table class="edit">
          <tr>
            <th scope="row"><label for="Tag_ID">Subject/Tag:</label></th>
            <td><input id="Tag_ID" class="Tag_ID" /></td>
          </tr>
          <tr>
            <td></td>
            <td><input type="submit" value="Add" /></td>
          </tr>
        </table>
      </form>
    </div>
    <div id="tag_list">
      <?=$this->render('geeby-deeby/edit-item/tag-list.phtml')?>
    </div>
  </div>

  <div id="translations-tab" class="tab-pane">
    <form onsubmit="Item.link('Translation'); return false;">
      <label class="sr-only" for="trans_type">Translation Direction:</label>
      <select id="trans_type">
        <option value='from'>Translated From</option>
        <option value='into'>Translated Into</option>
      </select>
      <label class="sr-only" for="trans_name">Translation Target:</label>
      <input type="text" id="trans_name" class="Item_ID" />
      <input type="submit" value="Add Translation" />
    </form>
    <table>
      <tr>
        <td>
          <b>Translated From:</b>
          <div id="translationfrom_list">
            <?=$this->render('geeby-deeby/edit-item/trans-from-list.phtml')?>
          </div>
        </td>
        <td>
          <b>Translated Into:</b>
          <div id="translationinto_list">
            <?=$this->render('geeby-deeby/edit-item/trans-into-list.phtml')?>
          </div>
        </td>
      </tr>
    </table>
  </div>
</div>