<?php if (!isset($editions) || count($editions) == 0): ?>
  No editions.
<?php else: ?>
  <table class="list_item">
    <tr><th scope="col">Display Order within Item</th><th scope="col"><button onclick="return Item.copyEdition();">Copy Selected Edition</button></th><th scope="col">Title</th><th scope="col">Details</th></tr>
    <?php foreach ($editions as $current): ?>
      <tr>
        <td>
          <form onsubmit="Item.reorderLink('Editions', { 'edition_id': <?=$current['Edition_ID']?> }); return false;">
            <label><span class="sr-only">Order: </span><input class="number" type="text" value="<?=isset($current['Item_Display_Order']) ? $this->escapeHtml($current['Item_Display_Order']) : 0 ?>" id="order<?=$current['Edition_ID']?>" /></label>
            <input type="submit" value="Set" />
          </form>
        </td>
        <td align="center">
          <input type="radio" class="selectedEdition" name="selectedEdition" value="<?=$current['Edition_ID']?>" />
        </td>
        <td>
          <a href="<?=$this->url('edit/edition', ['id' => $current['Edition_ID']])?>"><?=$this->escapeHtml($current['Edition_Name'])?></a>
        </td>
        <td>
          <?php $parts = array_filter([$current['Earliest_Year'], $current['Extent_In_Parent']]); ?>
          <?=$this->escapeHtml(implode(', ', $parts))?>
        </td>
      </tr>
    <?php endforeach; ?>
  </table>
<?php endif; ?>
