<div id="editItemForm" class="form-horizontal" role="form">
  <input type="hidden" id="Item_ID" value="<?=$item['Item_ID']?>" />
  <div class="form-group">
    <label class="col-sm-2 control-label">Material Type:</label>
    <div class="col-sm-10">
      <?=$this->render('geeby-deeby/edit-material-type/select.phtml', ['materials' => $materials, 'selected' => $item['Material_Type_ID'] ?? null])?>
    </div>
  </div>
  <div class="form-group">
    <label for="Item_Name" class="col-sm-2 control-label">Item Name:</label>
    <div class="col-sm-10">
      <input class="form-control" type="text" id="Item_Name" value="<?=isset($item['Item_Name']) ? $this->escapeHtml($item['Item_Name']) : ''?>" />
    </div>
  </div>
  <?php if (!isset($item['Item_ID']) || !is_numeric($item['Item_ID'])): ?>
    <div class="form-group">
      <label for="Item_Length" class="col-sm-2 control-label">Length:</label>
      <div class="col-sm-10">
        <input class="form-control" type="text" id="Item_Length" value="<?=isset($item['Item_Length']) ? $this->escapeHtml($item['Item_Length']) : ''?>" />
      </div>
    </div>
    <div class="form-group" style="display: none;">
      <label for="Item_Endings" class="col-sm-2 control-label">Endings:</label>
      <div class="col-sm-10">
        <input class="form-control" type="text" id="Item_Endings" value="<?=isset($item['Item_Endings']) ? $this->escapeHtml($item['Item_Endings']) : ''?>" />
      </div>
    </div>
  <?php endif; ?>
  <div class="form-group">
    <label for="Item_Errata" class="col-sm-2 control-label">Errata:</label>
    <div class="col-sm-10">
      <textarea class="form-control" rows="3" id="Item_Errata"><?=isset($item['Item_Errata']) ? $this->escapeHtml($item['Item_Errata']) : ''?></textarea>
    </div>
  </div>
  <div class="form-group">
    <label for="Item_Thanks" class="col-sm-2 control-label">Thanks:</label>
    <div class="col-sm-10">
      <input class="form-control" type="text" id="Item_Thanks" value="<?=isset($item['Item_Thanks']) ? $this->escapeHtml($item['Item_Thanks']) : ''?>" />
    </div>
  </div>
  <?php if (count($attributes) > 0): ?>
    <div class="collapse" id="extraAttributes">
      <?php foreach ($attributes as $attribute): $attrId = $attribute['Items_Attribute_ID']; ?>
        <div class="form-group">
          <label for="Item_Attribute_<?=$attrId?>" class="col-sm-2 control-label"><?=$this->escapeHtml($attribute['Items_Attribute_Name'])?>:</label>
          <div class="col-sm-10">
            <?php if ($attribute['Allow_HTML'] != 1): ?>
              <input class="form-control item-attribute" type="text" id="Item_Attribute_<?=$attrId?>" value="<?=isset($attributeValues[$attrId]) ? $this->escapeHtml($attributeValues[$attrId]) : ''?>" />
            <?php else: ?>
              <textarea class="form-control item-attribute" style="width:100%" rows="6" id="Item_Attribute_<?=$attrId?>"><?=isset($attributeValues[$attrId]) ? $this->escapeHtml($attributeValues[$attrId]) : ''?></textarea>
            <?php endif; ?>
          </div>
        </div>
      <?php endforeach; ?>
    </div>
  <?php endif; ?>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <?php if (count($attributes) > 0): ?>
        <button data-toggle="collapse" data-target="#extraAttributes">Toggle Additional Attributes</button>
      <?php endif; ?>
      <button id="save_item" onclick="Item.save();">Save</button>
    </div>
  </div>
  <div id="save_item_status"></div>
</div>
