<?php if (isset($itemsBib) && count($itemsBib) > 0): ?>
  <?php foreach ($itemsBib as $current): ?>
    <table class="list_item">
      <tr>
        <td>
          <a href="<?=$this->url('edit/item', ['id' => $current['Item_ID']])?>#bib-tab">
            <?=$this->escapeHtml($current['Item_Name'])?>
          </a>
        </td>
        <td>
          <?=
            $this->iconButton(
                'trash',
                "Item.unlink('AboutItem', " . $current['Item_ID'] . ")",
                'Unlink reference to item: ' . $current['Item_Name']
            )
      ?>
        </td>
      </tr>
    </table>
  <?php endforeach; ?>
<?php else: ?>
  No relevant items.
<?php endif; ?>