<?php if (isset($itemsBib) && count($itemsBib) > 0): ?>
  <?php foreach ($itemsBib as $current): ?>
    <table class="list_item">
      <tr>
        <td>
          <a href="<?=$this->url('edit/item', ['id' => $current['Item_ID']])?>#bib-tab">
            <?=$this->escapeHtml($current['Item_Name'])?>
          </a>
        </td>
        <td>
          <a class="ui-icon ui-icon-trash" href="#" onclick="Item.unlink('AboutItem', <?=$current['Item_ID']?>); return false;">
          </a>
        </td>
      </tr>
    </table>
  <?php endforeach; ?>
<?php else: ?>
  No relevant items.
<?php endif; ?>