<?php if (!isset($item_list) || count($item_list) < 1): ?>
  No items.
<?php else: ?>
  <table class="list_item">
    <tr><th scope="col">Order</th><th colspan="2" scope="col">Title / Material Type</th></tr>
    <?php foreach ($item_list as $current): ?>
      <tr>
        <td>
          <form onsubmit="Item.reorderLink('Attachment', { 'item_id': <?=$current['Item_ID']?> }); return false;">
            <label><span class="sr-only">Order: </span><input class="number" type="text" value="<?=$this->escapeHtml($current['Position'])?>" id="attachment_order_<?=$current['Item_ID']?>" /></label>
            <input type="submit" value="Set" />
          </form>
        </td>
        <td>
          <?=
            $this->iconButton(
                'trash',
                "Item.unlink('Attachment', " . $current['Item_ID'] . ")",
                'Unlink attached item: ' . $current['Item_Name']
            )
          ?>
        </td>
        <td>
          <a href="<?=$this->url('edit/item', ['id' => $current['Item_ID']])?>">
            <?=$this->escapeHtml($current['Item_Name'])?>
          </a>
          (<?=$this->escapeHtml($current['Material_Type_Name'])?><?php if (!empty($current['Note'])): ?>, <?=$this->escapeHtml($current['Note'])?><?php endif; ?>)
        </td>
      </tr>
    <?php endforeach; ?>
  </table>
<?php endif; ?>
