<?php if (!isset($item_list) || count($item_list) < 1): ?>
  No items.
<?php else: ?>
  <table class="list_item">
    <tr><th>Order</th><th colspan="2">Title / Material Type</th></tr>
    <?php foreach ($item_list as $current): ?>
      <tr>
        <td>
          <input class="number" type="text" value="<?=$this->escapeHtml($current['Position'])?>" id="attachment_order_<?=$current['Item_ID']?>" />
          <button onclick="Item.reorderLink('Attachment', { 'item_id': <?=$current['Item_ID']?> });">Set</button>
        </td>
        <td>
          <a class="ui-icon ui-icon-trash" href="#" onclick="Item.unlink('Attachment', <?=$current['Item_ID']?>); return false;">
          </a>
        </td>
        <td>
          <a href="<?=$this->url('edit/item', ['id' => $current['Item_ID']])?>">
            <?=$this->escapeHtml($current['Item_Name'])?>
          </a>
          (<?=$this->escapeHtml($current['Material_Type_Name'])?><?php if (!empty($current['Note'])): ?>, <?=$this->escapeHtml($current['Note'])?><?php endif; ?>)
        </td>
      </tr>
    <?php endforeach; ?>
  </table>
<?php endif; ?>
