<?php if (isset($peopleBib) && count($peopleBib) > 0): ?>
  <?php foreach ($peopleBib as $current): ?>
    <table class="list_item">
      <tr>
        <td>
          <a href="<?=$this->url('edit/person', ['id' => $current['Person_ID']])?>#bib-tab">
            <?=$this->escapeHtml($this->showperson($current))?>
          </a>
        </td>
        <td>
          <a class="ui-icon ui-icon-trash" href="#" onclick="Item.unlink('AboutPerson', <?=$current['Person_ID']?>); return false;">
          </a>
        </td>
      </tr>
    </table>
  <?php endforeach; ?>
<?php else: ?>
  No relevant people.
<?php endif; ?>