<? if (isset($peopleBib) && count($peopleBib) > 0): ?>
  <? foreach ($peopleBib as $current): ?>
    <table class="list_item">
      <tr>
        <td>
          <a href="<?=$this->url('edit/person', array('id' => $current['Person_ID']))?>#bib-tab">
            <?=$this->escapeHtml($this->showperson($current))?>
          </a>
        </td>
        <td>
          <a class="ui-icon ui-icon-trash" href="#" onclick="Item.unlink('AboutPerson', <?=$current['Person_ID']?>); return false;">
          </a>
        </td>
      </tr>
    </table>
  <? endforeach; ?>
<? else: ?>
  No relevant people.
<? endif; ?>