<?php if (empty($this->relationshipsValues)): ?>
  <p>No relationships defined.</p>
<?php else: ?>
    <?php foreach ($this->relationshipsValues as $current): ?>
      <h3><?=$this->escapeHtml($current['label'])?>:</h3>
      <table class="list_item">
        <?php foreach ($current['values'] as $value): ?>
          <tr>
            <td>
              <a href="<?=$this->url('edit/item', ['id' => $value['Item_ID']])?>">
                <?=$this->escapeHtml($value['Item_Name'])?>
              </a>
            </td><td>
              <?=
                $this->iconButton(
                    'trash',
                    "Item.unlink('Relationship', " . $value['Item_ID'] . ", '/" . $current['relationship_id'] . "')",
                    'Delete relationship -- ' . $current['label'] . ': ' . $value['Item_Name']
                )
              ?>
            </td>
          </tr>
        <?php endforeach; ?>
      </table>
    <?php endforeach; ?>
  </table>
<?php endif; ?>
