<?php if (count($items) < 1): ?>
  <p>No items listed in this database yet.</p>
<?php else: ?>
  <h2>
    <?=$this->firstLetterMenu($items, 'Item_Name'); ?>
  </h2>
  <?php $currentLetter = false; foreach ($tags as $i => $current): ?>
    <?php $first = $this->firstletter($current['Item_Name']); ?>
    <?php if ($currentLetter !== $first): $currentLetter = $first; ?>
      <?php if ($i > 0): ?>
        <a name="<?=$this->escapeHtml($currentLetter)?>"/>
        <h2><?=$this->escapeHtml($currentLetter)?><a href="#" style="float:right">Back to Top &uarr;</a></h2>
      <?php endif; ?>
    <?php endif; ?>
    <a href="<?=$this->url('edit/item', ['id' => $current['Item_ID']])?>"><?=$this->escapeHtml($current['Item_Name'])?></a><br />
  <?php endforeach; ?>
<?php endif; ?>