<?php if (isset($seriesBib) && count($seriesBib) > 0): ?>
  <?php foreach ($seriesBib as $current): ?>
    <table class="list_item">
      <tr>
        <td>
          <a href="<?=$this->url('edit/series', ['id' => $current['Series_ID']])?>#bib-tab">
            <?=$this->escapeHtml($current['Series_Name'])?>
          </a>
        </td>
        <td>
          <a class="ui-icon ui-icon-trash" href="#" onclick="Item.unlink('AboutSeries', <?=$current['Series_ID']?>); return false;">
          </a>
        </td>
      </tr>
    </table>
  <?php endforeach; ?>
<?php else: ?>
  No relevant series.
<?php endif; ?>