<?php if (isset($seriesBib) && count($seriesBib) > 0): ?>
  <?php foreach ($seriesBib as $current): ?>
    <table class="list_item">
      <tr>
        <td>
          <a href="<?=$this->url('edit/series', ['id' => $current['Series_ID']])?>#bib-tab">
            <?=$this->escapeHtml($current['Series_Name'])?>
          </a>
        </td>
        <td>
          <?=$this->iconButton(
    'trash',
    "Item.unlink('AboutSeries', " . $current['Series_ID'] . ")",
    'Unlink reference to series: ' . $current['Series_Name']
)?>
        </td>
      </tr>
    </table>
  <?php endforeach; ?>
<?php else: ?>
  No relevant series.
<?php endif; ?>