<?php if (isset($tags) && count($tags) > 0): ?>
  <?php foreach ($tags as $current): ?>
  <table class="list_item">
    <tr>
      <td>
        <a href="<?=$this->url('edit/tag', ['id' => $current['Tag_ID']])?>"><?=$this->escapeHtml($current['Tag'])?></a>
      </td>
      <td>
        <?=
          $this->iconButton(
              'trash',
              "Item.unlink('Tag', " . $current['Tag_ID'] . ")",
              'Unlink tag: ' . $current['Tag']
          )
        ?>
      </td>
    </tr>
  </table>
  <?php endforeach; ?>
<?php else: ?>
  No tags set.
<?php endif; ?>
