<?php if (isset($tags) && count($tags) > 0): ?>
  <?php foreach ($tags as $current): ?>
  <table class="list_item">
    <tr>
      <td>
        <?=$this->escapeHtml($current['Tag'])?>
      </td>
      <td>
        <a class="ui-icon ui-icon-trash" href="#" onclick="Item.unlink('Tag', <?=$this->escapeHtml($current['Tag_ID'])?>); return false;">
        </a>
      </td>
    </tr>
  </table>
  <?php endforeach; ?>
<?php else: ?>
  No tags set.
<?php endif; ?>
