<?php if (isset($translatedFrom) && count($translatedFrom) > 0): ?>
  <?php foreach ($translatedFrom as $current): ?>
    <table class="list_item">
      <tr>
        <td>
          <a href="<?=$this->url('edit/item', ['id' => $current['Item_ID']])?>#translations-tab">
            <?=$this->escapeHtml($current['Item_Name'])?>
          </a>
        </td>
        <td>
          <?=
            $this->iconButton(
                'trash',
                "Item.unlink('Translation', " . $current['Item_ID'] . ", 'From')",
                'Unlink translation from: ' . $current['Item_Name']
            )
          ?>
        </td>
      </tr>
    </table>
  <?php endforeach; ?>
<?php else: ?>
  No relevant items.
<?php endif; ?>
