<?php if (isset($translatedInto) && count($translatedInto) > 0): ?>
  <?php foreach ($translatedInto as $current): ?>
    <table class="list_item">
      <tr>
        <td>
          <a href="<?=$this->url('edit/item', ['id' => $current['Item_ID']])?>#translations-tab">
            <?=$this->escapeHtml($current['Item_Name'])?>
          </a>
        </td>
        <td>
          <?=$this->iconButton(
            'trash',
            "Item.unlink('Translation', " . $current['Item_ID'] . ", 'Into')",
            'Unlink translation into: ' . $current['Item_Name']
          )?>
        </td>
      </tr>
    </table>
  <?php endforeach; ?>
<?php else: ?>
  No relevant items.
<?php endif; ?>
