<? if (isset($translatedInto) && count($translatedInto) > 0): ?>
  <? foreach ($translatedInto as $current): ?>
    <table class="list_item">
      <tr>
        <td>
          <a href="<?=$this->url('edit/item', array('id' => $current['Item_ID']))?>#translations-tab">
            <?=$this->escapeHtml($current['Item_Name'])?>
          </a>
        </td>
        <td>
          <a class="ui-icon ui-icon-trash" href="#" onclick="deleteTranslation(<?=$current['Item_ID']?>); return false;">
          </a>
        </td>
      </tr>
    </table>
  <? endforeach; ?>
<? else: ?>
  No relevant items.
<? endif; ?>
