<?
    $this->layout()->title = 'Publisher List';
?>
<? if (count($publishers) < 1): ?>
  <p>No publishers listed in this database yet.</p>
<? else: ?>
  <h2>
    <?=$this->firstLetterMenu($publishers, 'Publisher_Name'); ?>
  </h2>
  <? $currentLetter = false; foreach ($publishers as $i=>$current): ?>
    <? $first = $this->firstletter($current['Publisher_Name']); ?>
    <? if ($currentLetter !== $first): $currentLetter = $first; ?>
      <? if ($i > 0): ?>
        <a name="<?=$this->escapeHtml($currentLetter)?>"/>
        <h2><?=$this->escapeHtml($currentLetter)?><a href="#" style="float:right">Back to Top &uarr;</a></h2>
      <? endif; ?>
    <? endif; ?>
    <a href="<?=$this->url('publisher', array('id' => $current['Publisher_ID']))?>">
      <?=$this->escapeHtml($this->fixtitle($current['Publisher_Name']))?>
    </a><br />
  <? endforeach; ?>
<? endif; ?>