<?php
$title = $publisher['Publisher_Name'];
$this->layout()->title = 'Publisher - ' . $title;
$this->layout()->toggleLink = $this->toggleLink('edit/publisher', $publisher['Publisher_ID']);
$displayedSomething = false;
?>
<?php $uriCount = count($uris);
if ($uriCount > 0): $displayedSomething = true; ?>
  <p><b>External Identifier<?php if ($uriCount > 1): ?>s<?php endif; ?>:</b>
    <?php $i = 0;
    foreach ($uris as $uri): $i++ ?>
      <a href="<?=$this->escapeHtmlAttr($uri['URI'])?>"><?=$this->escapeHtml($uri['URI'])?></a><?=$i < $uriCount ? ', ' : ''?>
    <?php endforeach; ?>
  </p>
<?php endif; ?>
<?php if (!$displayedSomething && count($series) < 1): ?>
  <p>No information is available about this publisher.</p>
<?php else: ?>
  <?php $currentLetter = false;
    foreach ($series as $current): ?>
    <?php $first = $this->firstletter($current['Series_Name']);
        if ($currentLetter !== $first): $currentLetter = $first; ?>
      <h2><?=$this->escapeHtml($currentLetter)?></h2>
    <?php endif; ?>
    <a href="<?=$this->url('series', ['id' => $current['Series_ID']])?>">
      <?=$this->escapeHtml($this->fixtitle($current['Series_Name']))?>
    </a><br />
  <?php endforeach; ?>
<?php endif; ?>