<?php if (isset($series_alt_titles) && count($series_alt_titles) > 0): ?>
  <?php foreach ($series_alt_titles as $current): ?>
    <table class="list_item">
      <tr>
        <td>
          <?=$this->escapeHtml($current['Series_AltName'])?><?=(strlen($current['Note']) > 0) ? ' (' . $this->escapeHtml($current['Note']) . ')' : ''?>
        </td>
        <td>
          <?=
            $this->iconButton(
                'trash',
                "Series.unlink('AltTitle', " . $current['Sequence_ID'] . ')',
                'Delete alternate title: ' . $current['Series_AltName']
            )
      ?>
        </td>
      </tr>
    </table>
  <?php endforeach; ?>
<?php else: ?>
  No alternate titles set.
<?php endif; ?>
