<? $this->layout()->title = 'Edit Series' ?>
<? $this->scriptManager()->add(['autocomplete', 'base_editor', 'edit_items', 'edit_series']) ?>
<div class="edit_container" style="width: 800px;">
  <?=$this->render('geeby-deeby/edit-series/index.phtml')?>
</div>
<hr />
<ul class="nav nav-tabs">
  <li class="active"><a href="#items-tab" data-toggle="tab">Attached Items</a></li>
  <li><a href="#alt-titles-tab" data-toggle="tab">Alternate Titles</a></li>
  <li><a href="#categories-tab" data-toggle="tab">Categories</a></li>
  <li><a href="#material-tab" data-toggle="tab">Material Types</a></li>
  <li><a href="#publishers-tab" data-toggle="tab">Publishers</a></li>
  <li><a href="#relationships-tab" data-toggle="tab">Relationships</a></li>
  <li><a href="#translations-tab" data-toggle="tab">Translations</a></li>
</ul>

<div class="tab-content">
  <div id="items-tab" class="tab-pane active">
    <input id="item_name" />
    <button onclick="Series.link('Item');">Add Existing Item</button>
    <button onclick="Item.edit('NEW');">Add New Item</button>
    <div id="item_list">
      <?=$this->render('geeby-deeby/edit-series/item-list.phtml')?>
    </div>
  </div>

  <div id="material-tab" class="tab-pane">
    <?=$this->render('geeby-deeby/edit-material-type/select.phtml', array('materials' => $materials, 'idPrefix'=>'Series_'))?>
    <button onclick="Series.link('Material');">Add</button>
    <div id="material_list">
      <?=$this->render('geeby-deeby/edit-series/material-type-list.phtml')?>
    </div>
  </div>

  <div id="publishers-tab" class="tab-pane">
    <div class="edit_container">
      <table class="edit">
        <tr>
          <th>Publisher:</th>
          <td><input id="Publisher_ID" /></td>
        </tr>
        <tr>
          <th>Note:</th>
          <td><input id="Publisher_Note_ID" class="Note_ID" /></td>
        </tr>
        <tr>
          <td></td>
          <td><button onclick="Series.link('Publisher');">Add</button></td>
        </tr>
      </table>
    </div>
    <div id="publisher_list">
      <?=$this->render('geeby-deeby/edit-series/publisher-list.phtml')?>
    </div>
  </div>

  <div id="alt-titles-tab" class="tab-pane">
    <b>Title:</b> <input type="text" id="Alt_Title" />
    <b>Note: </b> <input id="Alt_Title_Note" class="Note_ID" />
    <button onclick="Series.link('AltTitle');">Add</button>
    <div id="alttitle_list">
      <?=$this->render('geeby-deeby/edit-series/alt-title-list.phtml')?>
    </div>
  </div>

  <div id="categories-tab" class="tab-pane">
    <? if (!empty($categories)): ?>
      <? $selected_categories = $seriesObj->getCategoryIDs(); ?>
      <? foreach ($categories as $current): ?>
        <input type="checkbox" id="Category_ID_<?=$current['Category_ID']?>" class="Category_ID" value="<?=$current['Category_ID']?>"<?=in_array($current['Category_ID'], $selected_categories) ? ' checked="checked"' : '' ?> />
        <label for="Category_ID_<?=$current['Category_ID']?>"><?=$this->escapeHtml($current['Category'])?></label><br />
      <? endforeach; ?>
      <button id="save_categories" onclick="Series.saveCategories();">Save</button>
      <div id="save_categories_status"></div>
    <? else: ?>
      No categories defined.
    <? endif; ?>
  </div>

  <div id="relationships-tab" class="tab-pane">
    <div>
      <select id="relationship_type">
        <? foreach ($this->relationships as $value => $label): ?>
          <option value="/<?=$this->escapeHtmlAttr($value)?>"><?=$this->escapeHtml($label)?></option>
        <? endforeach; ?>
      </select>
      <input id="target_series" />
      <button onclick="Series.link('Relationship');">Add Relationship</button>
    </div>
    <hr/>
    <div id="relationship_list">
      <?=$this->render('geeby-deeby/edit-series/relationship-list.phtml')?>
    </div>
  </div>

  <div id="translations-tab" class="tab-pane">
    <select id="trans_type">
      <option value='from'>Translated From</option>
      <option value='into'>Translated Into</option>
    </select>
    <input id="trans_name" />
    <button onclick="Series.link('Translation');">Add Translation</button>
    <table>
      <tr>
        <td>
          <b>Translated From:</b>
          <div id="translationfrom_list">
            <?=$this->render('geeby-deeby/edit-series/trans-from-list.phtml')?>
          </div>
        </td>
        <td>
          <b>Translated Into:</b>
          <div id="translationinto_list">
            <?=$this->render('geeby-deeby/edit-series/trans-into-list.phtml')?>
          </div>
        </td>
      </tr>
    </table>
  </div>
</div>