<?php
$this->layout()->title = 'Edit Series';
$this->layout()->toggleLink = $this->toggleLink('series', $series['Series_ID']);
$this->scriptManager()->add(['base_editor', 'vendor/autocomplete', 'autocomplete', 'edit_items', 'edit_series']);
?>
<div class="edit_container" style="width: 800px;">
  <?=$this->render('geeby-deeby/edit-series/index.phtml')?>
</div>
<hr />
<ul class="nav nav-tabs">
  <li class="active"><a href="#items-tab" data-toggle="tab">Attached Items</a></li>
  <li><a href="#alt-titles-tab" data-toggle="tab">Alternate Titles</a></li>
  <li><a href="#categories-tab" data-toggle="tab">Categories</a></li>
  <li><a href="#material-tab" data-toggle="tab">Material Types</a></li>
  <li><a href="#publishers-tab" data-toggle="tab">Publishers</a></li>
  <li><a href="#relationships-tab" data-toggle="tab">Relationships</a></li>
  <li><a href="#translations-tab" data-toggle="tab">Translations</a></li>
</ul>

<div class="tab-content">
  <div id="items-tab" class="tab-pane active">
    <form style="float: left;" onsubmit="Series.link('Item'); return false;">
      <label>Item: <input type="text" id="item_name" /></label>
      <input type="submit" value="Add Existing Item" />
    </form>
    <button style="margin-left: 5px; float: left;" onclick="Item.edit('NEW');">Add New Item</button>
    <div style="clear: left;" id="item_list">
      <?=$this->render('geeby-deeby/edit-series/item-list.phtml')?>
    </div>
  </div>

  <div id="material-tab" class="tab-pane">
    <form onsubmit="Series.link('Material'); return false;">
      <label>Material Type:
      <?=$this->render('geeby-deeby/edit-material-type/select.phtml', ['materials' => $materials, 'idPrefix' => 'Series_'])?></label>
      <input type="submit" value="Add" />
    </form>
    <div id="material_list">
      <?=$this->render('geeby-deeby/edit-series/material-type-list.phtml')?>
    </div>
  </div>

  <div id="publishers-tab" class="tab-pane">
    <form class="edit_container" onsubmit="Series.link('Publisher'); return false;">
      <table class="edit">
        <tr>
          <th scope="row"><label for="Publisher_ID">Publisher:</label></th>
          <td><input id="Publisher_ID" /></td>
        </tr>
        <tr>
          <th scope="row"><label for="Publisher_Note_ID">Note:</label></th>
          <td><input id="Publisher_Note_ID" class="Note_ID" /></td>
        </tr>
        <tr>
          <td></td>
          <td><input type="submit" value="Add" /></td>
        </tr>
      </table>
    </form>
    <div id="publisher_list">
      <?=$this->render('geeby-deeby/edit-series/publisher-list.phtml')?>
    </div>
  </div>

  <div id="alt-titles-tab" class="tab-pane">
    <form onsubmit="Series.link('AltTitle'); return false;">
      <label>Title: <input type="text" id="Alt_Title" /></label>
      <label>Note: <input id="Alt_Title_Note" class="Note_ID" /></label>
      <input type="submit" value="Add" />
    </form>
    <div id="alttitle_list">
      <?=$this->render('geeby-deeby/edit-series/alt-title-list.phtml')?>
    </div>
  </div>

  <div id="categories-tab" class="tab-pane">
    <?php if (!empty($categories)): ?>
      <?php $selected_categories = $seriesObj->getCategoryIDs(); ?>
      <form onsubmit="Series.saveCategories(); return false;">
        <?php foreach ($categories as $current): ?>
          <input type="checkbox" id="Category_ID_<?=$current['Category_ID']?>" class="Category_ID" value="<?=$current['Category_ID']?>"<?=in_array($current['Category_ID'], $selected_categories) ? ' checked="checked"' : '' ?> />
          <label for="Category_ID_<?=$current['Category_ID']?>"><?=$this->escapeHtml($current['Category'])?></label><br />
        <?php endforeach; ?>
        <input type="submit" value="Save" />
      </form>
      <div id="save_categories_status"></div>
    <?php else: ?>
      No categories defined.
    <?php endif; ?>
  </div>

  <div id="relationships-tab" class="tab-pane">
    <form onsubmit="Series.link('Relationship'); return false;">
      <label class="sr-only" for="relationship_type">Relationship Type:</label>
      <select id="relationship_type">
        <?php foreach ($this->relationships as $value => $label): ?>
          <option value="/<?=$this->escapeHtmlAttr($value)?>"><?=$this->escapeHtml($label)?></option>
        <?php endforeach; ?>
      </select>
      <label class="sr-only" for="target_series">Target Series:</label>
      <input type="text" id="target_series" />
      <input type="submit" value="Add Relationship" />
    </form>
    <hr/>
    <div id="relationship_list">
      <?=$this->render('geeby-deeby/edit-series/relationship-list.phtml')?>
    </div>
  </div>

  <div id="translations-tab" class="tab-pane">
    <form onsubmit="Series.link('Translation'); return false;">
      <label class="sr-only" for="trans_type">Translation Direction:</label>
      <select id="trans_type">
        <option value='from'>Translated From</option>
        <option value='into'>Translated Into</option>
      </select>
      <label class="sr-only" for="trans_name">Translation Target:</label>
      <input type="text" id="trans_name" />
      <input type="submit" value="Add Translation" />
    </form>
    <table>
      <tr>
        <td>
          <b>Translated From:</b>
          <div id="translationfrom_list">
            <?=$this->render('geeby-deeby/edit-series/trans-from-list.phtml')?>
          </div>
        </td>
        <td>
          <b>Translated Into:</b>
          <div id="translationinto_list">
            <?=$this->render('geeby-deeby/edit-series/trans-into-list.phtml')?>
          </div>
        </td>
      </tr>
    </table>
  </div>
</div>