<div id="editForm" style="width:100%">
  <input type="hidden" id="Series_ID" value="<?=$series['Series_ID']?>" />
  <table class="edit" style="width:100%">
    <tr>
      <th width="20%">Series Name:</th>
      <td><input type="text" id="Series_Name" value="<?=isset($series['Series_Name']) ? $this->escapeHtml($series['Series_Name']) : ''?>" /></td>
    </tr>
    <tr>
      <th>Description:</th>
      <td><textarea style="width:100%" rows="6" id="Series_Description"><?=isset($series['Series_Description']) ? $this->escapeHtml($series['Series_Description']) : ''?></textarea></td>
    </tr>
    <tr>
      <th>Language:</th>
      <td><?=$this->render('geeby-deeby/edit-language/select.phtml', array('languages' => $languages, 'selected' => isset($series['Language_ID']) ? $series['Language_ID'] : null))?></td>
    </tr>
  </table>
  <button id="save_series" onclick="saveSeries();">Save</button>
  <div id="save_series_status"></div>
</div>
