<div id="editForm" class="form-horizontal" role="form">
  <input type="hidden" id="Series_ID" value="<?=$series['Series_ID']?>" />
  <div class="form-group">
    <label for="Series_Name" class="col-sm-2 control-label">Series Name:</label>
    <div class="col-sm-10">
      <input class="form-control" type="text" id="Series_Name" value="<?=isset($series['Series_Name']) ? $this->escapeHtml($series['Series_Name']) : ''?>" />
    </div>
  </div>
  <div class="form-group">
    <label for="Series_Description" class="col-sm-2 control-label">Description:</label>
    <div class="col-sm-10">
      <textarea class="form-control" style="width:100%" rows="6" id="Series_Description"><?=isset($series['Series_Description']) ? $this->escapeHtml($series['Series_Description']) : ''?></textarea>
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-2 control-label">Language:</label>
    <div class="col-sm-10">
      <?=$this->render('geeby-deeby/edit-language/select.phtml', ['languages' => $languages, 'selected' => $series['Language_ID'] ?? null])?>
    </div>
  </div>
  <?php if (count($attributes) > 0): ?>
    <div class="collapse" id="extraAttributes">
      <?php foreach ($attributes as $attribute): $attrId = $attribute['Series_Attribute_ID']; ?>
        <div class="form-group">
          <label for="Series_Attribute_<?=$attrId?>" class="col-sm-2 control-label"><?=$this->escapeHtml($attribute['Series_Attribute_Name'])?>:</label>
          <div class="col-sm-10">
            <?php if ($attribute['Allow_HTML'] != 1): ?>
              <input class="form-control series-attribute" type="text" id="Series_Attribute_<?=$attrId?>" value="<?=isset($attributeValues[$attrId]) ? $this->escapeHtml($attributeValues[$attrId]) : ''?>" />
            <?php else: ?>
              <textarea class="form-control series-attribute" style="width:100%" rows="6" id="Series_Attribute_<?=$attrId?>"><?=isset($attributeValues[$attrId]) ? $this->escapeHtml($attributeValues[$attrId]) : ''?></textarea>
            <?php endif; ?>
          </div>
        </div>
      <?php endforeach; ?>
    </div>
  <?php endif; ?>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <?php if (count($attributes) > 0): ?>
        <button data-toggle="collapse" data-target="#extraAttributes">Toggle Additional Attributes</button>
      <?php endif; ?>
      <button id="save_series" onclick="Series.save();">Save</button>
    </div>
  </div>
  <div id="save_series_status"></div>
</div>
