<?php if (!isset($item_list) || count($item_list) == 0): ?>
  No items.
<?php else: ?>
  <table class="list_item">
    <tr><th scope="col">Order</th><th colspan="2" scope="col">Title / Material Type</th></tr>
    <?php foreach ($item_list as $current): ?>
      <?php $currentTitle = !empty($current['Item_AltName']) ? $current['Item_AltName'] : $current['Item_Name']; ?>
      <tr>
        <td>
          <form onsubmit="Series.reorderLink('Item', { 'edition_id': <?=$current['Edition_ID']?> }); return false;">
            <label><span class="sr-only">Order: </span><input class="number" type="text" value="<?=($current['Volume'] > 0 ? $this->escapeHtml($current['Volume'] . ',') : '') . $this->escapeHtml($current['Position'])?>" id="order<?=$current['Edition_ID']?>" /></label>
            <input type="submit" value="Set" />
          </form>
        </td>
        <td>
          <?=
            $this->iconButton(
                'trash',
                "Series.unlink('Item', " . $current['Edition_ID'] . ')',
                'Unlink ' . $currentTitle
            )
        ?>
        </td>
        <td>
          <?=$this->escapeHtml($currentTitle)?>
          (<?=$this->escapeHtml($current['Material_Type_Name'])?>)
          <a href="<?=$this->url('edit/item', ['id' => $current['Item_ID']])?>">[edit item]</a>
          <a href="<?=$this->url('edit/edition', ['id' => $current['Edition_ID']])?>">[edit edition]</a>
        </td>
      </tr>
    <?php endforeach; ?>
  </table>
<?php endif; ?>