<? $this->layout()->title = 'Edit Series List' ?>
<? $this->headScript()->appendFile($this->basePath() . '/js/base_editor.js') ?>
<? $this->headScript()->appendFile($this->basePath() . '/js/edit_series.js') ?>
<p><b>Series:</b></p>
<button id="add_series" type="button" onclick="Series.edit('NEW');">Add Series</button>
<br /><br />
<div id="series_list"><?=$this->render('geeby-deeby/edit-series/render-series.phtml')?></div>
