<?php if (isset($series_materials) && count($series_materials) > 0): ?>
  <?php foreach ($series_materials as $current): ?>
    <table class="list_item">
      <tr>
        <td><?=$this->escapeHtml($current['Material_Type_Name'])?></td>
        <td>
          <a class="ui-icon ui-icon-trash" href="#" onclick="Series.unlink('Material', <?=$current['Material_Type_ID']?>); return false;">
          </a>
        </td>
      </tr>
    </table>
  <?php endforeach; ?>
<?php else: ?>
  No material types set.
<?php endif; ?>