<form id="modifyPublisherForm" onsubmit="Series.saveLink('Publisher', <?=$row['Series_Publisher_ID']?>); return false">
  <table class="edit">
    <tr>
      <th scope="row"><label for="Address_ID">Address:</label></th>
      <td><?=$this->render('geeby-deeby/edit-publisher/address-select.phtml', ['addresses' => $addresses, 'selected' => $row['Address_ID']])?></td>
    </tr>
    <tr>
      <th scope="row"><label for="Imprint_ID">Imprint:</label></th>
      <td><?=$this->render('geeby-deeby/edit-publisher/imprint-select.phtml', ['imprints' => $imprints, 'selected' => $row['Imprint_ID']])?></td>
    </tr>
  </table>
  <input id="save_series_publisher" type="submit" value="Save" />
  <div id="save_series_publisher_status"></div>
</form>
