<?php if (isset($series_publishers) && count($series_publishers) > 0): ?>
  <?php foreach ($series_publishers as $current): ?>
    <table class="list_item">
      <tr>
        <td>
          <a href="#" onclick="Series.editLink('Publisher', <?=$current['Series_Publisher_ID']?>); return false;"><?=$this->escapeHtml($current['Publisher_Name'])?></a>
          <?php if (!empty($current['Country_Name']) || !empty($current['Imprint_Name']) || !empty($current['Note'])): ?>
            (<?php
              $city = (empty($current['City_Name']) ? '' : ' -- ' . $current['City_Name']);
              $street = (empty($current['Street']) ? '' : ' -- ' . $current['Street']);
              $address = $current['Country_Name'] . $city . $street;
              echo strlen($current['Imprint_Name']) > 0 ? $this->escapeHtml($current['Imprint_Name']) . ((strlen($address) > 0 || strlen($current['Note']) > 0) ? ': ' : '') : '';
              echo strlen($address) > 0 ? $this->escapeHtml($address) : '';
              echo strlen($current['Note']) > 0 ? ((strlen($address) > 0 || strlen($current['Imprint_Name']) > 0) ? ' - ' : '') . $this->escapeHtml($current['Note']) : '';
            ?>)
          <?php endif; ?>
        </td>
        <td>
          <a class="ui-icon ui-icon-gear" href="#" onclick="Series.editLink('Publisher', <?=$current['Series_Publisher_ID']?>); return false;">
          </a>
        </td>
        <td>
          <a class="ui-icon ui-icon-trash" href="#" onclick="Series.unlink('Publisher', <?=$current['Series_Publisher_ID']?>); return false;">
          </a>
        </td>
      </tr>
    </table>
  <?php endforeach; ?>
<?php else: ?>
  No publishers set.
<?php endif; ?>