<? if (isset($series_publishers) && count($series_publishers) > 0): ?>
  <? foreach ($series_publishers as $current): ?>
    <table class="list_item">
      <tr>
        <td>
          <a href="#" onclick="modifyPublisher(<?=$current['Series_Publisher_ID']?>); return false;"><?=$this->escapeHtml($current['Publisher_Name'])?></a>
          (<?=(strlen($current['Imprint_Name']) > 0) ? $this->escapeHtml($current['Imprint_Name']) . ': ' : ''?><?=$this->escapeHtml($current['Country_Name'])?><?=(strlen($current['Note']) > 0) ? ' - ' . $this->escapeHtml($current['Note']) : '' ?>)
        </td>
        <td>
          <a class="ui-icon ui-icon-gear" href="#" onclick="modifyPublisher(<?=$current['Series_Publisher_ID']?>); return false;">
          </a>
        </td>
        <td>
          <a class="ui-icon ui-icon-trash" href="#" onclick="deletePublisher(<?=$current['Series_Publisher_ID']?>); return false;">
          </a>
        </td>
      </tr>
    </table>
  <? endforeach; ?>
<? else: ?>
  No publishers set.
<? endif; ?>