<?php if (isset($series_publishers) && count($series_publishers) > 0): ?>
  <?php foreach ($series_publishers as $current): ?>
    <table class="list_item">
      <tr>
        <td>
          <a href="<?=$this->url('edit/publisher', ['id' => $current['Publisher_ID']])?>"><?=$this->escapeHtml($current['Publisher_Name'])?></a>
          <?php $extraDetails = ''; ?>
          <?php if (!empty($current['Country_Name']) || !empty($current['Imprint_Name']) || !empty($current['Note'])): ?>
            (<?php
              $city = (empty($current['City_Name']) ? '' : ' -- ' . $current['City_Name']);
              $street = (empty($current['Street']) ? '' : ' -- ' . $current['Street']);
              $address = $current['Country_Name'] . $city . $street;
              $extraDetails .= strlen($current['Imprint_Name']) > 0 ? $this->escapeHtml($current['Imprint_Name']) . ((strlen($address) > 0 || strlen($current['Note']) > 0) ? ': ' : '') : '';
              $extraDetails .= strlen($address) > 0 ? $this->escapeHtml($address) : '';
              $extraDetails .= strlen($current['Note']) > 0 ? ((strlen($address) > 0 || strlen($current['Imprint_Name']) > 0) ? ' - ' : '') . $this->escapeHtml($current['Note']) : '';
              echo $extraDetails;
            ?>)
          <?php endif; ?>
          <?php $currentLabel = $current['Publisher_Name'] . (empty($extraDetails) ? '' : (', ' . $extraDetails)); ?>
        </td>
        <td>
          <?=
            $this->iconButton(
                'gear',
                "Series.editLink('Publisher', " . $current['Series_Publisher_ID'] . ")",
                'Edit options for ' . $currentLabel
            )
          ?>
        </td>
        <td>
          <?=
            $this->iconButton(
                'trash',
                "Series.unlink('Publisher', " . $current['Series_Publisher_ID'] . ")",
                'Unlink ' . $currentLabel
            )
          ?>
        </td>
      </tr>
    </table>
  <?php endforeach; ?>
<?php else: ?>
  No publishers set.
<?php endif; ?>