<?php if (empty($this->relationshipsValues)): ?>
  <p>No relationships defined.</p>
<?php else: ?>
    <?php foreach ($this->relationshipsValues as $current): ?>
      <h3><?=$this->escapeHtml($current['label'])?>:</h3>
      <table class="list_item">
        <?php foreach ($current['values'] as $value): ?>
          <tr>
            <td>
              <a href="<?=$this->url('edit/series', ['id' => $value['Series_ID']])?>">
                <?=$this->escapeHtml($value['Series_Name'])?>
              </a>
            </td><td>
              <?=$this->iconButton(
                'trash',
                "Series.unlink('Relationship', " . $value['Series_ID'] . ", '/" . $current['relationship_id'] . "')",
                'Delete relationship -- ' . $current['label'] . ': ' . $value['Series_Name']
              )?>
            </td>
          </tr>
        <?php endforeach; ?>
      </table>
    <?php endforeach; ?>
  </table>
<?php endif; ?>
