<? if (count($series) < 1): ?>
  <p>No series listed in this database yet.</p>
<? else: ?>
  <h2>
    <?=$this->firstLetterMenu($series, 'Series_Name'); ?>
  </h2>
  <? $currentLetter = false; foreach ($series as $i=>$current): ?>
    <? $first = $this->firstletter($current['Series_Name']); ?>
    <? if ($currentLetter !== $first): $currentLetter = $first; ?>
      <? if ($i > 0): ?>
        <a name="<?=$this->escapeHtml($currentLetter)?>"/>
        <h2><?=$this->escapeHtml($currentLetter)?><a href="#" style="float:right">Back to Top &uarr;</a></h2>
      <? endif; ?>
    <? endif; ?>
    <a href="<?=$this->url('edit/series', array('id' => $current['Series_ID']))?>"><?=$this->escapeHtml($current['Series_Name'])?></a><br />
  <? endforeach; ?>
<? endif; ?>