<?php if (isset($translatedInto) && count($translatedInto) > 0): ?>
  <?php foreach ($translatedInto as $current): ?>
    <table class="list_item">
      <tr>
        <td>
          <a href="<?=$this->url('edit/series', ['id' => $current['Series_ID']])?>#translations-tab">
            <?=$this->escapeHtml($current['Series_Name'])?>
          </a>
        </td>
        <td>
          <?=
            $this->iconButton(
                'trash',
                "Series.unlink('Translation', " . $current['Series_ID'] . ", 'Into')",
                'Unlink translation into: ' . $current['Series_Name']
            )
      ?>
        </td>
      </tr>
    </table>
  <?php endforeach; ?>
<?php else: ?>
  No relevant series.
<?php endif; ?>
