<?php if (isset($translatedFrom) && count($translatedFrom) > 0): ?>
  <?php foreach ($translatedFrom as $current): ?>
    <table class="list_item">
      <tr>
        <td>
          <a href="<?=$this->url('edit/series', ['id' => $current['Series_ID']])?>#translations-tab">
            <?=$this->escapeHtml($current['Series_Name'])?>
          </a>
        </td>
        <td>
          <a class="ui-icon ui-icon-trash" href="#" onclick="Series.unlink('Translation', <?=$current['Series_ID']?>, 'From'); return false;">
          </a>
        </td>
      </tr>
    </table>
  <?php endforeach; ?>
<?php else: ?>
  No relevant series.
<?php endif; ?>
