<div id="editForm">
  <input type="hidden" id="Country_ID" value="<?=$this->escapeHtml($country['Country_ID'])?>" />
  <table class="edit">
    <tr>
      <th>Country:</th>
      <td><input type="text" id="Country_Name" value="<?=isset($country['Country_Name']) ? $this->escapeHtml($country['Country_Name']) : ''?>" /></td>
    </tr>
  </table>
  <button id="save_country" onclick="saveCountry();">Save</button>
  <div id="save_country_status"></div>
</div>
