<form id="editForm" onsubmit="Country.save(); return false;">
  <input type="hidden" id="Country_ID" value="<?=$this->escapeHtml($country['Country_ID'])?>" />
  <table class="edit">
    <tr>
      <th scope="row"><label for="Country_Name">Country:</label></th>
      <td><input type="text" id="Country_Name" value="<?=isset($country['Country_Name']) ? $this->escapeHtml($country['Country_Name']) : ''?>" /></td>
    </tr>
  </table>
  <input type="submit" id="save_country" value="Save" />
  <div id="save_country_status"></div>
</form>
