<? $this->headTitle('Place List - ') ?>
<? $this->headScript()->prependFile($this->basePath() . '/js/edit_countries.js') ?>
<h1>Edit Places</h1>
<table>
  <tr>
    <td>
      <p><b>Countries:</b></p>
      <button id="add_country" type="button" onclick="editCountry('NEW');">Add Country</button>
      <br /><br />
      <div id="country_list"><?=$this->render('geeby-deeby/edit-country/render-countries.phtml')?></div>
    </td>
    <td>
      <p><b>Cities:</b></p>
      <button id="add_city" type="button" onclick="editCity('NEW');">Add City</button>
      <br /><br />
      <div id="city_list"><?=$this->render('geeby-deeby/edit-city/render-cities.phtml')?></div>
    </td>
  </tr>
</table>
