<? $this->layout()->title = 'Edit Places' ?>
<? $this->scriptManager()->add(['base_editor', 'edit_countries']) ?>
<div class="row">
  <div class="col-md-3">
    <p><b>Countries:</b></p>
    <button id="add_country" type="button" onclick="Country.edit('NEW');">Add Country</button>
    <br /><br />
    <div id="country_list"><?=$this->render('geeby-deeby/edit-country/render-countries.phtml')?></div>
  </div>
  <div class="col-md-3">
    <p><b>Cities:</b></p>
    <button id="add_city" type="button" onclick="City.edit('NEW');">Add City</button>
    <br /><br />
    <div id="city_list"><?=$this->render('geeby-deeby/edit-city/render-cities.phtml')?></div>
  </div>
</div>
