<? $this->layout()->title = 'Edit Places' ?>
<? $this->headScript()->prependFile($this->basePath() . '/js/edit_countries.js') ?>
<div class="row">
  <div class="col-md-3">
    <p><b>Countries:</b></p>
    <button id="add_country" type="button" onclick="editCountry('NEW');">Add Country</button>
    <br /><br />
    <div id="country_list"><?=$this->render('geeby-deeby/edit-country/render-countries.phtml')?></div>
  </div>
  <div class="col-md-3">
    <p><b>Cities:</b></p>
    <button id="add_city" type="button" onclick="editCity('NEW');">Add City</button>
    <br /><br />
    <div id="city_list"><?=$this->render('geeby-deeby/edit-city/render-cities.phtml')?></div>
  </div>
</div>
