<?php if (isset($countries) && count($countries) > 0): ?>
  <select id="<?=!empty($idPrefix) ? $this->escapeHtml($idPrefix) : ''?>Country_ID">
    <?php foreach ($countries as $current): ?>
      <option value="<?=$current['Country_ID']?>"<?=(isset($selected) && $current['Country_ID'] == $selected) ? ' selected="selected"' : ''?>>
        <?=$this->escapeHtml($current['Country_Name'])?>
      </option>
    <?php endforeach; ?>
  </select>
<?php else: ?>
  Please define countries.
<?php endif; ?>