<form id="editForm" onsubmit="Citation.save(); return false;">
  <input type="hidden" id="Citation_ID" value="<?=$this->escapeHtml($citation['Citation_ID'])?>" />
  <table class="edit">
    <tr>
      <th scope="row"><label for="Citation_Text">Citation:</label></th>
      <td><input type="text" id="Citation_Text" value="<?=isset($citation['Citation']) ? $this->escapeHtml($citation['Citation']) : ''?>" /></td>
    </tr>
  </table>
  <input type="submit" id="save_citation" value="Save" />
  <div id="save_citation_status"></div>
</form>
