<?php if (isset($citations) && count($citations) > 0): ?>
  <select id="<?=!empty($idPrefix) ? $this->escapeHtml($idPrefix) : ''?>Citation_ID">
    <option value="">-- no citation set --</option>
    <?php foreach ($citations as $current): ?>
      <option value="<?=$current['Citation_ID']?>"<?=(isset($selected) && $current['Citation_ID'] == $selected) ? ' selected="selected"' : ''?>>
        <?=$this->escapeHtml($current['Citation'])?>
      </option>
    <?php endforeach; ?>
  </select>
<?php else: ?>
  Please define citations.
<?php endif; ?>