<div id="editForm">
  <input type="hidden" id="Full_Text_Source_ID" value="<?=$this->escapeHtml($fulltextsource['Full_Text_Source_ID'])?>" />
  <table class="edit">
    <tr>
      <th>Full Text Source:</th>
      <td><input type="text" id="Full_Text_Source_Name" value="<?=isset($fulltextsource['Full_Text_Source_Name']) ? $this->escapeHtml($fulltextsource['Full_Text_Source_Name']) : ''?>" /></td>
    </tr>
  </table>
  <button id="save_source" onclick="saveFullTextSource();">Save</button>
  <div id="save_source_status"></div>
</div>
