<form id="editForm" onsubmit="FullTextSource.save(); return false;">
  <input type="hidden" id="Full_Text_Source_ID" value="<?=$this->escapeHtml($fulltextsource['Full_Text_Source_ID'])?>" />
  <table class="edit">
    <tr>
      <th scope="row"><label for="Full_Text_Source_Name">Full Text Source:</label></th>
      <td><input type="text" id="Full_Text_Source_Name" value="<?=isset($fulltextsource['Full_Text_Source_Name']) ? $this->escapeHtml($fulltextsource['Full_Text_Source_Name']) : ''?>" /></td>
    </tr>
  </table>
  <input type="submit" id="save_source" value="Save" />
  <div id="save_source_status"></div>
</form>
