<?php $this->layout()->title = 'Edit Edition Attributes' ?>
<?php $this->scriptManager()->add(['base_editor', 'edit_attributes']) ?>
<p><b>Edition Attributes:</b></p>
<button id="add_edition_attribute" type="button" onclick="EditionsAttribute.edit('NEW');">Add Edition Attribute</button>
<br /><br />
<div id="editions_attribute_list"><?=$this->render('geeby-deeby/edit-edition-attribute/render-edition-attributes.phtml')?></div>
