<?
    $this->headTitle('City List - ');
?>
<h1>City List</h1>
<? if (count($cities) < 1): ?>
  <p>No cities listed in this database yet.</p>
<? else: ?>
  <? $currentLetter = false; foreach ($cities as $current): ?>
    <? $first = $this->firstletter($current['City_Name']); if ($currentLetter !== $first): $currentLetter = $first; ?>
      <h2><?=$this->escapeHtml($currentLetter)?></h2>
    <? endif; ?>
    <a href="<?=$this->url('city', array('id' => $current['City_ID']))?>">
      <?=$this->escapeHtml($this->fixtitle($current['City_Name']))?>
    </a><br />
  <? endforeach; ?>
<? endif; ?>