<?php
    $this->layout()->title = 'City List';
?>
<?php if (count($cities) < 1): ?>
  <p>No cities listed in this database yet.</p>
<?php else: ?>
  <h2>
    <?=$this->firstLetterMenu($cities, 'City_Name'); ?>
  </h2>
  <?php $currentLetter = false; ?>
  <?php foreach ($cities as $i => $current): ?>
    <?php $first = $this->firstletter($current['City_Name']); ?>
    <?php if ($currentLetter !== $first): $currentLetter = $first; ?>
      <?php if ($i > 0): ?>
        <a name="<?=$this->escapeHtml($currentLetter)?>"/>
        <h2><?=$this->escapeHtml($currentLetter)?><a href="#" style="float:right">Back to Top &uarr;</a></h2>
      <?php endif; ?>
    <?php endif; ?>
    <a href="<?=$this->url('city', ['id' => $current['City_ID']])?>">
      <?=$this->escapeHtml($this->fixtitle($current['City_Name']))?>
    </a><br />
  <?php endforeach; ?>
<?php endif; ?>