<?php if (!$details): ?>
  <?php $this->layout()->title = 'Not Found' ?>
  <p>The episode you requested does not exist.</p>
<?php else: ?>
  <?php $this->layout()->title = 'The Spare Change Library' ?>
  <!-- <a href="<?=$this->url('podcast')?>"><img alt="Spare Change Library logo" src="<?=$this->url('home')?>images/spl-logo.png" /></a> -->
  <div class="row">
    <div class="col-sm-5" style="text-align:center">
      <img alt="Cover" src="<?=$this->url('home')?>mp3/<?=$this->escapeHtml($details['image'])?>"/>
    </div>
    
    <div class="col-sm-7">
      <h2><a href="<?=$this->url($details['category_route'])?>"><?=$this->escapeHtml($details['category'])?></a>: <?=$this->escapeHtml($details['title'])?></h2>

      <p><?=$this->escapeHtml($details['description'])?></p>

      <p>Released on <?=date('F j, Y', strtotime($details['date']))?>.</p>

      <p>Download: <a href="<?=$this->url('home')?>mp3/<?=$this->escapeHtml($details['filename'])?>">MP3</a> (<?=number_format(($details['size'] / 1024) / 1024, 2)?> MB, Duration: <?=$this->escapeHtml($details['duration'])?>)</p>

      <?php if ($details['credits']): ?>
        <h3>Credits</h3>
        <?=$details['credits']?>
      <?php endif; ?>

      <?php if ($prev): ?>
        <p>Previous episode: <a href="<?=$this->url('podcast-about')?>?file=<?=urlencode($prev['filename'])?>"><?=$this->escapeHtml($prev['title'])?></a></p>
      <?php endif; ?>
      <?php if ($next): ?>
        <p>Next episode: <a href="<?=$this->url('podcast-about')?>?file=<?=urlencode($next['filename'])?>"><?=$this->escapeHtml($next['title'])?></a></p>
      <?php endif; ?>

      <p><a href="<?=$this->url('podcast')?>">About The Spare Change Library</a></p>
    <?php endif; ?>
  </div>
</div>