<?php
  $fulltitle = (empty($latest['category']) ? '' : $latest['category'] . ': ') . $latest['title']
?>
<p><a href="<?=$this->url('podcast-about')?>?file=<?=urlencode($latest['filename'])?>"><?=$this->escapeHtml($fulltitle)?></a></p>
<p>Released on <?=date('F j, Y', strtotime($latest['date']))?>.</p>
<p>Download: <a href="<?=$this->url('home')?>mp3/<?=$this->escapeHtml($latest['filename'])?>">MP3</a> (<?=number_format(($latest['size'] / 1024) / 1024, 2)?> MB, Duration: <?=$this->escapeHtml($latest['duration'])?>)</p>