<?php $this->layout()->title = 'The Spare Change Library' ?>

<p>The Spare Change Library is the dime novel and popular literature podcast, featuring audio editions of stories, as well as scholarship.
All episodes are available through an <a href="<?=$this->url('podcast-rss')?>">RSS feed</a>.</p>

<p>The Spare Change Library is produced by Lancelot Darling &amp; Friends (named after the hero of Mrs. Alex. McVeigh Miller's <i>The Bride of the Tomb</i>).</p>

<!-- <div style="text-align: center;"><img alt="Spare Change Library logo" src="<?=$this->url('home')?>images/spl-logo.png" /></div> -->

<h2>Latest Episode</h2>
<div class="row">
  <div class="col-sm-12">
    <?php $this->latest = current($episodes) ?>
    <?=$this->partial('geeby-deeby-local/podcast/episode.phtml')?>
  </div>
</div>
<h2>Previous Episodes</h2>
<div class="row">
  <div class="col-sm-12">
    <?php if(count($episodes) > 1): ?>
      <?php next($episodes) ?>
      <?php while($this->latest = current($episodes)): ?>
        <?=$this->partial('geeby-deeby-local/podcast/episode.phtml')?>
        <hr/>
        <?php next($episodes) ?>
      <?php endwhile; ?>
      <?php if (!$all): ?><a href="?all=1">More...</a><?php endif; ?>
    <?php endif; ?>
  </div>
</div>
