<? $this->headTitle('Podcast - '); ?>
<h1>Mittie's Storytime</h1>

<img src="/images/mittie.png" alt="Mittie's Storytime" />

<p>Mittie's Storytime is a collection of audio editions of dime novel fiction.
It is part of the <a href="<?=$this->url('podcast')?>">Spare Change Library</a>.</p>

<?=$this->partial('geeby-deeby-local/podcast/latest.phtml')?>

<h2>Credits</h2>

<h3>The Bride of the Tomb by Mrs. Alex. McVeigh Miller</h3>

<p>The Spare Change Library thanks the following for The Bride of the Tomb episodes of Mittie's Storytime:<br />
Principal Voice Talents: Laura Bang &amp; Demian Katz<br />
Intro/Outro Narratives Voiced By: Chris Hallberg<br />
Music: "The Guava Rag" by <a href="http://www.brettstuff.com/">Brett Donnelly</a><br />
Executive Producer: Laura Bang</p>
