<? $this->layout()->title = 'Mittie\'s Storytime' ?>

<div style="text-align:center">
  <img src="/images/mittie-text.png" style="display:block;margin:auto" alt="Mittie's Storytime" />

  <p>Mittie's Storytime is a collection of audio editions of dime novel fiction. It is part of the <a href="<?=$this->url('podcast')?>">Spare Change Library</a>.</p>
  <p>An audiobook edition of <i>The Bride of the Tomb</i>, the first complete novel featured on this podcast, may also be downloaded in its entirety (<a href="http://digital.library.villanova.edu/Item/vudl:384795">MP3/OGG/FLAC</a>, <a href="https://dimenovels.org/m4b/bott32kbps.m4b">32kbps M4B</a>, <a href="https://dimenovels.org/m4b/bott64kbps.m4b">64kbps M4B</a>).</p>
</div>

<h2>Latest Episode</h2>
<? $this->latest = current($episodes) ?>
<?=$this->partial('geeby-deeby-local/podcast/episode.phtml')?>

<? if(count($episodes) > 1): ?>
  <h2>Previous Episodes</h2>
  <? next($episodes) ?>
  <? while($this->latest = current($episodes)): ?>
    <?=$this->partial('geeby-deeby-local/podcast/episode.phtml')?>
    <hr/>
    <? next($episodes) ?>
  <? endwhile; ?>
<? endif; ?>
