<? $this->layout()->title = 'Professor M\'s Lecture Series' ?>

<div style="text-align:center">
  <img src="/images/professor-text.png" alt="Professor M's Lecture Series" />

  <p>Professor M's Lecture Series is a collection of oral history about dime novels and popular literature. It is part of the <a href="<?=$this->url('podcast')?>">Spare Change Library</a>.</p>
</div>

<h2>Latest Episode</h2>
<? $this->latest = current($episodes) ?>
<?=$this->partial('geeby-deeby-local/podcast/episode.phtml')?>

<? if(count($episodes) > 1): ?>
  <h2>Previous Episodes</h2>
  <? next($episodes) ?>
  <? while($this->latest = current($episodes)): ?>
    <?=$this->partial('geeby-deeby-local/podcast/episode.phtml')?>
    <hr/>
    <? next($episodes) ?>
  <? endwhile; ?>
<? endif; ?>