<? $this->headTitle('Podcast - '); ?>

<h1>Professor M's Lecture Series</h3>

<img src="/images/professor.png" alt="Professor M's Lecture Series" />

<p>Professor M's Lecture Series is a collection of oral history about dime novels and popular literature.
It is part of the <a href="<?=$this->url('podcast')?>">Spare Change Library</a>.</p>

<p><i>Coming soon....</i></p>

<?=$this->partial('geeby-deeby-local/podcast/latest.phtml')?>