<?php $this->layout()->title = 'Edit Full Text Attributes' ?>
<?php $this->scriptManager()->add(['base_editor', 'edit_attributes']) ?>
<p><b>Full Text Attributes:</b></p>
<button id="add_edition_full_text_attribute" type="button" onclick="EditionsFullTextAttribute.edit('NEW');">Add Full Text Attribute</button>
<br /><br />
<div id="edition_full_text_attribute_list"><?=$this->render('geeby-deeby/edit-edition-full-text-attribute/render-edition-full-text-attributes.phtml')?></div>
