<div id="editForm">
  <input type="hidden" id="Series_Relationship_ID" value="<?=$relationship['Series_Relationship_ID']?>" />
  <table class="edit">
    <tr>
      <th>Relationship Name:</th>
      <td><input type="text" id="Series_Relationship_Name" value="<?=isset($relationship['Series_Relationship_Name']) ? $this->escapeHtml($relationship['Series_Relationship_Name']) : ''?>" /></td>
    </tr>
    <tr>
      <th>RDF Property (optional URI):</th>
      <td><input type="text" id="Series_Relationship_RDF_Property" value="<?=isset($relationship['Series_Relationship_RDF_Property']) ? $this->escapeHtml($relationship['Series_Relationship_RDF_Property']) : ''?>" /></td>
    </tr>
    <tr>
      <th>Display Priority (lower numbers displayed first):</th>
      <td><input type="text" id="Display_Priority" value="<?=isset($relationship['Display_Priority']) ? $this->escapeHtml($relationship['Display_Priority']) : '0'?>" /></td>
    </tr>
    <tr>
      <th>Inverse Relationship Name (optional):</th>
      <td><input type="text" id="Series_Inverse_Relationship_Name" value="<?=isset($relationship['Series_Inverse_Relationship_Name']) ? $this->escapeHtml($relationship['Series_Inverse_Relationship_Name']) : ''?>" /></td>
    </tr>
    <tr>
      <th>Inverse RDF Property (optional URI):</th>
      <td><input type="text" id="Series_Inverse_Relationship_RDF_Property" value="<?=isset($relationship['Series_Inverse_Relationship_RDF_Property']) ? $this->escapeHtml($relationship['Series_Inverse_Relationship_RDF_Property']) : ''?>" /></td>
    </tr>
    <tr>
      <th>Inverse Display Priority (lower numbers displayed first):</th>
      <td><input type="text" id="Inverse_Display_Priority" value="<?=isset($relationship['Inverse_Display_Priority']) ? $this->escapeHtml($relationship['Inverse_Display_Priority']) : '0'?>" /></td>
    </tr>
  </table>
  <button id="save_series_relationship" onclick="SeriesRelationship.save();">Save</button>
  <div id="save_series_relationship_status"></div>
</div>
