<div id="editForm">
  <input type="hidden" id="Tags_Relationship_ID" value="<?=$relationship['Tags_Relationship_ID']?>" />
  <table class="edit">
    <tr>
      <th>Relationship Name:</th>
      <td><input type="text" id="Tags_Relationship_Name" value="<?=isset($relationship['Tags_Relationship_Name']) ? $this->escapeHtml($relationship['Tags_Relationship_Name']) : ''?>" /></td>
    </tr>
    <tr>
      <th>RDF Property (optional URI):</th>
      <td><input type="text" id="Tags_Relationship_RDF_Property" value="<?=isset($relationship['Tags_Relationship_RDF_Property']) ? $this->escapeHtml($relationship['Tags_Relationship_RDF_Property']) : ''?>" /></td>
    </tr>
    <tr>
      <th>Display Priority (lower numbers displayed first):</th>
      <td><input type="text" id="Display_Priority" value="<?=isset($relationship['Display_Priority']) ? $this->escapeHtml($relationship['Display_Priority']) : '0'?>" /></td>
    </tr>
    <tr>
      <th>Inverse Relationship Name (optional):</th>
      <td><input type="text" id="Tags_Inverse_Relationship_Name" value="<?=isset($relationship['Tags_Inverse_Relationship_Name']) ? $this->escapeHtml($relationship['Tags_Inverse_Relationship_Name']) : ''?>" /></td>
    </tr>
    <tr>
      <th>Inverse RDF Property (optional URI):</th>
      <td><input type="text" id="Tags_Inverse_Relationship_RDF_Property" value="<?=isset($relationship['Tags_Inverse_Relationship_RDF_Property']) ? $this->escapeHtml($relationship['Tags_Inverse_Relationship_RDF_Property']) : ''?>" /></td>
    </tr>
    <tr>
      <th>Inverse Display Priority (lower numbers displayed first):</th>
      <td><input type="text" id="Inverse_Display_Priority" value="<?=isset($relationship['Inverse_Display_Priority']) ? $this->escapeHtml($relationship['Inverse_Display_Priority']) : '0'?>" /></td>
    </tr>
  </table>
  <button id="save_tag_relationship" onclick="TagsRelationship.save();">Save</button>
  <div id="save_tag_relationship_status"></div>
</div>
