<? $this->layout()->title = 'Edit Users' ?>
<? $this->scriptManager()->add(['base_editor', 'edit_users']) ?>
<div class="row">
  <div class="col-md-6">
    <p><b>Users:</b></p>
    <div id="user_list"><?=$this->render('geeby-deeby/edit-user/render-users.phtml')?></div>
  </div>
  <div class="col-md-6">
    <p><b>Groups:</b></p>
    <button id="add_user_group" type="button" onclick="UserGroup.edit('NEW');">Add Group</button>
    <br /><br />
    <div id="user_group_list"><?=$this->render('geeby-deeby/edit-user/render-usergroups.phtml')?></div>
  </div>
</div>