<?php foreach ($usergroups as $current): ?>
  <table class="list_item">
    <tr>
      <td>
        <a href="#" onclick="UserGroup.edit(<?=$this->escapeHtml($current['User_Group_ID'])?>); return false;"><?=$this->escapeHtml($current['Group_Name'])?></a>
      </td>
      <td>
        <?=
          $this->iconButton(
              'trash',
              "UserGroup.destroy(" . $current['User_Group_ID'] . ")",
              'Delete group: ' . $current['Group_Name']
          )
    ?>
      </td>
    </tr>
  </table>
<?php endforeach; ?>
<?php if (count($usergroups) == 0): ?>No groups defined.<?php endif; ?>