<?php if (count($users) < 1): ?>
  <p>No users in this database yet.</p>
<?php else: ?>
  <h2>
    <?=$this->firstLetterMenu($users, 'Username'); ?>
  </h2>
  <?php $currentLetter = false;
    foreach ($users as $i => $current): ?>
    <?php $first = $this->firstletter($current['Username']); ?>
    <?php if ($currentLetter !== $first): $currentLetter = $first; ?>
      <?php if ($i > 0): ?>
        <a name="<?=$this->escapeHtml($currentLetter)?>"/>
        <h2><?=$this->escapeHtml($currentLetter)?><a href="#" style="float:right">Back to Top &uarr;</a></h2>
      <?php endif; ?>
    <?php endif; ?>
    <table class="list_item">
      <tr>
        <td>
          <a href="<?=$this->url('edit/user', ['id' => $current['User_ID']])?>">
            <?=$this->escapeHtml($current['Username'])?>
          </a><br />
        </td>
        <td>
          <?=
              $this->iconButton(
                  'trash',
                  "User.destroy(" . $current['User_ID'] . ")",
                  'Delete user: ' . $current['Username']
              )
        ?>
        </td>
      </tr>
    </table>
  <?php endforeach; ?>
<?php endif; ?>