<?php if (isset($usergroups) && count($usergroups) > 0): ?>
  <select id="<?=!empty($idPrefix) ? $this->escapeHtml($idPrefix) : ''?>User_Group_ID">
    <option value="">None</option>
    <?php foreach ($usergroups as $current): ?>
      <option value="<?=$current['User_Group_ID']?>"<?=(isset($selected) && $current['User_Group_ID'] == $selected) ? ' selected="selected"' : ''?>>
        <?=$this->escapeHtml($current['Group_Name'])?>
      </option>
    <?php endforeach; ?>
  </select>
<?php else: ?>
  Please define groups.
<?php endif; ?>