<?
    $this->layout()->title = $title;
?>
<? if (!empty($desc)): ?><?=$desc?><? endif; ?>
<? if (count($links) < 1): ?>
  <p>No links listed in this database yet.</p>
<? else: ?>
  <h2>
    <?=$this->firstLetterMenu($links, 'Link_Type'); ?>
  </h2>
  <? $type = false; foreach ($links as $i=>$link): ?>
    <? if ($type != $link['Link_Type']): $type = $link['Link_Type']; ?>
      <? if ($i > 0): ?>
        <a name="<?=$this->escapeHtml($currentLetter)?>"/>
        <h2><?=$this->escapeHtml(substr($type, $typeTrim))?><a href="#" style="float:right">Back to Top &uarr;</a></h2>
      <? endif; ?>
    <? endif; ?>
    <p class="link">
      <a href="<?=$this->escapeHtml($link['URL'])?>"><?=$this->fixtitle($link['Link_Name'])?></a><br />
      <? if (!empty($link['Description'])): ?><?=$link['Description']?><br /><? endif; ?>
      <span class="url"><?=$this->escapeHtml($link['URL'])?></span>
      (last verified: <?=$this->escapeHtml($link['Date_Checked'])?>)
    </p>
  <? endforeach; ?>
<? endif; ?>