<?php if (count($predicates) == 0): ?>
  <p>No predicates defined yet.</p>
<?php else: ?>
  <h2>
    <?=$this->firstLetterMenu($predicates, 'Predicate_Abbrev'); ?>
  </h2>
  <?php $currentLetter = false;
    foreach ($predicates as $i => $current): ?>
    <?php $first = $this->firstletter($current['Predicate_Abbrev']); ?>
    <?php if ($currentLetter !== $first): $currentLetter = $first; ?>
      <?php if ($i > 0): ?>
        <a name="<?=$this->escapeHtml($currentLetter)?>"/>
        <h2><?=$this->escapeHtml($currentLetter)?><a href="#" style="float:right">Back to Top &uarr;</a></h2>
      <?php endif; ?>
    <?php endif; ?>
    <a href="#" onClick="Predicate.edit(<?=$current['Predicate_ID'] ?>);return false">
      <?=$this->escapeHtml($current['Predicate_Abbrev'] . ' (' . $current['Predicate'] . ')')?>
    </a><br />
  <?php endforeach; ?>
<?php endif; ?>