<? if (count($predicates) == 0): ?>
  <p>No predicates defined yet.</p>
<? else: ?>
  <h2>
    <?=$this->firstLetterMenu($predicates, 'Predicate_Abbrev'); ?>
  </h2>
  <? $currentLetter = false; foreach ($predicates as $i=>$current): ?>
    <? $first = $this->firstletter($current['Predicate_Abbrev']); ?>
    <? if ($currentLetter !== $first): $currentLetter = $first; ?>
      <? if ($i > 0): ?>
        <a name="<?=$this->escapeHtml($currentLetter)?>"/>
        <h2><?=$this->escapeHtml($currentLetter)?><a href="#" style="float:right">Back to Top &uarr;</a></h2>
      <? endif; ?>
    <? endif; ?>
    <a href="#" onClick="Predicate.edit(<?=$current['Predicate_ID'] ?>);return false">
      <?=$this->escapeHtml($current['Predicate_Abbrev'] . ' (' . $current['Predicate'] . ')')?>
    </a><br />
  <? endforeach; ?>
<? endif; ?>