<?
    $this->layout()->title = 'Check for Missing Data';

    $formatRanges = function ($values) {
        $currentStart = $currentEnd = null;
        $parts = [];
        foreach ($values as $current) {
            if ($currentStart === null) {
                $currentStart = $currentEnd = $current;
            } else if ($current == $currentEnd + 1) {
                $currentEnd = $current;
            } else {
                $parts[] = $currentStart === $currentEnd ? $currentStart : "$currentStart-$currentEnd";
                $currentStart = $currentEnd = $current;
            }
        }
        if (null !== $currentStart) {
            $parts[] = $currentStart === $currentEnd ? $currentStart : "$currentStart-$currentEnd";
        }
        return implode(', ', $parts);
    };
?>

<h2>Missing Credits</h2>
<? if (empty($missingCredits)): ?>
  <p>None.</p>
<? else: ?>
  <? foreach ($missingCredits as $current): ?>
    <a href="<?=$this->url('item', ['id' => $current['Item_ID']])?>">
      <? if (!empty($current['Position'])): ?>
        #<?=$this->escapeHtml($current['Position'])?>
      <? else: ?>
        <?=$this->escapeHtml($this->fixTitle($current['Item_Name']))?>
      <? endif; ?>
    </a>
  <? endforeach; ?>
<? endif; ?>

<h2>Missing Dates</h2>
<? if (empty($missingDates)): ?>
  <p>None.</p>
<? else: ?>
  <? foreach ($missingDates as $current): ?>
    <a href="<?=$this->url('item', ['id' => $current['Item_ID']])?>">
      <? if (!empty($current['Position'])): ?>
        #<?=$this->escapeHtml($current['Position'])?>
      <? else: ?>
        <?=$this->escapeHtml($this->fixTitle($current['Item_Name']))?>
      <? endif; ?>
    </a>
  <? endforeach; ?>
<? endif; ?>

<h2>Statistics</h2>

<? if (empty($dateStats['Start'])): ?>
  <p>No date information.</p>
<? elseif ($dateStats['Start'] == $dateStats['End']): ?>
  <p>Series contains dates from <?=$this->escapeHtml($dateStats['End'])?>.</p>
<? else: ?>
  <p>Series contains dates ranging from <?=$this->escapeHtml($dateStats['Start'])?>
  to <?=$this->escapeHtml($dateStats['End'])?>.</p>
<? endif; ?>

<? if (!empty($itemStats)): ?>
  <p>Series contains <?=$this->escapeHtml($itemStats['Total'])?>
  total items representing <?=$this->escapeHtml($itemStats['Different'])?>
  different numbers ranging from <?=$this->escapeHtml($itemStats['Start'])?>
  to <?=$this->escapeHtml($itemStats['End'])?>.</p>
  <? if (!empty($itemStats['Dupes'])): ?>
    <p>Duplicate numbers: <?=$formatRanges($itemStats['Dupes'])?></p>
  <? endif; ?>
  <? if (!empty($itemStats['Missing'])): ?>
    <p>Missing numbers: <?=$formatRanges($itemStats['Missing'])?></p>
  <? endif; ?>
<? else: ?>
  <p>No item information.</p>
<? endif; ?>