<?php
    $this->layout()->title = 'Series with Comments';
?>
<?php if (count($comments) > 0): ?>
  <?php $currentLetter = $currentSeries = false;
  foreach ($comments as $current): ?>
    <?php $first = $this->firstletter($current['Series_Name']);
    if ($currentLetter !== $first): $currentLetter = $first; ?>
      <h2><?=$this->escapeHtml($currentLetter)?></h2>
    <?php endif; ?>
    <?php if ($currentSeries !== $current['Series_ID']): ?>
      <?php $currentSeries = $current['Series_ID']; ?>
      <a href="<?=$this->url('series', ['id' => $current['Series_ID']])?>">
        <?=$this->escapeHtml($this->fixtitle($current['Series_Name']))?>
      </a><br />
    <?php endif; ?>
  <?php endforeach; ?>
<?php else: ?>
  <p>No comments listed.</p>
<?php endif; ?>
