<?
    $title = $this->fixtitle($series['Series_Name']);
    $this->headTitle('Series - ' . $title . ' - ');
?>
<h1><?=$this->escapeHtml($title)?></h1>

<p>
  <a href="<?=$this->url('series')?>">[List All Series]</a>
  <a href="<?=$this->url('series', array('id' => $series['Series_ID'], 'extra' => 'Images'))?>">[List Series Images]</a>
</p>

<table class="series">
  <tr><th>Language:</th><td><?=$this->escapeHtml($language['Language_Name'])?></td></tr>
  <? $altTitleCount = count($altTitles); if ($altTitleCount > 0): ?>
    <tr>
      <th>Alternate Title<?=$altTitleCount > 1 ? 's' : ''?>:</th>
      <td>
        <? foreach ($altTitles as $altTitle): ?>
          <?=$this->escapeHtml($this->fixtitle($altTitle['Series_AltName']))?>
          <? if (!empty($altTitle['Note'])): ?>(<?=$this->escapeHtml($altTitle['Note'])?>)<? endif; ?>
          <br />
        <? endforeach; ?>
      </td>
    </tr>
  <? endif; ?>
</table>

<? if (count($items) < 1): ?>
  <p>No items listed in this series yet.</p>
<? else: ?>
  <? $matType = ''; ?>
  <? foreach ($items as $item): ?>
    <? if ($matType != $item['Material_Type_Name']): ?>
      <? $matType = $item['Material_Type_Name'] ?>
      <h2><?=$this->escapeHtml($matType)?></h2>
    <? endif; ?>
    <?=$item['Position'] > 0 ? $item['Position'] . '. ' : ''?>
    <a href="<?=$this->url('item', array('id' => $item['Item_ID']))?>">
      <?=$this->escapeHtml($this->fixtitle($item['Item_Name']))?>
    </a><br />
  <? endforeach; ?>
<? endif; ?>