<?php
    $title = $this->fixtitle($series['Series_Name']);
    $this->layout()->title = 'Series People - ' . $title;
    $lastPerson = null;
?>
<?php if (count($people) < 1): ?>
  <p>No people listed for this series.</p>
<?php else: ?>
  <?php foreach ($people as $i => $current): ?>
    <?php if (($currentPerson = $this->showperson($current)) !== $lastPerson): ?>
      <?php $lastPerson = $currentPerson; ?>
      <h2>
        <a href="<?=$this->url('person', ['id' => $current['Person_ID']])?>">
          <?=$this->escapeHtml($currentPerson)?>
        </a>
      </h2>
    <?php endif; ?>
    <a href="<?=$this->url('item', ['id' => $current['Item_ID']])?>">
      <?=$this->escapeHtml($this->fixtitle(isset($current['Item_AltName']) && !empty($current['Item_AltName']) ? $current['Item_AltName'] : $current['Item_Name']))?>
    </a><br />
  <?php endforeach; ?>
<?php endif; ?>
