<?
    $title = $this->fixtitle($series['Series_Name']);
    $this->layout()->title = 'Series - ' . $title;
?>
<p>
  <a href="<?=$this->url('series')?>">[List All Series]</a>
  <a href="<?=$this->url('series', array('id' => $series['Series_ID'], 'extra' => 'FullText'))?>">[List Series Full Text]</a>
  <a href="<?=$this->url('series', array('id' => $series['Series_ID'], 'extra' => 'Images'))?>">[List Series Images]</a>
</p>

<table class="series">
  <tr><th>Language:</th><td><?=$this->escapeHtml($language['Language_Name'])?></td></tr>

  <? $altTitleCount = count($altTitles); if ($altTitleCount > 0): ?>
    <tr>
      <th>Alternate Title<?=$altTitleCount > 1 ? 's' : ''?>:</th>
      <td>
        <? foreach ($altTitles as $altTitle): ?>
          <?=$this->escapeHtml($this->fixtitle($altTitle['Series_AltName']))?>
          <? if (!empty($altTitle['Note'])): ?>(<?=$this->escapeHtml($altTitle['Note'])?>)<? endif; ?>
          <br />
        <? endforeach; ?>
      </td>
    </tr>
  <? endif; ?>

  <? $pubCount = count($publishers); if ($pubCount > 0): ?>
    <tr>
      <th>Publisher<?=$pubCount > 1 ? 's' : ''?>:</th>
      <td>
        <? foreach ($publishers as $publisher): ?>
          <a href="<?=$this->url('publisher', array('id' => $publisher['Publisher_ID']))?>">
            <?=$this->escapeHtml($publisher['Publisher_Name'])?>
          </a>
          <? if (!empty($publisher['City_Name']) || !empty($publisher['Street'])): ?>
            (<?
              if (!empty($publisher['City_Name'])) {
                echo '<a href="' . $this->url('city', array('id' => $publisher['City_ID'])) . '">'
                  . $this->escapeHtml($publisher['City_Name']) . '</a>';
                if (!empty($publisher['Street'])) {
                  echo ': ';
                }
              }
              echo $this->escapeHtml($publisher['Street']);
            ?>)
          <? endif; ?>
          <? if (!empty($publisher['Imprint_Name'])): ?>
            (<?=$this->escapeHtml($publisher['Imprint_Name'])?> imprint)
          <? endif; ?>
          <? if (!empty($publisher['Country_Name'])): ?>
            --
            <a href="<?=$this->url('country', array('id' => $publisher['Country_ID']))?>">
              <?=$this->escapeHtml($publisher['Country_Name'])?>
            </a>
          <? endif; ?>
          <? if (!empty($publisher['Note'])): ?>
            (<?=$this->escapeHtml($publisher['Note'])?>)
          <? endif; ?>
          <br />
        <? endforeach; ?>
      </td>
    </tr>
  <? endif; ?>

  <? $catCount = count($categories); if ($catCount > 0): ?>
    <tr>
      <th><?=$catCount > 1 ? 'Categories' : 'Category'?>:</th>
      <td>
        <? foreach ($categories as $category): ?>
          <a href="<?=$this->url('category', array('id' => $category['Category_ID']))?>">
            <?=$this->escapeHtml($category['Category'])?>
          </a><br />
        <? endforeach; ?>
      </td>
    </tr>
  <? endif; ?>

  <? if (count($translatedFrom) > 0): ?>
    <tr>
      <th>Translated From:</th>
      <td>
        <? foreach ($translatedFrom as $current): ?>
          <a href="<?=$this->url('series', array('id' => $current['Series_ID']))?>">
            <?=$this->escapeHtml($this->fixtitle($current['Series_Name']))?>
          </a> (<?=$this->escapeHtml($current['Language_Name'])?>)<br />
        <? endforeach; ?>
      </td>
    </tr>
  <? endif; ?>

  <? if (count($translatedInto) > 0): ?>
    <tr>
      <th>Translated Into:</th>
      <td>
        <? foreach ($translatedInto as $current): ?>
          <a href="<?=$this->url('series', array('id' => $current['Series_ID']))?>">
            <?=$this->escapeHtml($this->fixtitle($current['Series_Name']))?>
          </a> (<?=$this->escapeHtml($current['Language_Name'])?>)<br />
        <? endforeach; ?>
      </td>
    </tr>
  <? endif; ?>

  <? foreach ($seriesAttributes as $current): ?>
    <tr>
        <th><?=$this->escapeHtml($current->Series_Attribute_Name)?>:</th>
        <td>
          <? if ($current->Allow_HTML == 1): ?>
            <?=$current->Series_Attribute_Value?>
          <? else: ?>
            <?=$this->escapeHtml($current->Series_Attribute_Value)?>
          <? endif; ?>
        </td>
  <? endforeach; ?>
</table>

<? if (!empty($series['Series_Description'])): ?>
  <p><?=nl2br($series['Series_Description'])?></p>
<? endif; ?>

<? if (count($items) < 1): ?>
  <p>No items listed in this series yet.</p>
<? else: ?>
  <? $matType = ''; ?>
  <? foreach ($items as $item): ?>
    <? if ($matType != $item['Material_Type_Plural_Name']): ?>
      <? $matType = $item['Material_Type_Plural_Name'] ?>
      <h2><?=$this->escapeHtml($matType)?></h2>
    <? endif; ?>
    <?=$item['Position'] > 0 ? $item['Position'] . '. ' : ''?>
    <a href="<?=$this->url('item', array('id' => $item['Item_ID']))?>">
      <?=$this->escapeHtml($this->fixtitle(isset($item['Item_AltName']) && !empty($item['Item_AltName']) ? $item['Item_AltName'] : $item['Item_Name']))?>
    </a><br />
  <? endforeach; ?>
<? endif; ?>

<? if (count($files) > 0): ?>
  <h2>Related Documents</h2>
  <? $type = false; foreach ($files as $file): ?>
    <? if ($type !== $file['File_Type']): $type = $file['File_Type']; ?>
      <h3 class="filetype"><?=$this->escapeHtml($type)?></h3>
    <? endif; ?>
    <p class="file">
      <a target="_new" href="<?=$this->escapeHtml($file['File_Path'])?>">
        <?=$this->escapeHtml($file['File_Name'])?>
      </a>
      <? if (!empty($file['Description'])): ?>
        <br /><?=$file['Description']?>
      <? endif; ?>
    </p>
  <? endforeach; ?>
<? endif; ?>

<? if (count($bibliography) > 0): ?>
  <h2>Bibliography of Items About "<?=$this->escapeHtml($title)?>"</h2>
  <? $type = false; foreach ($bibliography as $bib): ?>
    <? if ($type !== $bib['Material_Type_Plural_Name']): $type = $bib['Material_Type_Plural_Name']; ?>
      <h3 class="materialType"><?=$this->escapeHtml($type)?></h3>
    <? endif; ?>
    <span class="item"><a href="<?=$this->url('item', array('id' => $bib['Item_ID']))?>"><?=$this->fixtitle($bib['Item_Name'])?></a></span><br />
  <? endforeach; ?>
<? endif; ?>

<? if (count($links) > 0): ?>
  <h2>Related Links</h2>
  <? foreach ($links as $link): ?>
    <p class="link">
      <a href="<?=$this->escapeHtml($link['URL'])?>"><?=$this->fixtitle($link['Link_Name'])?></a><br />
      <? if (!empty($link['Description'])): ?><?=$link['Description']?><br /><? endif; ?>
      <span class="url"><?=$this->escapeHtml($link['URL'])?></span>
      (last verified: <?=$this->escapeHtml($link['Date_Checked'])?>)
    </p>
  <? endforeach; ?>
<? endif; ?>

<h2>User Comments</h2>

<? if (count($comments) > 0): ?>
  <? $currentUser = $this->auth()->getIdentity(); ?>
  <? foreach ($comments as $comment): ?>
    <p><?=$comment['Review']?></p>
    <p class="review_signature">--<a href="<?=$this->url('user', array('id' => $comment['User_ID']))?>"><?=$this->escapeHtml($comment['Username'])?></a></p>
  <? endforeach; ?>
<? else: ?>
  <p>No comments available.</p>
<? endif; ?>

<div class="controls">
  <? if ($this->auth()->hasIdentity()): ?>
    <p>
      <a class="button" href="<?=$this->url('series', array('id' => $series['Series_ID'], 'extra' => 'Comment'))?>">
        <?=$userHasComment ? 'Edit Comment' : 'Submit Comment'?>
      </a>
    </p>
  <? else: ?>
    <p>Please <a href="<?=$this->url('login')?>">log in</a> to leave a comment.</p>
  <? endif; ?>
</div>