<?php
    $title = $this->fixtitle($series['Series_Name']);
    $this->layout()->title = 'Series - ' . $title;
    $this->layout()->toggleLink = $this->toggleLink('edit/series', $series['Series_ID']);
?>

<div class="controls top">
  <?php ob_start(); ?>
  <?php if ($this->auth()->hasIdentity()): ?>
    <p>
      <a class="button" href="<?=$this->url('series', ['id' => $series['Series_ID'], 'extra' => 'Comment'])?>">
        <?=$userHasComment ? 'Edit Comment' : 'Submit Comment'?>
      </a>
    </p>
  <?php else: ?>
    <p>Please <a href="<?=$this->url('login')?>">log in</a> to leave a comment.</p>
  <?php endif; ?>
  <?php $controls = ob_get_flush(); ?>
</div>

<p>
  <a href="<?=$this->url('series')?>">[List All Series]</a>
  <a href="<?=$this->url('series', ['id' => $series['Series_ID'], 'extra' => 'FullText'])?>">[List Series Full Text]</a>
  <a href="<?=$this->url('series', ['id' => $series['Series_ID'], 'extra' => 'Images'])?>">[List Series Images]</a>
  <a href="<?=$this->url('series', ['id' => $series['Series_ID'], 'extra' => 'People'])?>">[List Series People]</a>
  <a href="<?=$this->url('series', ['id' => $series['Series_ID'], 'extra' => 'Tags'])?>">[List Series Subjects/Tags]</a>
</p>

<table class="series">
  <tr><th scope="row">Language:</th><td><?=$this->escapeHtml($language['Language_Name'])?></td></tr>

  <?php $altTitleCount = count($altTitles); ?>
  <?php if ($altTitleCount > 0): ?>
    <tr>
      <th scope="row">Alternate Title<?=$altTitleCount > 1 ? 's' : ''?>:</th>
      <td>
        <?php foreach ($altTitles as $altTitle): ?>
          <?=$this->escapeHtml($this->fixtitle($altTitle['Series_AltName']))?>
          <?php if (!empty($altTitle['Note'])): ?>(<?=$this->escapeHtml($altTitle['Note'])?>)<?php endif; ?>
          <br />
        <?php endforeach; ?>
      </td>
    </tr>
  <?php endif; ?>

  <?php $pubCount = count($publishers); ?>
  <?php if ($pubCount > 0): ?>
    <tr>
      <th scope="row">Publisher<?=$pubCount > 1 ? 's' : ''?>:</th>
      <td>
        <?php foreach ($publishers as $publisher): ?>
          <a href="<?=$this->url('publisher', ['id' => $publisher['Publisher_ID']])?>">
            <?=$this->escapeHtml($publisher['Publisher_Name'])?>
          </a>
          <?php if (!empty($publisher['City_Name']) || !empty($publisher['Street'])): ?>
            (<?php
              if (!empty($publisher['City_Name'])) {
                echo '<a href="' . $this->url('city', ['id' => $publisher['City_ID']]) . '">'
                  . $this->escapeHtml($publisher['City_Name']) . '</a>';
                if (!empty($publisher['Street'])) {
                  echo ': ';
                }
              }
              echo $this->escapeHtml($publisher['Street']);
            ?>)
          <?php endif; ?>
          <?php if (!empty($publisher['Imprint_Name'])): ?>
            (<?=$this->escapeHtml($publisher['Imprint_Name'])?> imprint)
          <?php endif; ?>
          <?php if (!empty($publisher['Country_Name'])): ?>
            --
            <a href="<?=$this->url('country', ['id' => $publisher['Country_ID']])?>">
              <?=$this->escapeHtml($publisher['Country_Name'])?>
            </a>
          <?php endif; ?>
          <?php if (!empty($publisher['Note'])): ?>
            (<?=$this->escapeHtml($publisher['Note'])?>)
          <?php endif; ?>
          <br />
        <?php endforeach; ?>
      </td>
    </tr>
  <?php endif; ?>

  <?php $catCount = count($categories); ?>
  <?php if ($catCount > 0): ?>
    <tr>
      <th scope="row"><?=$catCount > 1 ? 'Categories' : 'Category'?>:</th>
      <td>
        <?php foreach ($categories as $category): ?>
          <a href="<?=$this->url('category', ['id' => $category['Category_ID']])?>">
            <?=$this->escapeHtml($category['Category'])?>
          </a><br />
        <?php endforeach; ?>
      </td>
    </tr>
  <?php endif; ?>

  <?php if (count($translatedFrom) > 0): ?>
    <tr>
      <th scope="row">Translated From:</th>
      <td>
        <?php foreach ($translatedFrom as $current): ?>
          <a href="<?=$this->url('series', ['id' => $current['Series_ID']])?>">
            <?=$this->escapeHtml($this->fixtitle($current['Series_Name']))?>
          </a> (<?=$this->escapeHtml($current['Language_Name'])?>)<br />
        <?php endforeach; ?>
      </td>
    </tr>
  <?php endif; ?>

  <?php if (count($translatedInto) > 0): ?>
    <tr>
      <th scope="row">Translated Into:</th>
      <td>
        <?php foreach ($translatedInto as $current): ?>
          <a href="<?=$this->url('series', ['id' => $current['Series_ID']])?>">
            <?=$this->escapeHtml($this->fixtitle($current['Series_Name']))?>
          </a> (<?=$this->escapeHtml($current['Language_Name'])?>)<br />
        <?php endforeach; ?>
      </td>
    </tr>
  <?php endif; ?>

  <?php foreach ($seriesAttributes as $current): ?>
    <tr>
        <th scope="row"><?=$this->escapeHtml($current->Series_Attribute_Name)?>:</th>
        <td>
          <?php if (!empty($current->Value_Link)): ?>
            <a href="<?=$this->escapeHtmlAttr($current->Value_Link)?>">
          <?php endif; ?>
          <?php if ($current->Allow_HTML == 1): ?>
            <?=$current->Series_Attribute_Value?>
          <?php else: ?>
            <?=$this->escapeHtml($current->Series_Attribute_Value)?>
          <?php endif; ?>
          <?php if (!empty($current->Value_Link)): ?>
            </a>
          <?php endif; ?>
        </td>
  <?php endforeach; ?>

  <?php foreach ($this->relationshipsValues as $current): ?>
    <tr>
      <th scope="row"><?=$this->escapeHtml($current['label'])?>:</th>
      <td>
        <?php foreach ($current['values'] as $value): ?>
          <a href="<?=$this->url('series', ['id' => $value['Series_ID']])?>">
            <?=$this->escapeHtml($value['Series_Name'])?>
          </a><br />
        <?php endforeach; ?>
      </td>
    </tr>
  <?php endforeach; ?>
</table>

<?php if (!empty($series['Series_Description'])): ?>
  <p><?=$series['Series_Description']?></p>
<?php endif; ?>

<?php if (count($items) < 1): ?>
  <p>No items listed in this series yet.</p>
<?php else: ?>
  <?php $matType = ''; ?>
  <?php if (!$groupByMaterial): ?><h2>Items</h2><?php endif; ?>
  <?php foreach ($items as $item): ?>
    <?php if ($groupByMaterial && $matType != $item['Material_Type_Plural_Name']): ?>
      <?php $matType = $item['Material_Type_Plural_Name'] ?>
      <h2><?=$this->escapeHtml($matType)?></h2>
    <?php endif; ?>
    <?=$this->escapeHtml($this->formatItemNumber($item))?>
    <a href="<?=$this->url('item', ['id' => $item['Item_ID']])?>">
      <?=$this->escapeHtml($this->fixtitle(isset($item['Item_AltName']) && !empty($item['Item_AltName']) ? $item['Item_AltName'] : $item['Item_Name']))?>
    </a>
    <?php if (!empty($item['Child_Items'])): ?>
      <?php $parts = array_unique(explode('||', $item['Child_Items'])); ?>
      (<i><?=$this->escapeHtml($this->fixtitle($parts[0]))?></i><?php if (count($parts) == 2): ?> and 1 more item<?php elseif (count($parts) > 2): ?> and <?=(count($parts) - 1)?> more items<?php endif;?>)
    <?php endif; ?>
    <br />
  <?php endforeach; ?>
<?php endif; ?>

<?php if (count($files) > 0): ?>
  <h2>Related Documents</h2>
  <?php $type = false; ?>
  <?php foreach ($files as $file): ?>
    <?php if ($type !== $file['File_Type']): $type = $file['File_Type']; ?>
      <h3 class="filetype"><?=$this->escapeHtml($type)?></h3>
    <?php endif; ?>
    <p class="file">
      <a target="_new" href="<?=$this->escapeHtml($file['File_Path'])?>">
        <?=$this->escapeHtml($this->fixtitle($file['File_Name']))?>
      </a>
      <?php if (!empty($file['Description'])): ?>
        <br /><?=$file['Description']?>
      <?php endif; ?>
    </p>
  <?php endforeach; ?>
<?php endif; ?>

<?php if (count($bibliography) > 0): ?>
  <h2>Bibliography of Items About "<?=$this->escapeHtml($title)?>"</h2>
  <?php $type = false; ?>
  <?php foreach ($bibliography as $bib): ?>
    <?php if ($type !== $bib['Material_Type_Plural_Name']): $type = $bib['Material_Type_Plural_Name']; ?>
      <h3 class="materialType"><?=$this->escapeHtml($type)?></h3>
    <?php endif; ?>
    <span class="item"><a href="<?=$this->url('item', ['id' => $bib['Item_ID']])?>"><?=$this->fixtitle($bib['Item_Name'])?></a></span><br />
  <?php endforeach; ?>
<?php endif; ?>

<?php if (count($links) > 0): ?>
  <h2>Related Links</h2>
  <?php foreach ($links as $link): ?>
    <p class="link">
      <a href="<?=$this->escapeHtml($link['URL'])?>"><?=$this->fixtitle($link['Link_Name'])?></a><br />
      <?php if (!empty($link['Description'])): ?><?=$link['Description']?><br /><?php endif; ?>
      <span class="url"><?=$this->escapeHtml($link['URL'])?></span>
      (last verified: <?=$this->escapeHtml($link['Date_Checked'])?>)
    </p>
  <?php endforeach; ?>
<?php endif; ?>

<h2>User Comments</h2>

<?php if (count($comments) > 0): ?>
  <?php $currentUser = $this->auth()->getIdentity(); ?>
  <?php foreach ($comments as $comment): ?>
    <p><?=$comment['Review']?></p>
    <p class="review_signature">--<a href="<?=$this->url('user', ['id' => $comment['User_ID']])?>"><?=$this->escapeHtml($comment['Username'])?></a></p>
  <?php endforeach; ?>
<?php else: ?>
  <p>No comments available.</p>
<?php endif; ?>

<div class="controls bottom"><?=$controls?></div>
