<?php
    $title = $this->fixtitle($series['Series_Name']);
    $this->layout()->title = 'Series Subjects/Tags - ' . $title;
    $lastTag = null;
?>
<?php if (count($tags) < 1): ?>
  <p>No subjects/tags listed for this series.</p>
<?php else: ?>
  <?php foreach ($tags as $i => $current): ?>
    <?php if ($current['Tag'] !== $lastTag): ?>
      <?php $lastTag = $current['Tag']; ?>
      <h2>
        <a href="<?=$this->url('tag', ['id' => $current['Tag_ID']])?>">
          <?=$this->escapeHtml($current['Tag'])?>
        </a>
      </h2>
    <?php endif; ?>
    <a href="<?=$this->url('item', ['id' => $current['Item_ID']])?>">
      <?=$this->escapeHtml($this->fixtitle(isset($current['Item_AltName']) && !empty($current['Item_AltName']) ? $current['Item_AltName'] : $current['Item_Name']))?>
    </a><br />
  <?php endforeach; ?>
<?php endif; ?>
