<?php
    $this->layout()->title = 'Item List By Year';
?>
<?php if (count($items) < 1): ?>
  <p>No items listed in this database yet.</p>
<?php else: ?>
  <?php $currentYear = false; foreach ($items as $current): ?>
    <?php if ($currentYear !== $current['Year']): $currentYear = $current['Year']; ?>
      <h2><?=$this->escapeHtml($current['Year'] == -1 ? 'Never Published' : $current['Year'])?></h2>
    <?php endif; ?>
    <a href="<?=$this->url('item', ['id' => $current['Item_ID']])?>">
      <?=$this->escapeHtml($this->fixtitle(isset($current['Item_AltName']) && !empty($current['Item_AltName']) ? $current['Item_AltName'] : $current['Item_Name']))?>
    </a>
    <?php if (!empty($current['Note'])): ?>
      (<?=$this->escapeHtml($current['Note'])?>)
    <?php endif; ?>
    <br />
  <?php endforeach; ?>
<?php endif; ?>