<?
    $this->headTitle('Choose Series - ');
?>
<h1>Choose Series</h1>

<p class="disclaimer">This item is contained within multiple series; please select one.</p>

<form action="" method="post">
  <select name="series">
    <? foreach ($series as $current): ?>
      <option value="<?=$current['Series_ID']?>">
        <?=$this->escapeHtml($this->fixtitle($current['Series_Name']))?>
      </option>
    <? endforeach; ?>
  </select>
  <input type="submit" value="Submit" />
</form>

<br />