<?php
    $title = $this->fixtitle($item['Item_Name']);
    $this->layout()->title = 'Item - ' . $title;
    $this->layout()->toggleLink = $this->toggleLink('edit/item', $item['Item_ID']);
?>
<div class="row">
  <div class="col-md-12">
    <div class="controls top">
      <?php ob_start(); ?>
      <?php if ($this->auth()->hasIdentity()): ?>
        <p>
          <a class="button" href="<?=$this->url('item', ['id' => $item['Item_ID'], 'extra' => 'Review'])?>">
            <?=$userHasReview ? 'Edit Review' : 'Submit Review'?>
          </a>
          <a class="button" href="<?=$this->url('item', ['id' => $item['Item_ID'], 'extra' => 'EditHave'])?>">
            <?=$userHasItem ? 'Modify Have List' : 'Add to Have List'?>
          </a>
          <a class="button" href="<?=$this->url('item', ['id' => $item['Item_ID'], 'extra' => 'EditWant'])?>">
            <?=$userWantsItem ? 'Modify Want List' : 'Add to Want List'?>
          </a>
          <a class="button" href="<?=$this->url('item', ['id' => $item['Item_ID'], 'extra' => 'EditExtra'])?>">
            <?=$userHasExtraItem ? 'Modify Sale/Trade List' : 'Add to Sale/Trade List'?>
          </a>
        </p>
      <?php else: ?>
        <p>Please <a href="<?=$this->url('login')?>">log in</a> to manage your collection or post a review.</p>
      <?php endif; ?>
      <?php $controls = ob_get_flush(); ?>
    </div>

    <div class="pull-right" style="padding:6px 0;">
      View:
      <div class="btn-group" style="margin-top:-4px;">
        <a href="<?=$this->url('item', ['id' => $item['Item_ID']])?>" class="btn btn-default">Combined</a>
        <a href="" class="btn btn-primary">By Edition</a>
      </div>
    </div>

    <h2>Item-Level Details</h2>
    <table class="item">
      <?php ob_start(); ?>
      <?php $altTitleCount = count($altTitles); ?>
      <?php if ($altTitleCount > 0): ?>
        <tr>
          <th scope="row">Alternate Title<?=$altTitleCount > 1 ? 's' : ''?>:</th>
          <td>
            <?php foreach ($altTitles as $altTitle): ?>
              <?=$this->escapeHtml($this->fixtitle($altTitle['Item_AltName']))?>
              <?php if (!empty($altTitle['Note'])): ?>(<?=$this->escapeHtml($altTitle['Note'])?>)<?php endif; ?>
              <br />
            <?php endforeach; ?>
          </td>
        </tr>
      <?php endif; ?>

      <?php $tagCount = count($tags); ?>
      <?php if ($tagCount > 0): ?>
        <tr>
          <th scope="row">Subject<?=$tagCount > 1 ? 's' : ''?> / Tag<?=$tagCount > 1 ? 's' : ''?>:</th>
          <td>
            <?php foreach ($tags as $tag): ?>
              <a href="<?=$this->url('tag', ['id' => $tag['Tag_ID']])?>"><?=$this->escapeHtml($tag['Tag'])?></a><br />
            <?php endforeach; ?>
          </td>
        </tr>
      <?php endif; ?>

      <?php if (count($containedIn) > 0): ?>
        <tr>
          <th scope="row">Contained In:</th>
          <td>
            <?php foreach ($containedIn as $current): ?>
              <a href="<?=$this->url('item', ['id' => $current['Item_ID']])?>">
                <?=$this->escapeHtml($this->fixtitle($current['Item_Name']))?>
              </a> (<?=$this->escapeHtml($current['Material_Type_Name'])?><?php if (!empty($current['Note'])): ?>, <?=$this->escapeHtml($current['Note'])?><?php endif; ?>)<br />
            <?php endforeach; ?>
          </td>
        </tr>
      <?php endif; ?>

      <?php if (count($contains) > 0): ?>
        <tr>
          <th scope="row">Contains:</th>
          <td>
            <?php foreach ($contains as $current): ?>
              <a href="<?=$this->url('item', ['id' => $current['Item_ID']])?>">
                <?=$this->escapeHtml($this->fixtitle($current['Item_Name']))?>
              </a> (<?=$this->escapeHtml($current['Material_Type_Name'])?><?php if (!empty($current['Note'])): ?>, <?=$this->escapeHtml($current['Note'])?><?php endif; ?>)<br />
            <?php endforeach; ?>
          </td>
        </tr>
      <?php endif; ?>

      <?php if (count($translatedFrom) > 0): ?>
        <tr>
          <th scope="row">Translated From:</th>
          <td>
            <?php foreach ($translatedFrom as $current): ?>
              <a href="<?=$this->url('item', ['id' => $current['Item_ID']])?>">
                <?=$this->escapeHtml($this->fixtitle($current['Item_Name']))?>
              </a> (<?=$this->escapeHtml($current['Language_Name'])?>)<br />
            <?php endforeach; ?>
          </td>
        </tr>
      <?php endif; ?>

      <?php if (count($translatedInto) > 0): ?>
        <tr>
          <th scope="row">Translated Into:</th>
          <td>
            <?php foreach ($translatedInto as $current): ?>
              <a href="<?=$this->url('item', ['id' => $current['Item_ID']])?>">
                <?=$this->escapeHtml($this->fixtitle($current['Item_Name']))?>
              </a> (<?=$this->escapeHtml($current['Language_Name'])?>)<br />
            <?php endforeach; ?>
          </td>
        </tr>
      <?php endif; ?>

      <?php if (count($adaptedFrom) > 0): ?>
        <tr>
          <th scope="row">Adapted From:</th>
          <td>
            <?php foreach ($adaptedFrom as $current): ?>
              <a href="<?=$this->url('item', ['id' => $current['Item_ID']])?>">
                <?=$this->escapeHtml($this->fixtitle($current['Item_Name']))?>
              </a> (<?=$this->escapeHtml($current['Material_Type_Name'])?>)<br />
            <?php endforeach; ?>
          </td>
        </tr>
      <?php endif; ?>

      <?php if (count($adaptedInto) > 0): ?>
        <tr>
          <th scope="row">Adapted Into:</th>
          <td>
            <?php foreach ($adaptedInto as $current): ?>
              <a href="<?=$this->url('item', ['id' => $current['Item_ID']])?>">
                <?=$this->escapeHtml($this->fixtitle($current['Item_Name']))?>
              </a> (<?=$this->escapeHtml($current['Material_Type_Name'])?>)<br />
            <?php endforeach; ?>
          </td>
        </tr>
      <?php endif; ?>

      <?php foreach ($this->relationshipsValues as $current): ?>
        <tr>
          <th scope="row"><?=$this->escapeHtml($current['label'])?>:</th>
          <td>
            <?php foreach ($current['values'] as $value): ?>
              <a href="<?=$this->url('item', ['id' => $value['Item_ID']])?>">
                <?=$this->fixTitle($value['Item_Name'])?>
              </a><br />
            <?php endforeach; ?>
          </td>
        </tr>
      <?php endforeach; ?>

      <?php if (count($descriptions) > 0): ?>
        <?php foreach ($descriptions as $desc): ?>
          <tr>
            <th scope="row"><?=$this->escapeHtml($this->descriptionsource()->getName($desc['Source']))?>:</th>
            <td><?=$desc['Description']?></td>
          </tr>
        <?php endforeach; ?>
      <?php endif; ?>

      <?php foreach ($itemAttributes as $current): ?>
        <tr>
          <th scope="row"><?=$this->escapeHtml($current['Items_Attribute_Name'])?>:</th>
          <td>
            <?php if ($current->Allow_HTML == 1): ?>
              <?=$current->Items_Attribute_Value?><br />
            <?php else: ?>
              <?=$this->escapeHtml($current->Items_Attribute_Value)?><br />
            <?php endif; ?>
          </td>
        </tr>
      <?php endforeach; ?>

      <?php if (count($reviews) > 0): ?>
        <?php foreach ($reviews as $review): ?>
          <tr>
            <th scope="row"><?=$this->escapeHtml($review['Username'])?>'s Thoughts:</th>
            <td>
              <?=$review['Review']?>
              <p>
                <a href="<?=$this->url('user', ['id' => $review['User_ID'], 'action' => 'Reviews'])?>">
                  More reviews by <?=$this->escapeHtml($review['Username'])?>
                </a>
              </p>
            </td>
          </tr>
        <?php endforeach; ?>
      <?php endif; ?>

      <?php if (!empty($item['Item_Errata'])): ?>
        <tr><th scope="row">Errata:</th><td><?=$item['Item_Errata']?></td></tr>
      <?php endif; ?>

      <?php if (!empty($item['Item_Thanks'])): ?>
        <tr><th scope="row">Special Thanks:</th><td><?=$item['Item_Thanks']?></td></tr>
      <?php endif; ?>

      <?php $userHasItem = $userWantsItem = $userHasExtraItem = false; ?>

      <?php if (count($owners) > 0): ?>
        <tr>
          <th scope="row">Users Who Own This Item:</th>
          <td>
            <?php $prevUser = false; ?>
            <?php foreach ($owners as $owner): $separator = $prevUser; ?><?php if ($this->auth()->hasIdentity() && $owner['User_ID'] == $this->auth()->getIdentity()): $userHasItem = true; endif; ?><?php if ($prevUser !== $owner['Username']): $prevUser = $owner['Username'];?><?php if ($separator): ?>, <?php endif; ?><a href="<?=$this->url('user', ['id' => $owner['User_ID'], 'action' => 'Collection'])?>"><?=$this->escapeHtml($prevUser)?></a><?php endif; ?><?php if (!empty($owner['Collection_Note'])): ?> (<?=$this->escapeHtml($owner['Collection_Note'])?>)<?php endif; ?><?php endforeach; ?>
          </td>
        </tr>
      <?php endif; ?>

      <?php if (count($buyers) > 0): ?>
        <tr>
          <th scope="row">Users Who Want This Item:</th>
          <td>
            <?php $prevUser = false; ?>
            <?php foreach ($buyers as $buyer): $separator = $prevUser; ?><?php if ($this->auth()->hasIdentity() && $buyer['User_ID'] == $this->auth()->getIdentity()): $userWantsItem = true; endif; ?><?php if ($prevUser !== $buyer['Username']): $prevUser = $buyer['Username'];?><?php if ($separator): ?>, <?php endif; ?><a href="<?=$this->url('user', ['id' => $buyer['User_ID'], 'action' => 'Collection'])?>"><?=$this->escapeHtml($prevUser)?></a><?php endif; ?><?php if (!empty($buyer['Collection_Note'])): ?> (<?=$this->escapeHtml($buyer['Collection_Note'])?>)<?php endif; ?><?php endforeach; ?>
          </td>
        </tr>
      <?php endif; ?>

      <?php if (count($sellers) > 0): ?>
        <tr>
          <th scope="row">Users with Extra Copies:</th>
          <td>
            <?php $prevUser = false; ?>
            <?php foreach ($sellers as $seller): $separator = $prevUser; ?>
              <?php if ($this->auth()->hasIdentity() && $seller['User_ID'] == $this->auth()->getIdentity()): $userHasExtraItem = true; endif; ?>
              <?php if ($prevUser !== $seller['Username']): $prevUser = $seller['Username'];?>
                <?php if ($separator): ?><br /><?php endif; ?>
                <a href="<?=$this->url('user', ['id' => $seller['User_ID'], 'action' => 'Extras'])?>">
                  <?=$this->escapeHtml($prevUser)?>
                </a>
              <?php endif; ?>
              <?php if (!empty($seller['Collection_Note'])): ?> - <?=$this->escapeHtml($seller['Collection_Note'])?><?php endif; ?>
            <?php endforeach; ?>
          </td>
        </tr>
      <?php endif; ?>

      <?php $table_contents = ob_get_contents(); ?>
      <?php ob_end_clean(); ?>
      <?=strlen(trim($table_contents)) > 0 ? $table_contents : 'No information available.' ?>
    </table>
  </div>
</div>

<?php foreach ($editions as $edition): ?>
  <?=$this->showEdition($edition['Edition_ID'])?>
<?php endforeach; ?>

<div class="controls bottom"><?=$controls?></div>

<?php if (count($files) > 0): ?>
  <h2>Related Documents</h2>
  <?php $type = false; ?>
  <?php foreach ($files as $file): ?>
    <?php if ($type !== $file['File_Type']): $type = $file['File_Type']; ?>
      <h3 class="filetype"><?=$this->escapeHtml($type)?></h3>
    <?php endif; ?>
    <p class="file">
      <a target="_new" href="<?=$this->escapeHtml($file['File_Path'])?>">
        <?=$this->escapeHtml($file['File_Name'])?>
      </a>
      <?php if (!empty($file['Description'])): ?>
        <br /><?=$file['Description']?>
      <?php endif; ?>
    </p>
  <?php endforeach; ?>
<?php endif; ?>

<?php if (count($bibliography) > 0): ?>
  <h2>Bibliography of Items About "<?=$this->escapeHtml($title)?>"</h2>
  <?php $type = false; ?>
  <?php foreach ($bibliography as $bib): ?>
    <?php if ($type !== $bib['Material_Type_Plural_Name']): $type = $bib['Material_Type_Plural_Name']; ?>
      <h3 class="materialType"><?=$this->escapeHtml($type)?></h3>
    <?php endif; ?>
    <span class="item"><a href="<?=$this->url('item', ['id' => $bib['Item_ID']])?>"><?=$this->fixtitle($bib['Item_Name'])?></a></span><br />
  <?php endforeach; ?>
<?php endif; ?>

<?php if (count($links) > 0): ?>
  <h2>Related Links</h2>
  <?php foreach ($links as $link): ?>
    <p class="link">
      <a href="<?=$this->escapeHtml($link['URL'])?>"><?=$this->fixtitle($link['Link_Name'])?></a><br />
      <?php if (!empty($link['Description'])): ?><?=$link['Description']?><br /><?php endif; ?>
      <span class="url"><?=$this->escapeHtml($link['URL'])?></span>
      (last verified: <?=$this->escapeHtml($link['Date_Checked'])?>)
    </p>
  <?php endforeach; ?>
<?php endif; ?>