<?php
$this->layout()->title = 'Items with Full Text'
?>
<?php if ($fuzzy): ?>
  <p>Showing fuzzy matches; switch to <a href="?fuzzy=0&source=<?=(int)$source?>">exact matches</a> to only show links where the online text exactly matches the listed edition.</p>
<?php else: ?>
  <p>Showing exact matches; switch to <a href="?fuzzy=1&source=<?=(int)$source?>">fuzzy matches</a> to add links to listings where online text comes from a different edition.</p>
<?php endif; ?>

<form action="<?=$this->url(isset($series) ? 'series' : 'items', ['extra' => 'FullText'] + (isset($series) ? ['id' => $series['Series_ID']] : []))?>" method="GET">
  <input type="hidden" name="fuzzy" value="<?=$fuzzy ? 1 : 0?>" />
  <label class="normal">Showing <?=count($fulltext)?> result<?php if (count($fulltext) > 1): ?>s<?php endif; ?> from:
    <select name="source">
      <option value="">All Sources</option>
      <?php foreach ($sources as $current): ?>
        <option value="<?=$current['Full_Text_Source_ID']?>"<?php if ((int)$source === (int)$current['Full_Text_Source_ID']): ?> selected="selected"<?php endif; ?>>
          <?=$this->escapeHtml($current['Full_Text_Source_Name'])?>
        </option>
      <?php endforeach; ?>
    </select>
  </label>
  <input type="submit" value="Change" />
</form>

<?php if (count($fulltext) > 0): ?>
  <?php $series = false;
    foreach ($fulltext as $current): ?>
    <?php if ($series !== $current['Series_ID']): $series = $current['Series_ID']; ?>
      <h2 class="series"><a href="<?=$this->url('series', ['id' => $series])?>">
        <?=$this->fixtitle($current['Series_Name']);?>
      </a></h2>
    <?php endif; ?>
    <span class="item">
      <?=$this->escapeHtml($this->formatItemNumber($current))?>
      <a href="<?=$this->url('item', ['id' => $current['Item_ID']])?>">
        <?=$this->escapeHtml($this->fixtitle(isset($current['Item_AltName']) && !empty($current['Item_AltName']) ? $current['Item_AltName'] : $current['Item_Name']))?>
      </a>
      <?php if (!empty($current['Child_Items'])): ?>
        <?php $parts = array_unique(explode('||', $current['Child_Items'])); ?>
        (<i><?=$this->escapeHtml($this->fixtitle($parts[0]))?></i><?php if (count($parts) == 2): ?> and 1 more item<?php elseif (count($parts) > 2): ?> and <?=(count($parts) - 1)?> more items<?php endif;?>)
      <?php endif; ?>
      <br />
    </span>
  <?php endforeach; ?>
<?php else: ?>
  <p>No full text listed.</p>
<?php endif; ?>
