<?
    $this->layout()->title = 'Items with Full Text'
?>
<? if ($fuzzy): ?>
  <p>Showing fuzzy matches; switch to <a href="?fuzzy=0">exact matches</a> to only show links where the online text exactly matches the listed edition.</p>
<? else: ?>
  <p>Showing exact matches; switch to <a href="?fuzzy=1">fuzzy matches</a> to add links to listings where online text comes from a different edition.</p>
<? endif; ?>

<form action="<?=$this->url(isset($series) ? 'series' : 'items', array('extra' => 'FullText') + (isset($series) ? array('id' => $series['Series_ID']) : array()))?>" method="GET">
  Showing results from:
  <input type="hidden" name="fuzzy" value="<?=$fuzzy ? 1 : 0?>" />
  <select name="source">
    <option value="">All Sources</option>
    <? foreach ($sources as $current): ?>
      <option value="<?=$current['Full_Text_Source_ID']?>"<? if ((int)$source === (int)$current['Full_Text_Source_ID']): ?> selected="selected"<? endif; ?>>
        <?=$this->escapeHtml($current['Full_Text_Source_Name'])?>
      </option>
    <? endforeach; ?>
  </select>
  <input type="submit" value="Change" />
</form>

<? if (count($fulltext) > 0): ?>
  <? $series = false; foreach ($fulltext as $current): ?>
    <? if ($series !== $current['Series_ID']): $series = $current['Series_ID']; ?>
      <h2 class="series"><a href="<?=$this->url('series', array('id' => $series))?>">
        <?=$this->fixtitle($current['Series_Name']);?>
      </a></h2>
    <? endif; ?>
    <span class="item">
      <?=$this->escapeHtml($this->formatItemNumber($current))?>
      <a href="<?=$this->url('item', array('id' => $current['Item_ID']))?>">
        <?=$this->escapeHtml($this->fixtitle(isset($current['Item_AltName']) && !empty($current['Item_AltName']) ? $current['Item_AltName'] : $current['Item_Name']))?>
      </a>
      <? if (!empty($current['Child_Items'])): ?>
        <? $parts = array_unique(explode('||', $current['Child_Items'])); ?>
        (<i><?=$this->escapeHtml($this->fixtitle($parts[0]))?></i><? if (count($parts) == 2): ?> and 1 more item<? elseif (count($parts) > 2): ?> and <?=(count($parts) - 1)?> more items<?endif ;?>)
      <? endif; ?>
      <br />
    </span>
  <? endforeach; ?>
<? else: ?>
  <p>No full text listed.</p>
<? endif; ?>
