<?
    $title = $this->fixtitle($item['Item_Name']);
    $this->headTitle('Item - ' . $title . ' - ');
?>
<h1><?=$this->escapeHtml($title)?></h1>
<? $role = false; foreach ($credits as $credit): ?>
  <? if ($role !== $credit['Role_Name']): $role = $credit['Role_Name']; ?>
    <h2><?=$this->escapeHtml($role)?></h2>
  <? endif; ?>
  <a href="<?=$this->url('person', array('id' => $credit['Person_ID']))?>">
    <?=$this->showperson($credit)?>
  </a>
  <? if (!empty($credit['Note'])): ?> (<?=$this->escapeHtml($credit['Note'])?>)<? endif; ?>
  <br />
<? endforeach; ?>