<?
    $title = $this->fixtitle($item['Item_Name']);
    $this->headTitle('Item - ' . $title . ' - ');
?>
<h1><?=$this->escapeHtml($title)?></h1>

<? if (count($images) > 0): ?>
  <? foreach ($images as $image): ?>
    <table class="image">
      <tr><td align="center"><a target="_new" href="<?=$this->escapeHtml($image['Image_Path'])?>"><img src="<?=$this->escapeHtml($image['Thumb_Path'])?>" /></a></td></tr>
      <? if (!empty($image['Note'])): ?>
        <tr><td align="center">(<?=$this->escapeHtml($image['Note'])?>)</td></tr>
      <? endif; ?>
    </table>
  <? endforeach; ?>
  <div style="clear: left;"><!-- empty --></div>
<? endif; ?>

<table class="item">
  <? if (count($series) > 0): ?>
    <tr>
      <th>Series:</th>
      <td>
        <? foreach ($series as $current): ?>
          <a href="<?=$this->url('series', array('id' => $current['Series_ID']))?>">
            <?=$this->escapeHtml($this->fixtitle($current['Series_Name']))?>
          </a>
          <? if ($current['Position'] > 0): ?>
            #<?=$this->escapeHtml($current['Position'])?>
          <? endif; ?>
          <br />
        <? endforeach; ?>
      </td>
    </tr>
  <? endif; ?>
  <? $altTitleCount = count($altTitles); if ($altTitleCount > 0): ?>
    <tr>
      <th>Alternate Title<?=$altTitleCount > 1 ? 's' : ''?>:</th>
      <td>
        <? foreach ($altTitles as $altTitle): ?>
          <?=$this->escapeHtml($this->fixtitle($altTitle['Item_AltName']))?>
          <? if (!empty($altTitle['Note'])): ?>(<?=$this->escapeHtml($altTitle['Note'])?>)<? endif; ?>
          <br />
        <? endforeach; ?>
      </td>
    </tr>
  <? endif; ?>

  <?
    if (count($credits) > 0) {
      $groupedCredits = array();
      foreach ($credits as $credit) {
        if (!isset($groupedCredits[$credit['Role_Name']])) {
          $groupedCredits[$credit['Role_Name']] = array();
        }
        $groupedCredits[$credit['Role_Name']][] = $credit;
      }
    } else {
      $groupedCredits = array();
    }
  ?>

  <? if (count($groupedCredits) > 0): ?>
    <? foreach ($groupedCredits as $role => $group): ?>
      <tr>
        <th><?=$this->escapeHtml($role) . (count($group) == 1 ? '' : 's') ?>:</th>
        <td>
          <? foreach ($group as $credit): ?>
            <a href="<?=$this->url('person', array('id' => $credit['Person_ID']))?>">
              <?=$this->showperson($credit)?>
            </a>
            <? if (!empty($credit['Note'])): ?> (<?=$this->escapeHtml($credit['Note'])?>)<? endif; ?>
            <br />
          <? endforeach; ?>
        </td>
      </tr>
    <? endforeach; ?>
  <? endif; ?>

</table>