<?php
$title = 'ISBN Details';
$this->layout()->title = $title;
?>
<?php if (!$isbn->isValid()): ?>
  <p>Invalid ISBN!</p>
<?php else: ?>
  <?php if (empty($config)): ?>
    <p>No links available.</p>
  <?php else: ?>
    <?php foreach ($config as $section => $details): ?>
      <h2><?=$this->escapeHtml($section)?></h2>
      <?php if (!empty($details['description'])): ?><p><?=$details['description']?></p><?php endif; ?>
      <p>
        <?php foreach ($details['links'] as $label => $url): ?>
          <a href="<?=$this->escapeHtml(str_replace('%isbn10%', $isbn->get10(), $url))?>"><?=$this->escapeHtml($label)?></a><br />
        <?php endforeach; ?>
    <?php endforeach ?>
  <?php endif; ?>
<?php endif; ?>