<?
    $this->layout()->title = 'Item List';
?>
<? if (count($items) < 1): ?>
  <p>No items listed in this database yet.</p>
<? else: ?>
  <? $currentLetter = false; foreach ($items as $current): ?>
    <? $first = $this->firstletter($current['Item_Name']); if ($currentLetter !== $first): $currentLetter = $first; ?>
      <h2><?=$this->escapeHtml($currentLetter)?></h2>
    <? endif; ?>
    <a href="<?=$this->url('item', array('id' => $current['Item_ID']))?>">
      <?=$this->escapeHtml($this->fixtitle($current['Item_Name']))?>
    </a><br />
  <? endforeach; ?>
<? endif; ?>