<?php
$this->layout()->title = 'Most Recently Added Items';
$pageCount = count($paginator);
?>
<?php if ($pageCount < 1): ?>
  <p>No items listed in this database yet.</p>
<?php else: ?>
  <p>Viewing page <?=$paginator->getCurrentPageNumber()?> of <?=$pageCount?></p>
  <?php foreach ($paginator as $current): ?>
    <a href="<?=$this->url('item', ['id' => $current['Item_ID']])?>">
      <?=$this->escapeHtml($this->fixtitle($current['Item_Name']))?>
    </a><br />
  <?php endforeach; ?>
  <p><?=$this->paginationControl($paginator, null, 'partials/pagination.phtml')?></p>
<?php endif; ?>