<?
    $this->layout()->title = 'Items with Reviews';
?>

<? if (count($reviews) > 0): ?>
  <? $series = false; foreach ($reviews as $review): ?>
    <? if ($series !== $review['Series_ID']): $series = $review['Series_ID']; ?>
      <? $item = false; ?>
      <h2 class="series"><a href="<?=$this->url('series', array('id' => $series))?>">
        <?=$this->fixtitle($review['Series_Name']);?>
      </a></h2>
    <? endif; ?>
    <? if ($item !== $review['Item_ID']): ?>
      <? $item = $review['Item_ID']; ?>
      <span class="item">
        <?=$this->escapeHtml($this->formatItemNumber($review))?>
        <a href="<?=$this->url('item', array('id' => $review['Item_ID']))?>">
          <?=$this->escapeHtml($this->fixtitle(isset($review['Item_AltName']) && !empty($review['Item_AltName']) ? $review['Item_AltName'] : $review['Item_Name']))?>
        </a>
        <br />
      </span>
    <? endif; ?>
  <? endforeach; ?>
<? else: ?>
  <p>No reviews listed.</p>
<? endif; ?>
