<?
    $this->headTitle('Edit Review - ');
?>
<h1>Edit Review</h1>

<? if (!empty($review)): ?>
  <p class="disclaimer">You have already reviewed this item.  You can make changes
  to the text below and resubmit it, but if you do so, it will
  temporarily disappear from the site until your changes are
  approved.  Sorry for any inconvenience!</p>
<? endif; ?>

<form action="" method="post">
  <h2>Review of <?=$this->escapeHtml($this->fixtitle($item['Item_Name']))?>:</h2>
  <textarea name="Review" rows="15" cols="80"><?=$this->escapeHtml($review)?></textarea><br />
  <input type="submit" value="Submit Review" />
</form>

<h2>Important Notes:</h2>
<ul>
  <li>You may use HTML in your review.</li>
  <li>
    By submitting this review, you are giving permission to
    post it on this site under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/deed.en_US">Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License</a>.
    You retain copyright, however, and may use
    it elsewhere however you see fit.  You may not post 
    reviews to which you do not hold the copyright.
  </li>
  <li>
    Your review will be edited for spelling and grammar and may be rejected if it
    does not provide enough depth.  Please do not be insulted by a 
    rejection, and feel free to use the contact link below if you would like 
    to discuss the situation.
  </li>
</ul>