<?php
    $title = $this->fixtitle($item['Item_Name']);
    $this->layout()->title = 'Item - ' . $title;
    $this->layout()->toggleLink = $this->toggleLink('edit/item', $item['Item_ID']);
    $editionViewLink = $this->url('item', ['id' => $item['Item_ID'], 'extra' => 'Editions']);

    // If there are too many images to display comfortably, pick a smaller number
    // and set a flag to display a link to edition view, where everything is visible.
    // We'll try to pick at least one image for each distinct label, to the greatest
    // extent possible.
    $imageLimit = 12;
    $maxPerGroup = 3;
    $truncatedImages = false;
    if (count($images) > $imageLimit) {
      $sortedImages = [];
      foreach ($images as $image) {
        $sortedImages[$image['Edition_Name']][] = $image;
      }
      $remainingGroups = count($sortedImages);
      $newImages = [];
      foreach ($sortedImages as $name => $contents) {
        $remainingGroups--;
        foreach ($contents as $posInGroup => $current) {
          if (count($newImages) + $remainingGroups < $imageLimit
            && $posInGroup < $maxPerGroup
          ) {
            $newImages[] = $current;
          } else {
            break;
          }
        }
      }
      $images = $newImages;
      $truncatedImages = true;
    }
?>
<div class="row">
  <div class="col-md-12">
    <div class="controls top">
      <?php ob_start(); ?>
      <?php if ($this->auth()->hasIdentity()): ?>
        <p>
          <a class="button" href="<?=$this->url('item', ['id' => $item['Item_ID'], 'extra' => 'Review'])?>">
            <?=$userHasReview ? 'Edit Review' : 'Submit Review'?>
          </a>
          <a class="button" href="<?=$this->url('item', ['id' => $item['Item_ID'], 'extra' => 'EditHave'])?>">
            <?=$userHasItem ? 'Modify Have List' : 'Add to Have List'?>
          </a>
          <a class="button" href="<?=$this->url('item', ['id' => $item['Item_ID'], 'extra' => 'EditWant'])?>">
            <?=$userWantsItem ? 'Modify Want List' : 'Add to Want List'?>
          </a>
          <a class="button" href="<?=$this->url('item', ['id' => $item['Item_ID'], 'extra' => 'EditExtra'])?>">
            <?=$userHasExtraItem ? 'Modify Sale/Trade List' : 'Add to Sale/Trade List'?>
          </a>
        </p>
      <?php else: ?>
        <p>Please <a href="<?=$this->url('login')?>">log in</a> to manage your collection or post a review.</p>
      <?php endif; ?>
      <?php $controls = ob_get_flush(); ?>
    </div>
  </div>
  <?=$this->render('partials/images.phtml', compact('images', 'editions'))?>
  <?php if ($truncatedImages): ?>
    <div class="col-md-12">
      To see more images, switch to
      <a href="<?=$editionViewLink?>">Edition View</a>.
    </div>
  <?php endif; ?>
  <div class="col-md-<?=count($images) > 0 ? 10 : 12?>">
    <div class="pull-right" style="padding:6px 0;">
      View:
      <div class="btn-group" style="margin-top:-4px;">
        <a href="" class="btn btn-primary">Combined</a>
        <a href="<?=$editionViewLink?>" class="btn btn-default">By Edition</a>
      </div>
    </div>
    <?php if (count($editions) > 1): ?><h2>Combined Summary</h2><?php endif; ?>
    <table class="item">
      <?php if (count($fullText) > 0): ?>
        <tr>
          <th scope="row">Online Full Text:</th>
          <td>
            <?php $fullTextCount = count($fullText); ?>
            <?php $previousFullTextName = $skippedFullText = false; ?>
            <?php foreach ($fullText as $current): ?>
              <?php if ($fullTextCount > 6 && $current['Edition_Name'] == $previousFullTextName): ?>
                <?php $skippedFullText = true; ?>
              <?php else: ?>
                <a href="<?=$this->escapeHtml($current['Full_Text_URL'])?>">
                  <?=$this->escapeHtml($current['Full_Text_Source_Name'])?>
                  <?php if (count($editions) > 1): ?>
                    (<?=$this->escapeHtml($this->fixtitle($current['Edition_Name']))?>)
                  <?php endif; ?>
                </a>
                <?php
                  $attrHtml = [];
                  if (count($fullTextAttributes[$current['Sequence_ID']] ?? []) > 0) {
                    foreach ($fullTextAttributes[$current['Sequence_ID']] as $attr) {
                      $attrValue = $attr['Allow_HTML']
                        ? $attr['Editions_Full_Text_Attribute_Value']
                        : $this->escapeHtml($attr['Editions_Full_Text_Attribute_Value']);
                      $attrHtml[] = '<b>'
                        . $this->escapeHtml($attr['Editions_Full_Text_Attribute_Name'])
                        . ':</b> '
                        . $attrValue;
                    }
                    echo '(' . implode('; ', $attrHtml) . ')';
                  }
                ?>
                <br />
              <?php endif; ?>
              <?php $previousFullTextName = $current['Edition_Name'] ?>
            <?php endforeach; ?>
            <?php if ($skippedFullText): ?>
              <i>To see all <?=$fullTextCount?> full text links, switch to
              <a href="<?=$editionViewLink?>">Edition View</a>.</i>
            <?php endif; ?>
          </td>
        </tr>
      <?php endif; ?>
      <?php if (count($series) > 0): ?>
        <tr>
          <th scope="row">Series:</th>
          <td>
            <?php
              // If a series has a numbered entry AND an unnumbered entry, we don't want to
              // display the unnumbered version, since it adds no useful information and
              // reduces readability. Let's index the data so we can identify rows to skip:
              $seriesHasDetails = $rowHasDetails = [];
              foreach ($series as $i => $current) {
                $rowHasDetails[$i] = $current['Parent_Volume'] > 0
                  || $current['Parent_Position'] > 0
                  || $current['Parent_Replacement_Number'] > 0 || $current['Volume'] > 0
                  || $current['Position'] > 0 || $current['Replacement_Number'] > 0;
                if ($rowHasDetails[$i]) {
                  $seriesHasDetails[$current['Series_ID']] = true;
                }
              }
            ?>
            <?php foreach ($series as $i => $current): ?>
              <?php
                // Skip unnumbered rows if a numbered row exists for the same series (using
                // indexes created above):
                if (($seriesHasDetails[$current['Series_ID']] ?? false) && !$rowHasDetails[$i]) {
                  continue;
                }
              ?>
              <a href="<?=$this->url('series', ['id' => $current['Series_ID']])?>">
                <?=$this->escapeHtml($this->fixtitle(empty($current['Series_AltName']) ? $current['Series_Name'] : $current['Series_AltName']))?>
              </a>
              <?php if ($current['Parent_Volume'] > 0 || $current['Parent_Position'] > 0 || $current['Parent_Replacement_Number'] > 0): ?>
                &mdash; <a href="<?=$this->url('item', ['id' => $current['Parent_Item_ID']])?>">
                  <?php if ($current['Parent_Volume'] > 0): ?>
                    v. <?=$this->escapeHtml($current['Parent_Volume'])?>
                  <?php endif; ?>
                  <?php if ($current['Parent_Position'] > 0): ?>
                    no. <?=$this->escapeHtml($current['Parent_Position'])?>
                  <?php endif; ?>
                  <?php if ($current['Parent_Replacement_Number'] > 0): ?>
                    (replacement title no. <?=$this->escapeHtml($current['Parent_Replacement_Number'])?>)
                  <?php endif; ?>
                </a>
                <?php if (!empty($current['Extent_In_Parent'])): ?>
                  &mdash; <?=$this->escapeHtml($current['Extent_In_Parent'])?>
                <?php endif; ?>
              <?php else: ?>
                <?php if ($current['Volume'] > 0 || $current['Position'] > 0 || $current['Replacement_Number'] > 0): ?>
                  &mdash;
                <?php endif; ?>
                <?php if ($current['Volume'] > 0): ?>
                  v. <?=$this->escapeHtml($current['Volume'])?>
                <?php endif; ?>
                <?php if ($current['Position'] > 0): ?>
                  no. <?=$this->escapeHtml($current['Position'])?>
                <?php endif; ?>
                <?php if ($current['Replacement_Number'] > 0): ?>
                  (replacement title no. <?=$this->escapeHtml($current['Replacement_Number'])?>)
                <?php endif; ?>
              <?php endif; ?>
              <br />
            <?php endforeach; ?>
          </td>
        </tr>
      <?php endif; ?>
      <?php $altTitleCount = count($altTitles); if ($altTitleCount > 0): ?>
        <tr>
          <th scope="row">Alternate Title<?=$altTitleCount > 1 ? 's' : ''?>:</th>
          <td>
            <?php foreach ($altTitles as $altTitle): ?>
              <?=$this->escapeHtml($this->fixtitle($altTitle['Item_AltName']))?>
              <?php if (!empty($altTitle['Note'])): ?>(<?=$this->escapeHtml($altTitle['Note'])?>)<?php endif; ?>
              <br />
            <?php endforeach; ?>
          </td>
        </tr>
      <?php endif; ?>

      <?php $platforms = $this->groupeditions($platforms, 'Platform', $editions, 'Platform_ID'); $platformCount = count($platforms); if ($platformCount > 0): ?>
        <tr>
          <th scope="row">Platform<?=$platformCount > 1 ? 's' : ''?>:</th>
          <td>
            <?php foreach ($platforms as $platform => $note): ?>
              <?php list($platId, $platName) = explode('|', $platform, 2); ?>
              <a href="<?=$this->url('platform', ['id' => $platId])?>"><?=$this->escapeHtml($platName)?></a>
              <?=!empty($note) ? '(' . $this->escapeHtml($note) . ')' : ''?>
              <br />
            <?php endforeach; ?>
          </td>
        </tr>
      <?php endif; ?>

      <?php $tagCount = count($tags); if ($tagCount > 0): ?>
        <tr>
          <th scope="row">Subject<?=$tagCount > 1 ? 's' : ''?> / Tag<?=$tagCount > 1 ? 's' : ''?>:</th>
          <td>
            <?php foreach ($tags as $tag): ?>
              <a href="<?=$this->url('tag', ['id' => $tag['Tag_ID']])?>"><?=$this->escapeHtml($tag['Tag'])?></a><br />
            <?php endforeach; ?>
          </td>
        </tr>
      <?php endif; ?>

      <?php if (count($containedIn) > 0): ?>
        <tr>
          <th scope="row">Contained In:</th>
          <td>
            <?php foreach ($containedIn as $current): ?>
              <a href="<?=$this->url('item', ['id' => $current['Item_ID']])?>">
                <?=$this->escapeHtml($this->fixtitle($current['Item_Name']))?>
              </a> (<?=$this->escapeHtml($current['Material_Type_Name'])?><?php if (!empty($current['Note'])): ?>, <?=$this->escapeHtml($current['Note'])?><?php endif; ?>)<br />
            <?php endforeach; ?>
          </td>
        </tr>
      <?php endif; ?>

      <?php if (count($contains) > 0): ?>
        <tr>
          <th scope="row">Contains:</th>
          <td>
            <?php foreach ($contains as $current): ?>
              <a href="<?=$this->url('item', ['id' => $current['Item_ID']])?>">
                <?=$this->escapeHtml($this->fixtitle($current['Item_Name']))?>
              </a> (<?=$this->escapeHtml($current['Material_Type_Name'])?><?php if (!empty($current['Note'])): ?>, <?=$this->escapeHtml($current['Note'])?><?php endif; ?>)<br />
            <?php endforeach; ?>
          </td>
        </tr>
      <?php endif; ?>

      <?php if (count($editions) < 2 && count($parents) > 0): // only display if edition info is hidden; otherwise, redundant. ?>
        <tr>
          <th scope="row">Part of:</th>
          <td>
            <?php foreach ($parents as $current): ?>
              <a href="<?=$this->url('item', ['id' => $current['Item_ID']])?>">
                <?=$this->escapeHtml($this->fixtitle(empty($current['Item_AltName']) ? $current['Item_Name'] : $current['Item_AltName']))?>
              </a> (<?=$this->escapeHtml($current['Material_Type_Name'])?>)<br />
            <?php endforeach; ?>
          </td>
        </tr>
      <?php endif; ?>

      <?php if (count($children) > 0): ?>
        <tr>
          <th scope="row">Contents:</th>
          <td>
            <?php $childEditionNames = []; $contentsByEdition = []; ?>
            <?php foreach ($children as $current) {
                $childEditionNames[$current['Edition_ID']] = $current['Edition_Name'];
                if (!isset($contentsByEdition[$current['Edition_ID']])) {
                  $contentsByEdition[$current['Edition_ID']] = '';
                }
                $contentsByEdition[$current['Edition_ID']] .=
                  '<a href="' . $this->url('item', ['id' => $current['Item_ID']]) . '">'
                  . $this->escapeHtml($this->fixtitle(empty($current['Item_AltName']) ? $current['Item_Name'] : $current['Item_AltName']))
                  . '</a> (' . $this->escapeHtml($current['Material_Type_Name'])
                  . (!empty($current['Extent_In_Parent']) ? ', ' . $this->escapeHtml($current['Extent_In_Parent']) : '')
                  . ')<br />';
              }
              $i = 0; $diffs = false; $old = ''; $full = '';
              foreach ($contentsByEdition as $id => $contents) {
                $i++;
                if ($i > 1 && $contents != $old) {
                  $diffs = true;
                }
                $old = $contents;
                if (!empty($full)) {
                  $full .= '<br />';
                }
                $full .= '<i>' . $this->escapeHtml($childEditionNames[$id]) . ':</i><br />' . $contents;
              }
            ?>
            <?=$diffs ? $full : $contents?>
          </td>
        </tr>
      <?php endif; ?>

      <?php if (count($translatedFrom) > 0): ?>
        <tr>
          <th scope="row">Translated From:</th>
          <td>
            <?php foreach ($translatedFrom as $current): ?>
              <a href="<?=$this->url('item', ['id' => $current['Item_ID']])?>">
                <?=$this->escapeHtml($this->fixtitle($current['Item_Name']))?>
              </a>
              <?php if (!empty($current['Language_Name'])):?>
                (<?=$this->escapeHtml($current['Language_Name'])?>)
              <?php endif; ?><br />
            <?php endforeach; ?>
          </td>
        </tr>
      <?php endif; ?>

      <?php if (count($translatedInto) > 0): ?>
        <tr>
          <th scope="row">Translated Into:</th>
          <td>
            <?php foreach ($translatedInto as $current): ?>
              <a href="<?=$this->url('item', ['id' => $current['Item_ID']])?>">
                <?=$this->escapeHtml($this->fixtitle($current['Item_Name']))?>
              </a> (<?=$this->escapeHtml($current['Language_Name'])?>)<br />
            <?php endforeach; ?>
          </td>
        </tr>
      <?php endif; ?>

      <?php if (count($adaptedFrom) > 0): ?>
        <tr>
          <th scope="row">Adapted From:</th>
          <td>
            <?php foreach ($adaptedFrom as $current): ?>
              <a href="<?=$this->url('item', ['id' => $current['Item_ID']])?>">
                <?=$this->escapeHtml($this->fixtitle($current['Item_Name']))?>
              </a> (<?=$this->escapeHtml($current['Material_Type_Name'])?>)<br />
            <?php endforeach; ?>
          </td>
        </tr>
      <?php endif; ?>

      <?php if (count($adaptedInto) > 0): ?>
        <tr>
          <th scope="row">Adapted Into:</th>
          <td>
            <?php foreach ($adaptedInto as $current): ?>
              <a href="<?=$this->url('item', ['id' => $current['Item_ID']])?>">
                <?=$this->escapeHtml($this->fixtitle($current['Item_Name']))?>
              </a> (<?=$this->escapeHtml($current['Material_Type_Name'])?>)<br />
            <?php endforeach; ?>
          </td>
        </tr>
      <?php endif; ?>

      <?php foreach ($this->relationshipsValues as $current): ?>
        <tr>
          <th scope="row"><?=$this->escapeHtml($current['label'])?>:</th>
          <td>
            <?php foreach ($current['values'] as $value): ?>
              <a href="<?=$this->url('item', ['id' => $value['Item_ID']])?>">
                <?=$this->fixTitle($value['Item_Name'])?>
              </a><br />
            <?php endforeach; ?>
          </td>
        </tr>
      <?php endforeach; ?>

      <?php foreach ($this->analyzeCredits($creators, $credits, $editions) as $current): ?>
        <?php $role = $current['role']; $citation = $current['citation']; $group = $current['data']; ?>
        <tr>
          <th scope="row">
            <?=$this->escapeHtml($role) . (count($group) == 1 ? '' : 's')
                . (empty($citation) ? '' : ' (according to ' . $citation . ')')
            ?>:
          </th>
          <td>
            <?php foreach ($group as $person => $details): ?>
              <a href="<?=$this->url('person', ['id' => $person])?>">
                <?=$this->showperson($details['person'])?>
              </a>
              <?php $realNameCount = count($details['realPerson']); if ($realNameCount > 0): ?>
                (pseudonym used by <?=$realNameCount == 1 ? '<a href="' . $this->url('person', ['id' => $details['realPerson'][0]['Person_ID']]) . '">' . $this->showperson($details['realPerson'][0]) . '</a>' : 'multiple people' ?>)
              <?php endif; ?>
              <?php if (!empty($details['notes'])): ?>(<?=$this->escapeHtml($details['notes'])?>)<?php endif; ?><br />
            <?php endforeach; ?>
          </td>
        </tr>
      <?php endforeach; ?>

      <?php $dateCount = count($dates); if ($dateCount > 0): ?>
        <tr>
          <th scope="row">Date<?=$dateCount > 1 ? 's' : ''?>:</th>
          <td>
            <?php foreach ($dates as $date): ?>
              <?=$this->escapeHtml($this->formatReleaseDate($date, count($editions) > 1))?><br />
            <?php endforeach; ?>
          </td>
        </tr>
      <?php endif; ?>

      <?php $isbns = $this->groupeditions($isbns, 'ISBN13', $editions); $isbnCount = count($isbns); if ($isbnCount > 0): ?>
        <tr>
          <th scope="row">ISBN<?=$isbnCount > 1 ? 's' : ''?>:</th>
          <td>
            <?php foreach ($isbns as $isbn => $note): ?>
              <a href="<?=$this->url('item', ['id' => $item['Item_ID'], 'action' => 'ISBNDetails', 'extra' => $isbn])?>">
                <?php $isbnConverter = new \VuFindCode\ISBN($isbn); $isbn10 = $isbnConverter->get10(); ?>
                <?=$this->escapeHtml(!empty($isbn10) ? $isbn10 . ' / ' . $isbn : $isbn)?>
              </a>
              <?=!empty($note) ? '(' . $this->escapeHtml($note) . ')' : ''?>
              <br />
            <?php endforeach; ?>
          </td>
        </tr>
      <?php endif; ?>

      <?php $pubCount = count($publishers); if ($pubCount > 0): ?>
        <tr>
          <th scope="row">Publisher<?=$pubCount > 1 ? 's' : ''?>:</th>
          <td>
            <?php $pubLines = []; foreach ($publishers as $publisher): ob_start(); ?>
              <?php if (count($editions) > 1): ?>
                <?=$this->escapeHtml($this->fixTitle($publisher['Edition_Name']))?>:
              <?php endif; ?>
              <a href="<?=$this->url('publisher', ['id' => $publisher['Publisher_ID']])?>">
                <?=$this->escapeHtml($publisher['Publisher_Name'])?>
              </a>
              <?php if (!empty($publisher['City_Name']) || !empty($publisher['Street'])): ?>
                (<?php
                  if (!empty($publisher['City_Name'])) {
                    echo '<a href="' . $this->url('city', ['id' => $publisher['City_ID']]) . '">'
                      . $this->escapeHtml($publisher['City_Name']) . '</a>';
                    if (!empty($publisher['Street'])) {
                      echo ': ';
                    }
                  }
                  echo $this->escapeHtml($publisher['Street']);
                ?>)
              <?php endif; ?>
              <?php if (!empty($publisher['Imprint_Name'])): ?>
                (<?=$this->escapeHtml($publisher['Imprint_Name'])?> imprint)
              <?php endif; ?>
              <?php if (!empty($publisher['Country_Name'])): ?>
                --
                <a href="<?=$this->url('country', ['id' => $publisher['Country_ID']])?>">
                  <?=$this->escapeHtml($publisher['Country_Name'])?>
                </a>
              <?php endif; ?>
              <?php if (!empty($publisher['Note'])): ?>
                (<?=$this->escapeHtml($publisher['Note'])?>)
              <?php endif; ?>
              <br />
              <?php $pubLines[] = ob_get_clean(); ?>
            <?php endforeach; ?>
            <?=implode('', array_unique($pubLines))?>
          </td>
        </tr>
      <?php endif; ?>

      <?php $oclcNumbers = $this->groupeditions($oclcNumbers, 'OCLC_Number', $editions); $oclcCount = count($oclcNumbers); if ($oclcCount > 0): ?>
        <tr>
          <th scope="row">OCLC Number<?=$oclcCount > 1 ? 's' : ''?>:</th>
          <td>
            <?php foreach ($oclcNumbers as $number => $note): ?>
              <?=$this->escapeHtml($number)?>
              <?=!empty($note) ? '(' . $this->escapeHtml($note) . ')' : ''?>
              <br />
            <?php endforeach; ?>
          </td>
        </tr>
      <?php endif; ?>

      <?php $codes = $this->groupeditions($codes, 'Product_Code', $editions); $codeCount = count($codes); if ($codeCount > 0): ?>
        <tr>
          <th scope="row">Product Code<?=$codeCount > 1 ? 's' : ''?>:</th>
          <td>
            <?php foreach ($codes as $code => $note): ?>
              <?=$this->escapeHtml($code)?>
              <?=!empty($note) ? '(' . $this->escapeHtml($note) . ')' : ''?>
              <br />
            <?php endforeach; ?>
          </td>
        </tr>
      <?php endif; ?>

      <?php
        $lengths = $endings = [];
        $descCount = 0;
        foreach ($editions as $ed) {
            $name = $this->fixtitle($ed['Edition_Name']);
            if (!empty($ed['Edition_Length'])) {
                if (!isset($lengths[$ed['Edition_Length']])) {
                    $lengths[$ed['Edition_Length']] = [];
                }
                $lengths[$ed['Edition_Length']][] = $name;
            }
            if (!empty($ed['Edition_Endings'])) {
                if (!isset($endings[$ed['Edition_Endings']])) {
                    $endings[$ed['Edition_Endings']] = [];
                }
                $endings[$ed['Edition_Endings']][] = $name;
            }
            if (!empty($ed['Edition_Description'])) {
                $descCount++;
            }
        }
      ?>

      <?php if ($descCount > 0): ?>
        <tr><th scope="row">Edition Description<?=$descCount > 1 ? 's' : ''?>:</th><td>
          <?php $displayedCount = 0; foreach ($editions as $ed): ?>
            <?php if (!empty($ed['Edition_Description'])): $displayedCount++; ?>
              <?php if ($displayedCount > 1): ?><br /><?php endif; ?>
              <?php if (count($editions) > 1): ?>
                <i><?=$this->escapeHtml($this->fixtitle($ed['Edition_Name']))?><?php if (empty($ed['Item_Name'])): ?>:<?php endif; ?></i>
                <?php if (!empty($ed['Item_Name'])): ?>
                  (<?=!empty($ed['Extent_In_Parent']) ? $this->escapeHtml($ed['Extent_In_Parent']) . ' ' : ''?>in <a href="<?=$this->url('item', ['id' => $ed['Item_ID']])?>"><?=$this->escapeHtml($this->fixtitle(empty($ed['Item_AltName']) ? $ed['Item_Name'] : $ed['Item_AltName']))?></a>):
                <?php endif; ?>
                <br />
              <?php endif; ?>
              <?=$ed['Edition_Description']?><br />
            <?php endif; ?>
          <?php endforeach; ?>
        </td></tr>
      <?php endif; ?>

      <?php if (!empty($lengths)): ?>
        <tr><th scope="row">Length:</th><td>
          <?php foreach ($lengths as $length => $editionNames): ?>
            <?=$this->escapeHtml($length)?>
            <?php if (count($editionNames) != count($editions) && count($editions) > 1): ?>
              (<?=$this->escapeHtml(implode(', ', $editionNames))?>)
            <?php endif; ?>
            <br />
          <?php endforeach; ?>
        </td></tr>
      <?php endif; ?>

      <?php if (!empty($endings)): ?>
        <tr><th scope="row">Number of Endings:</th><td>
          <?php foreach ($endings as $ending => $editionNames): ?>
            <?=$this->escapeHtml($ending)?>
            <?php if (count($editionNames) != count($editions) && count($editions) > 1): ?>
              (<?=$this->escapeHtml(implode(', ', $editionNames))?>)
            <?php endif; ?>
            <br />
          <?php endforeach; ?>
        </td></tr>
      <?php endif; ?>

      <?php foreach ($itemAttributes as $current): ?>
        <tr>
          <th scope="row"><?=$this->escapeHtml($current['Items_Attribute_Name'])?>:</th>
          <td>
            <?php if ($current->Allow_HTML == 1): ?>
              <?=$current->Items_Attribute_Value?><br />
            <?php else: ?>
              <?=$this->escapeHtml($current->Items_Attribute_Value)?><br />
            <?php endif; ?>
          </td>
        </tr>
      <?php endforeach; ?>

      <?php
        $groupedAttribs = [];
        foreach ($editionAttributes as $current) {
            $groupedAttribs[$current['Editions_Attribute_Name']][] = $current;
        }
        foreach ($groupedAttribs as $key => $values) {
            $groupedAttribs[$key] = [
              'details' => $values[0],
              'values' => $this->groupeditions($values, 'Editions_Attribute_Value', $editions)
            ];
        }
      ?>
      <?php foreach ($groupedAttribs as $label => $current): ?>
        <tr>
          <th scope="row"><?=$this->escapeHtml($label)?>:</th>
          <td>
            <?php foreach ($current['values'] as $value => $note): ?>
              <?php if ($current['details']->Allow_HTML == 1): ?>
                <?php if (!empty($note)): ?><i><?=$this->escapeHtml($note)?>:</i><br /><?php endif; ?>
                <?=$value?><br />
              <?php else: ?>
                <?=$this->escapeHtml($value)?> <?php if (!empty($note)):?>(<?=$this->escapeHtml($note)?>)<?php endif; ?><br />
              <?php endif; ?>
            <?php endforeach; ?>
          </td>
      <?php endforeach; ?>

      <?php if (count($descriptions) > 0): ?>
        <?php foreach ($descriptions as $desc): ?>
          <tr>
            <th scope="row"><?=$this->escapeHtml($this->descriptionsource()->getName($desc['Source']))?>:</th>
            <td><?=$desc['Description']?></td>
          </tr>
        <?php endforeach; ?>
      <?php endif; ?>

      <?php if (count($reviews) > 0): ?>
        <?php foreach ($reviews as $review): ?>
          <tr>
            <th scope="row"><?=$this->escapeHtml($review['Username'])?>'s Thoughts:</th>
            <td>
              <?=substr(trim($review['Review']), 0, 3) === '<p>' ? '' : '<p>'?>
              <?=$review['Review']?>
              <p>
                <a href="<?=$this->url('user', ['id' => $review['User_ID'], 'action' => 'Reviews'])?>">
                  More reviews by <?=$this->escapeHtml($review['Username'])?>
                </a>
              </p>
            </td>
          </tr>
        <?php endforeach; ?>
      <?php endif; ?>

      <?php if (!empty($item['Item_Errata'])): ?>
        <tr><th scope="row">Errata:</th><td><?=$item['Item_Errata']?></td></tr>
      <?php endif; ?>

      <?php if (!empty($item['Item_Thanks'])): ?>
        <tr><th scope="row">Special Thanks:</th><td><?=$item['Item_Thanks']?></td></tr>
      <?php endif; ?>

      <?php $userHasItem = $userWantsItem = $userHasExtraItem = false; ?>

      <?php if (count($owners) > 0): ?>
        <tr>
          <th scope="row">Users Who Own This Item:</th>
          <td>
            <?php $prevUser = false; foreach ($owners as $owner): $separator = $prevUser; ?><?php if ($this->auth()->hasIdentity() && $owner['User_ID'] == $this->auth()->getIdentity()): $userHasItem = true; endif; ?><?php if ($prevUser !== $owner['Username']): $prevUser = $owner['Username'];?><?php if ($separator): ?>, <?php endif; ?><a href="<?=$this->url('user', ['id' => $owner['User_ID'], 'action' => 'Collection'])?>"><?=$this->escapeHtml($prevUser)?></a><?php endif; ?><?php if (!empty($owner['Collection_Note'])): ?> (<?=$this->escapeHtml($owner['Collection_Note'])?>)<?php endif; ?><?php endforeach; ?>
          </td>
        </tr>
      <?php endif; ?>

      <?php if (count($buyers) > 0): ?>
        <tr>
          <th scope="row">Users Who Want This Item:</th>
          <td>
            <?php $prevUser = false; foreach ($buyers as $buyer): $separator = $prevUser; ?><?php if ($this->auth()->hasIdentity() && $buyer['User_ID'] == $this->auth()->getIdentity()): $userWantsItem = true; endif; ?><?php if ($prevUser !== $buyer['Username']): $prevUser = $buyer['Username'];?><?php if ($separator): ?>, <?php endif; ?><a href="<?=$this->url('user', ['id' => $buyer['User_ID'], 'action' => 'Collection'])?>"><?=$this->escapeHtml($prevUser)?></a><?php endif; ?><?php if (!empty($buyer['Collection_Note'])): ?> (<?=$this->escapeHtml($buyer['Collection_Note'])?>)<?php endif; ?><?php endforeach; ?>
          </td>
        </tr>
      <?php endif; ?>

      <?php if (count($sellers) > 0): ?>
        <tr>
          <th scope="row">Users with Extra Copies:</th>
          <td>
            <?php $prevUser = false; foreach ($sellers as $seller): $separator = $prevUser; ?>
              <?php if ($this->auth()->hasIdentity() && $seller['User_ID'] == $this->auth()->getIdentity()): $userHasExtraItem = true; endif; ?>
              <?php if ($prevUser !== $seller['Username']): $prevUser = $seller['Username'];?>
                <?php if ($separator): ?><br /><?php endif; ?>
                <a href="<?=$this->url('user', ['id' => $seller['User_ID'], 'action' => 'Extras'])?>">
                  <?=$this->escapeHtml($prevUser)?>
                </a>
              <?php endif; ?>
              <?php if (!empty($seller['Collection_Note'])): ?> - <?=$this->escapeHtml($seller['Collection_Note'])?><?php endif; ?>
            <?php endforeach; ?>
          </td>
        </tr>
      <?php endif; ?>
    </table>
  </div>
</div>

<?php if (count($editions) > 1): ?>
  <h2>Known Editions</h2>
  <?php foreach ($editions as $edition): ?>
    <a href="<?=$this->url('edition', ['id' => $edition['Edition_ID']])?>">
        <?=$this->escapeHtml($this->fixtitle($edition['Edition_Name']))?>
    </a>
    <?php if (!empty($edition['Item_Name'])): ?>(<?=!empty($edition['Extent_In_Parent']) ? $this->escapeHtml($edition['Extent_In_Parent']) . ' ' : ''?>in <a href="<?=$this->url('item', ['id' => $edition['Parent_Item_ID'] ?? $edition['Item_ID']])?>"><?=$this->escapeHtml($this->fixtitle(empty($edition['Item_AltName']) ? $edition['Item_Name'] : $edition['Item_AltName']))?></a>)<?php endif; ?>
    <br />
  <?php endforeach; ?>
<?php endif; ?>

<div class="controls bottom"><?=$controls?></div>

<?php if (count($files) > 0): ?>
  <h2>Related Documents</h2>
  <?php $type = false; foreach ($files as $file): ?>
    <?php if ($type !== $file['File_Type']): $type = $file['File_Type']; ?>
      <h3 class="filetype"><?=$this->escapeHtml($type)?></h3>
    <?php endif; ?>
    <p class="file">
      <a target="_new" href="<?=$this->escapeHtml($file['File_Path'])?>">
        <?=$this->escapeHtml($this->fixtitle($file['File_Name']))?>
      </a>
      <?php if (!empty($file['Description'])): ?>
        <br /><?=$file['Description']?>
      <?php endif; ?>
    </p>
  <?php endforeach; ?>
<?php endif; ?>

<?php if (count($bibliography) > 0): ?>
  <h2>Bibliography of Items About "<?=$this->escapeHtml($title)?>"</h2>
  <?php $type = false; foreach ($bibliography as $bib): ?>
    <?php if ($type !== $bib['Material_Type_Plural_Name']): $type = $bib['Material_Type_Plural_Name']; ?>
      <h3 class="materialType"><?=$this->escapeHtml($type)?></h3>
    <?php endif; ?>
    <span class="item"><a href="<?=$this->url('item', ['id' => $bib['Item_ID']])?>"><?=$this->fixtitle($bib['Item_Name'])?></a></span><br />
  <?php endforeach; ?>
<?php endif; ?>

<?php if (count($links) > 0): ?>
  <h2>Related Links</h2>
  <?php foreach ($links as $link): ?>
    <p class="link">
      <a href="<?=$this->escapeHtml($link['URL'])?>"><?=$this->fixtitle($link['Link_Name'])?></a><br />
      <?php if (!empty($link['Description'])): ?><?=$link['Description']?><br /><?php endif; ?>
      <span class="url"><?=$this->escapeHtml($link['URL'])?></span>
      (last verified: <?=$this->escapeHtml($link['Date_Checked'])?>)
    </p>
  <?php endforeach; ?>
<?php endif; ?>
