<?php
    $title = $platform['Platform'];
    $this->layout()->title = 'Platform - ' . $title;
    $displayedSomething = false;
?>
<?php if (count($items) > 0): $displayedSomething = true; ?>
  <?php $series = false;
  foreach ($items as $credit): ?>
    <?php if ($series !== $credit['Series_ID']): $series = $credit['Series_ID']; ?>
      <h2 class="series"><a href="<?=$this->url('series', ['id' => $series])?>">
        <?=$this->fixtitle($credit['Series_Name']);?>
      </a></h2>
    <?php endif; ?>
    <span class="item">
      <?=$this->escapeHtml($this->formatItemNumber($credit))?>
      <a href="<?=$this->url('item', ['id' => $credit['Item_ID']])?>">
        <?=$this->fixtitle($credit['Item_Name'])?>
      </a>
      <br />
    </span>
  <?php endforeach; ?>
<?php endif; ?>

<?php if (!$displayedSomething): ?>
  <p>No information is available about this platform.</p>
<?php endif; ?>