<?
    $title = $platform['Platform'];
    $this->headTitle('Platform - ' . $title . ' - ');
    $displayedSomething = false;
?>
<h1><?=$this->escapeHtml($title)?></h1>

<? if (count($items) > 0): $displayedSomething = true; ?>
  <? $series = false; foreach ($items as $credit): ?>
    <? if ($series !== $credit['Series_Name']): $series = $credit['Series_Name']; ?>
      <h2 class="series"><a href="<?=$this->url('series', array('id' => $credit['Series_ID']))?>">
        <?=$this->fixtitle($series);?>
      </a></h2>
    <? endif; ?>
    <span class="item">
      <?=$credit['Position'] > 0 ? $this->escapeHtml($credit['Position']) . '. ' : ''?>
      <a href="<?=$this->url('item', array('id' => $credit['Item_ID']))?>">
        <?=$this->fixtitle($credit['Item_Name'])?>
      </a>
      <br />
    </span>
  <? endforeach; ?>
<? endif; ?>

<? if (!$displayedSomething): ?>
  <p>No information is available about this platform.</p>
<? endif; ?>