<?php
    $this->layout()->title = 'Platform List';
?>
<?php if (count($platforms) < 1): ?>
  <p>No platforms listed in this database yet.</p>
<?php else: ?>
  <h2>
    <?=$this->firstLetterMenu($platforms, 'Platform'); ?>
  </h2>
  <?php $currentLetter = false; ?>
  <?php foreach ($platforms as $i => $current): ?>
    <?php $first = $this->firstletter($current['Platform']); ?>
    <?php if ($currentLetter !== $first): $currentLetter = $first; ?>
      <?php if ($i > 0): ?>
        <a name="<?=$this->escapeHtml($currentLetter)?>"/>
        <h2><?=$this->escapeHtml($currentLetter)?><a href="#" style="float:right">Back to Top &uarr;</a></h2>
      <?php endif; ?>
    <?php endif; ?>
    <a href="<?=$this->url('platform', ['id' => $current['Platform_ID']])?>">
      <?=$this->escapeHtml($this->fixtitle($current['Platform']))?>
    </a><br />
  <?php endforeach; ?>
<?php endif; ?>