<?
    $this->layout()->title = 'Platform List';
?>
<? if (count($platforms) < 1): ?>
  <p>No platforms listed in this database yet.</p>
<? else: ?>
  <? $currentLetter = false; foreach ($platforms as $current): ?>
    <? $first = $this->firstletter($current['Platform']); if ($currentLetter !== $first): $currentLetter = $first; ?>
      <h2><?=$this->escapeHtml($currentLetter)?></h2>
    <? endif; ?>
    <a href="<?=$this->url('platform', array('id' => $current['Platform_ID']))?>">
      <?=$this->escapeHtml($this->fixtitle($current['Platform']))?>
    </a><br />
  <? endforeach; ?>
<? endif; ?>