<div id="editForm">
  <input type="hidden" id="Category_ID" value="<?=$this->escapeHtml($category['Category_ID'])?>" />
  <table class="edit">
    <tr>
      <th>Category:</th>
      <td><input type="text" id="Category" value="<?=$this->escapeHtml($category['Category'] ?? '')?>" /></td>
    </tr>
    <tr>
      <th>Description:</th>
      <td><textarea id="Description"><?=$this->escapeHtml($category['Description'] ?? '')?></textarea></td>
    </tr>
  </table>
  <button id="save_category" onclick="Category.save();">Save</button>
  <div id="save_category_status"></div>
</div>
