<form id="editForm" onsubmit="Category.save(); return false;">
  <input type="hidden" id="Category_ID" value="<?=$this->escapeHtml($category['Category_ID'])?>" />
  <table class="edit">
    <tr>
      <th scope="row"><label for="Category_Name">Category:</label></th>
      <td><input type="text" id="Category_Name" value="<?=$this->escapeHtml($category['Category'] ?? '')?>" /></td>
    </tr>
    <tr>
      <th scope="row"><label for="Description">Description:</label></th>
      <td><textarea id="Description"><?=$this->escapeHtml($category['Description'] ?? '')?></textarea></td>
    </tr>
  </table>
  <input type="submit" value="Save" />
  <div id="save_category_status"></div>
</form>
