<?
    $title = $category['Category'];
    $this->layout()->title = 'Category - ' . $title;
    $displayedSomething = false;
?>
<? if (!empty($category['Description'])): ?>
  <p><?=$category['Description']?></p>
<? endif; ?>

<? if (count($series) < 1): ?>
  <p>No series are listed in this category.</p>
<? else: ?>
  <? $currentLetter = false; foreach ($series as $current): ?>
    <? $first = $this->firstletter($current['Series_Name']); if ($currentLetter !== $first): $currentLetter = $first; ?>
      <h2><?=$this->escapeHtml($currentLetter)?></h2>
    <? endif; ?>
    <a href="<?=$this->url('series', array('id' => $current['Series_ID']))?>">
      <?=$this->escapeHtml($this->fixtitle($current['Series_Name']))?>
    </a><br />
  <? endforeach; ?>
<? endif; ?>