<?php
    $title = $category['Category'];
    $this->layout()->title = 'Category - ' . $title;
    $displayedSomething = false;
?>
<?php if (!empty($category['Description'])): ?>
  <p><?=$category['Description']?></p>
<?php endif; ?>

<?php if (count($series) < 1): ?>
  <p>No series are listed in this category.</p>
<?php else: ?>
  <h2>
    <?=$this->firstLetterMenu($series, 'Series_Name'); ?>
  </h2>
  <?php $currentLetter = false; foreach ($series as $i => $current): ?>
    <?php $first = $this->firstletter($current['Series_Name']); ?>
    <?php if ($currentLetter !== $first): $currentLetter = $first; ?>
      <?php if ($i > 0): ?>
        <h2><?=$this->escapeHtml($currentLetter)?><a href="#" style="float:right">Back to Top &uarr;</a></h2>
      <?php endif; ?>
    <?php endif; ?>
    <a href="<?=$this->url('series', ['id' => $current['Series_ID']])?>">
      <?=$this->escapeHtml($this->fixtitle($current['Series_Name']))?>
    </a><br />
  <?php endforeach; ?>
<?php endif; ?>