<?
    $this->layout()->title = 'Category List';
?>
<? if (count($categories) < 1): ?>
  <p>No categories listed in this database yet.</p>
<? else: ?>
  <h2>
    <?=$this->firstLetterMenu($categories, 'Category'); ?>
  </h2>
  <? $currentLetter = false; foreach ($categories as $i=>$current): ?>
    <? $first = $this->firstletter($current['Category']); if ($currentLetter !== $first): $currentLetter = $first; ?>
      <? if ($i > 0): ?>
        <a name="<?=$this->escapeHtml($currentLetter)?>"/>
        <h2><?=$this->escapeHtml($currentLetter)?><a href="#" style="float:right">Back to Top &uarr;</a></h2>
      <? endif ?>
    <? endif; ?>
    <a href="<?=$this->url('category', array('id' => $current['Category_ID']))?>">
      <?=$this->escapeHtml($this->fixtitle($current['Category']))?>
    </a><br />
  <? endforeach; ?>
<? endif; ?>