<?php
    $this->layout()->title = 'Category List';
?>
<?php if (count($categories) < 1): ?>
  <p>No categories listed in this database yet.</p>
<?php else: ?>
  <h2>
    <?=$this->firstLetterMenu($categories, 'Category'); ?>
  </h2>
  <?php $currentLetter = false; foreach ($categories as $i => $current): ?>
    <?php $first = $this->firstletter($current['Category']); if ($currentLetter !== $first): $currentLetter = $first; ?>
      <?php if ($i > 0): ?>
        <a name="<?=$this->escapeHtml($currentLetter)?>"/>
        <h2><?=$this->escapeHtml($currentLetter)?><a href="#" style="float:right">Back to Top &uarr;</a></h2>
      <?php endif ?>
    <?php endif; ?>
    <a href="<?=$this->url('category', ['id' => $current['Category_ID']])?>">
      <?=$this->escapeHtml($this->fixtitle($current['Category']))?>
    </a><br />
  <?php endforeach; ?>
<?php endif; ?>