<?php $this->layout()->title = 'Hierarchy Migration' ?>

<?php if (count($details) == 0): ?>
  <p>No hierarchies found.</p>
<?php else: ?>
  <form method="post">
    <?php foreach ($details as $item): ?>
      <label>
      <input type="checkbox" name="items[]" value="<?=$item['Item_ID']?>" />
      <?=$this->escapeHtml($item['Item_Name'])?>
      </label>
      <br />
    <?php endforeach; ?>
    <input type="submit" value="Submit" />
  </form>
<?php endif; ?>