<?php $this->layout()->title = 'Hierarchy Migration' ?>

<?php if (empty($details)): ?>
  <p>No hierarchies found.</p>
<?php else: ?>
  <form method="post">
    <?php foreach ($details as $item): ?>
      <input type="checkbox" name="items[]" value="<?=$item['Item_ID']?>" />
      <?=$this->escapeHtml($item['Item_Name'])?><br />
    <?php endforeach; ?>
    <input type="submit" />
  </form>
<?php endif; ?>