<? $this->layout()->title = 'Credits' ?>

<p>While this project owes its existence to the labors of Edward T. LeBlanc, it would also not be possible without the
effort of a team of workers who have entered data, researched anomalies and corrected errors. Here are the participants,
past and present, in alphabetical order by last name:</p>

<ul>
  <li>Caitlin Berner</li>
  <li>Michael Foight</li>
  <li>Scott Grapin</li>
  <li>Deidre Johnson</li>
  <li>Demian Katz</li>
  <li>James D. Keeline</li>
  <li><a href="http://lovecraftismissing.com">Larry Latham</a></li>
  <li>Kyunghyun Lee</li>
  <li>Ruth Martin</li>
  <li>Daniel Michel</li>
  <li>Bill Robinson</li>
  <li>Matthew Short</li>
  <li>Kelly Wiles</li>
  <li>Alexander Williams</li>
  <li>John R. Williams</li>
  <li>Rachel Yerger</li>
</ul>