<?php $this->layout()->title = 'Credits' ?>

<p>While this project owes its existence to the labors of Edward T. LeBlanc, it would also not be possible without the
effort of a team of workers who have entered data, researched anomalies and corrected errors. Here are the participants,
past and present, in alphabetical order by last name:</p>

<div class="two-columns">
  <ul>
    <li>Beaudry Allen</li>
    <li>Jacob Ballmaier</li>
    <li>Caitlin Berner</li>
    <li>Brenna Bychowski</li>
    <li>Leigh Clark</li>
    <li>Alison Dolbier</li>
    <li>Thomas Dorrance</li>
    <li>David Edwards</li>
    <li>Allison Floray</li>
    <li>Michael Foight</li>
    <li>Scott Grapin</li>
    <li>Matthew Gray</li>
    <li>Melanie Griffin</li>
    <li>Marjorie Haines</li>
    <li>Samantha Hunter</li>
    <li>Deidre Johnson</li>
    <li>Demian Katz</li>
    <li>James D. Keeline</li>
    <li>Michelle Kung</li>
    <li>Kyle Lampasona</li>
    <li>Christian Lash</li>
    <li>Larry Latham</li>
    <li>Kyunghyun Lee</li>
    <li>Christine Leonard</li>
    <li>Sarah Marcinik</li>
    <li>Ruth Martin</li>
    <li>Amanda McCollom</li>
    <li>Tad McGuire</li>
    <li>Daniel Michel</li>
    <li>Maura O'Neill</li>
    <li>Sue Ottignon</li>
    <li>Rebecca Oviedo</li>
    <li>Roshini Panicker</li>
    <li>Roberta Pierce</li>
    <li>Emma Poley</li>
    <li>Taylor Prahar-Ryals</li>
    <li>Sata Prescott</li>
    <li>Bill Robinson</li>
    <li>Christoforos Panagiotis Sassaris</li>
    <li>Amanda Schaefer</li>
    <li>Geoff Scholl</li>
    <li>Courtney Schultz</li>
    <li>Danielle Sens-Castet</li>
    <li>Mike Sgier</li>
    <li>Matthew Short</li>
    <li>Kayla Margery Smith</li>
    <li>Kayla Van Osten</li>
    <li>Kelly Wiles</li>
    <li>Alexander Williams</li>
    <li>John R. Williams</li>
    <li>Rachel Yerger</li>
  </ul>
</div>

<hr/>

<p>The following students from Northern Illinois University have contributed reviews as part of their coursework, listed in alphabetical order by last name:</p>

<div class="two-columns">
  <ul>
    <li>Michael Besonen</li>
    <li>James L. Bowman</li>
    <li>Jon Bunte</li>
    <li>Jaemee Cordero</li>
    <li>Riley Coules</li>
    <li>Claire Culton</li>
    <li>Kat Fiste</li>
    <li>Amy Freeman</li>
    <li>Robin Grooms</li>
    <li>Nathan Haffey</li>
    <li>Zain Haq</li>
    <li>Joshua Heinlein</li>
    <li>Madison Hill</li>
    <li>Riquia Hill</li>
    <li>Veronica LeRoy</li>
    <li>Jacquelin Marrero</li>
    <li>Joshua Maurice</li>
    <li>Tracy Osimowicz</li>
    <li>Natalie Santiago</li>
    <li>Leticia Zepeda</li>
  </ul>
</div>
