<? $this->layout()->title = 'Credits' ?>

<p>While this project owes its existence to the labors of Edward T. LeBlanc, it would also not be possible without the
effort of a team of workers who have entered data, researched anomalies and corrected errors. Here are the participants,
past and present, in alphabetical order by last name:</p>

<div class="two-columns">
  <ul>
    <li>Caitlin Berner</li>
    <li>Brenna Bychowski</li>
    <li>Leigh Clark</li>
    <li>Alison Dolbier</li>
    <li>Michael Foight</li>
    <li>Scott Grapin</li>
    <li>Melanie Griffin</li>
    <li>Marjorie Haines</li>
    <li>Samantha Hunter</li>
    <li>Deidre Johnson</li>
    <li>Demian Katz</li>
    <li>James D. Keeline</li>
    <li>Michelle Kung</li>
    <li>Kyle Lampasona</li>
    <li>Christian Lash</li>
    <li>Larry Latham</li>
    <li>Kyunghyun Lee</li>
    <li>Sarah Marcinik</li>
    <li>Ruth Martin</li>
    <li>Daniel Michel</li>
    <li>Maura O'Neill</li>
    <li>Sue Ottignon</li>
    <li>Emma Poley</li>
    <li>Bill Robinson</li>
    <li>Courtney Schultz</li>
    <li>Matthew Short</li>
    <li>Kayla Van Osten</li>
    <li>Kelly Wiles</li>
    <li>Alexander Williams</li>
    <li>John R. Williams</li>
    <li>Rachel Yerger</li>
  </ul>
</div>
