<? $this->headTitle('About - '); ?>
<h1>About the Project</h1>

<h2>What is the Dime Novel Bibliography?</h2>

<p>The Dime Novel Bibliography project aims to create a comprehensive online database of dime novels, story papers,
reprint libraries and related materials.  This is currently a <b>work in progress</b>.</p>

<h2>Who was Edward T. LeBlanc?</h2>

<p>Edward T. LeBlanc was the editor of <a href="http://www.readseries.com/dnru.html">Dime Novel Round-Up</a> from
1952 to 1994, and he devoted most of his life to compiling extensive lists of dime novels and related materials.
With the permission of the LeBlanc family, we are using his research as a foundation for this project, while also
incorporating information from various other sources.</p>

<h2>How can I help?</h2>

There are many ways you can help with the project:

<ul>
  <li>Contribute corrections and additions.</li>
  <li>Contribute cover images.</li>
  <li>Submit reviews and collection lists.</li>
  <li>Volunteer to help with data entry.</li>
</ul>

If you are interested in getting involved in these or other ways, please contact
<a href="mailto:demian.katz@villanova.edu">Demian Katz</a> for more details.