<?php $this->layout()->title = 'About the Project' ?>

<div style="background: #F3E3C6; padding: 14px; float: right; margin: -3px -15px 5px 10px; text-align: center;">
<a href="<?=$this->url('home')?>images/leblanc.jpg"><img width="293" height="400" src="<?=$this->url('home')?>images/leblanc-thumb.jpg" /></a><br />
<i>Photograph courtesy of Jacqueline LeBlanc.</i>
</div>

<h2>What is the Dime Novel Bibliography?</h2>

<p>The Dime Novel Bibliography project aims to create a comprehensive online database of dime novels, story papers,
reprint libraries and related materials.  This is currently a <b>work in progress</b>.</p>

<h2>What is a Dime Novel?</h2>

<p>For an overview of dime novels and other popular literature, see the <a href="http://exhibits.library.villanova.edu/dime-novels">Paper for the People</a>
online exhibit at Villanova University's Falvey Memorial Library.</p>

<h2>Who was Edward T. LeBlanc?</h2>

<p>Edward T. LeBlanc was the editor of <a href="http://www.readseries.com/dnru.html">Dime Novel Round-Up</a> from
1952 to 1994, and he devoted many years of his life to compiling <a href="http://digital.library.villanova.edu/Collection/vudl:283769">extensive
lists</a> of dime novels and related materials.  With the permission of the LeBlanc family, we are using his research as a foundation
for this project, while also incorporating information from various other sources.</p>

<h2>How much work has been completed?</h2>

<p>See the <a href="<?=$this->url('about-progress')?>">Progress Report</a> page.</p>

<h2>How accurate is the data?</h2>

<p>LeBlanc built his bibliographies from a variety of sources. While actual copies of the books were his first authorities, there are
many titles that he never saw. Thus, his listings also had to rely on publisher advertising, secondary sources, and notes from other
collectors. This means that some of the data here may be speculative in nature, and it is very likely that some of the listings are
"phantoms" that never actually existed. As in any large data set, there is also likely some small percentage of error in transcription,
etc.</p>

<p>This site is designed to be a guide and a discovery tool to help find more data and explore relationships between books and authors;
it is not necessarily intended to be a final authority on every detail of every book. For the reasons listed above, additional
fact-checking may sometimes be necessary. When possible, links are provided to digitized copies of books, enabling first-hand
verification of details. When there are known discrepancies or outstanding questions, these are described in detail on the series-level
records. If you have any questions about an individual title, checking the record for the associated series may provide answers. The
series records also indicate which listings are not yet fully entered -- they will always include a note saying "This listing is a work
in progress."</p>

<h2>Who is responsible for the project?</h2>

<p>This project is hosted and coordinated by Falvey Memorial Library at Villanova University. Several other institutions have shared
raw data and/or contributed data entry labor to help build the site, including Northern Illinois University, the University of South
Florida, Stanford University, Bowling Green State University, Oberlin College, and the Library of Congress. Significant work on the
listings related to Beadle and Adams was funded through a <a href="https://www.clir.org">CLIR</a> Digitizing Hidden Special Collections
and Archives grant.</p>

<p>For a full list of individuals who have directly participated in the project, see the
<a href="<?=$this->url('about-credits')?>">Credits</a> page.</p>

<h2>How can I help?</h2>

<p>There are many ways you can help with the project:</p>

<ul>
  <li>Contribute corrections and additions.</li>
  <li>Contribute cover images.</li>
  <li>Submit reviews and collection lists.</li>
  <li>Volunteer to help with data entry.</li>
</ul>

<p>If you are interested in getting involved in these or other ways, please contact
<a href="mailto:demian.katz@villanova.edu">Demian Katz</a> for more details.</p>

<div style="clear: both;"><!-- empty --></div>
