<?php
  $this->layout()->title = 'Progress';
  $getColor = function ($status) {
    switch (strtolower($status)) {
      case 'done, believed complete':
        return 'green';
      default:
        return 'black';
    }
  };
  $showProgress = function ($current) {
    return ' - ' . $current['Item_Count'] . ' item'
      . ($current['Item_Count'] > 1 ? 's' : '') . ' listed';
  }
?>

<p>Data entry from the LeBlanc Bibliographies is currently in progress. This page summarizes the status of the listings.
Note that "Complete" is measured relative only to the original <a href="http://digital.library.villanova.edu/Collection/vudl:283769">LeBlanc Listings</a>;
series that have gaps in the original listings or that were not included in LeBlanc's research will be listed here as complete even if there are
unlisted titles within the database.</p>

<table class="table table-striped" style="width: auto;">
  <tr>
    <th style="text-align: left;" scope="col">Series Title</th>
    <th style="text-align: left;" scope="col">Data Source</th>
    <th style="text-align: left;" scope="col">Status</th>
  </tr>
<?php foreach ($progress as $current): ?>
  <tr>
    <td><a href="<?=$this->url('series', ['id' => $current['Series_ID']])?>"><?=$this->escapeHtml($this->fixtitle($current['Series_Name']))?></a></td>
    <td><?=empty($current['source']) ? '<i>Undetermined</i>' : $this->escapeHtml($current['source'])?></td>
    <td>
      <?php if (!empty($current['status'])): ?>
        <span style="color: <?=$getColor($current['status'])?>">
          <?=$this->escapeHtml($current['status'])?>
          <?php if (stristr($current['status'], 'in progress')): ?>
            <?=$showProgress($current)?>
          <?php endif; ?>
        </span>
      <?php elseif ($current['Complete']): ?>
        <span style="color: green;">Complete</span>
      <?php elseif ($current['Item_Count'] == 0): ?>
        <span style="color: red;">Not Started</span>
      <?php else: ?>
        <span style="color: black;">Partial<?=$showProgress($current)?></span>
      <?php endif; ?>
    </td>
  </tr>
<?php endforeach; ?>
</table>
