<h1>Dedications and Acknowledgements</h1>

<h2><i>This project is dedicated to the memory of Al and Celia 
Arker</i></h2>

<h3>Additional Thanks:</h3>

<p>There are obviously a lot of people who have contributed to this 
project; perhaps most importantly, I feel obligated to thank the authors 
who wrote 
the books that inspired this work.  Without them, an entire interesting 
branch of literature simply wouldn't exist.  I am also grateful to all the 
teachers who have encouraged me and given me the tools necessary to build 
a work like this; reaching this point has required a critical appreciation 
of literature, an understanding of database design and web programming, 
careful thinking about the organization of information, and a variety of 
other skills for which I likely owe someone thanks.  Last but not least, I 
owe thanks to everyone who has helped me to discover books that I wasn't 
already aware of or answered my numerous online queries.</p>

<p> Here are specific names, in alphabetical order:  David Amis, Andrea
Angiolino, David Archwamety, Kevin Aycock, Sebastian Pozzi Azzaro, Mikael
Backlund, Stephane Bechard, Guillermo Belziti, Bigcobra, Andrew 
Black, Bjorn 
Brostrom,
Nicholas Campbell, Ilhan Citak, Robert Clay, Alexis Cole, Sebastien
Coquery, Tiffany Cory, Steve Dahlskog, Brett Easterbrook, Jeff Eppnebach,
Bob Evans, Sergey F., Fly, Roberto Gaiba, Jim Gasperini,
Oscar Gracia, Joe Grocott-James, Jim Groom, Lars Wagner Hansen, Edward J.
Hennessy, Will Hirsch, Alan Homola, José Humberto Mesquita Filho, Angel
Igov, Ed Jolley, Per Jorner, Job de Kogel, Felix Kwan, Garett Lepper, Rick
Loomis, Frederic Martinoty, Henning Maruhn, Paul Mason, Kenichi Miwa,
Moloch's Gamebook Garden contributors, Ian Nowell, Falk Nussbaum, Tommi A.
Ojanperä, Simon Osborne, Guillermo Paredes, Carlos Perez, Mark J. Popp
(and the FightingFantasy.com contributors), Gwyan Rhabyt, Nicolau
Rodrigues, Justin Thomas Sampson, Gunther Schmidl, Brian W. Seals, Lukasz
Sewastianik, Ali Shaker, Jason Shiga, Nick Smith, Jorgen Stoevne, Thorsten
Thielen, Aaron W. Thorne, Andrew Tumber, Aaron M. Turiello, Rafael Velasco
Umpierrez, Peter Upton, Jim Vassilakos, Gary S. Watkins, Ed Webb, Ingmar
Wennerberg, Brian (WIZARDBWS) and Zoleeka from Hungary.</p>

<p>This list of thanks is not comprehensive -- since 
starting my database, I have begun attaching notes of thanks to the 
database records that they apply to.  If you don't see your name here, 
try looking up the information you helped me with; you should be 
there.  If not, I apologize -- contact me (<a 
href="mailto:demiankatz@gmail.com">demiankatz@gmail.com</a>) and I'll correct 
the oversight.</p>
