<?php
    $this->layout()->title = 'Sign Up';
?>

<?=$this->render('geeby-deeby/signup/signup-notes.phtml')?>

<h2>Your Information</h2>
<form action="" method="post">
<?php if (isset($error)): ?>
  <div class="error"><?=$this->escapeHtml($error)?></div>
<?php endif; ?>
<table class="signup"><tr>
<th scope="row">Username (not case sensitive):</th><td>
<input type="text" name="Username" value="<?=$this->escapeHtml($user ?? '')?>" size="25" maxlength="25" /></td></tr>
<th scope="row">Full Name:</th><td>
<input type="text" name="Fullname" value="<?=$this->escapeHtml($fullname ?? '')?>" size="25" maxlength="50" /></td></tr>
<th scope="row">E-Mail Address (optional):</th><td>
<input type="text" name="Address" value="<?=$this->escapeHtml($address ?? '')?>" size="25" maxlength="50" /></td></tr>
<tr><th scope="row">Password:</th><td>
<input type="password" name="Password1" size="25" maxlength="25" /></td></tr>
<tr><th scope="row">Retype Password:</th><td>
<input type="password" name="Password2" size="25" maxlength="25" /></td></tr>
<tr><td><input type="submit" name="submit" value="Sign Me Up" /></td></tr>
</table>
</form>
