<h2>Why Sign Up?</h2>
<p>There are two main reasons to sign up:</p>
<ul>
<li>You will be able to submit reviews to the site.</li>
<li>You will be able to maintain have, want and trade lists on the 
site.</li>
</ul>
<h2>Important Notes</h2>
<ul>
<li>Submitting your e-mail address is optional.  Your e-mail address will 
only be displayed to other users who are currently logged into the 
system.</li>
<li>Your account will not be activated until it is approved by an administrator.</li>
</ul>
