<form id="editForm" onsubmit="ItemsRelationship.save(); return false;">
  <input type="hidden" id="Items_Relationship_ID" value="<?=$relationship['Items_Relationship_ID']?>" />
  <table class="edit">
    <tr>
      <th scope="row"><label for="Items_Relationship_Name">Relationship Name:</label></th>
      <td><input type="text" id="Items_Relationship_Name" value="<?=isset($relationship['Items_Relationship_Name']) ? $this->escapeHtml($relationship['Items_Relationship_Name']) : ''?>" /></td>
    </tr>
    <tr>
      <th scope="row"><label for="Items_Relationship_RDF_Property">RDF Property (optional URI):</label></th>
      <td><input type="text" id="Items_Relationship_RDF_Property" value="<?=isset($relationship['Items_Relationship_RDF_Property']) ? $this->escapeHtml($relationship['Items_Relationship_RDF_Property']) : ''?>" /></td>
    </tr>
    <tr>
      <th scope="row"><label for="Display_Priority">Display Priority (lower numbers displayed first):</label></th>
      <td><input type="text" id="Display_Priority" value="<?=isset($relationship['Display_Priority']) ? $this->escapeHtml($relationship['Display_Priority']) : '0'?>" /></td>
    </tr>
    <tr>
      <th scope="row"><label for="Items_Inverse_Relationship_Name">Inverse Relationship Name (optional):</label></th>
      <td><input type="text" id="Items_Inverse_Relationship_Name" value="<?=isset($relationship['Items_Inverse_Relationship_Name']) ? $this->escapeHtml($relationship['Items_Inverse_Relationship_Name']) : ''?>" /></td>
    </tr>
    <tr>
      <th scope="row"><label for="Items_Inverse_Relationship_RDF_Property">Inverse RDF Property (optional URI):</label></th>
      <td><input type="text" id="Items_Inverse_Relationship_RDF_Property" value="<?=isset($relationship['Items_Inverse_Relationship_RDF_Property']) ? $this->escapeHtml($relationship['Items_Inverse_Relationship_RDF_Property']) : ''?>" /></td>
    </tr>
    <tr>
      <th scope="row"><label for="Inverse_Display_Priority">Inverse Display Priority (lower numbers displayed first):</label></th>
      <td><input type="text" id="Inverse_Display_Priority" value="<?=isset($relationship['Inverse_Display_Priority']) ? $this->escapeHtml($relationship['Inverse_Display_Priority']) : '0'?>" /></td>
    </tr>
  </table>
  <input type="submit" value="Save" />
  <div id="save_item_relationship_status"></div>
</form>
