<?php
    $this->layout()->title = 'File List';
?>
<?php if (count($files) < 1): ?>
  <p>No files listed in this database yet.</p>
<?php else: ?>
  <?php foreach ($files as $group => $fileList): ?>
    <h2><?=$this->escapeHtml($this->fixtitle($group))?></h2>
    <p>
      <?php foreach ($fileList as $file): ?>
        <a href="<?=$this->escapeHtml($file['File_Path'])?>">
          <?=$this->escapeHtml($this->fixtitle($file['File_Name']))?>
        </a>
        <?php if (!empty($file['Description'])): ?> - <?=$file['Description']?><?php endif; ?>
        <br />
      <?php endforeach; ?>
    </p>
  <?php endforeach; ?>
<?php endif; ?>
