<?php
$this->layout()->title = 'Recent Reviews';
?>
<table class="reviews">
  <tr><th scope="col">New Item Reviews</th><th scope="col">New Series Comments</th></tr>
  <tr style="vertical-align: top;">
    <td style="width: 50%;">
      <?php if (count($reviews) < 1): ?>
        <p>No reviews available.</p>
      <?php else: ?>
        <table class="innerReviews">
          <tr><th scope="col">Date</th><th scope="col">Title</th><th scope="col">User</th></tr>
          <?php foreach ($reviews as $current): ?>
            <tr>
              <td><?=$this->escapeHtml($current['Added'])?></td>
              <td>
                <a href="<?=$this->url('item', ['id' => $current['Item_ID']])?>">
                  <?=$this->escapeHtml($this->fixtitle($current['Item_Name']))?>
                </a>
              </td>
              <td>
                <a href="<?=$this->url('user', ['id' => $current['User_ID']])?>">
                  <?=$this->escapeHtml($current['Username'])?>
                </a>
              </td>
            </tr>
          <?php endforeach; ?>
        </table>
      <?php endif; ?>
    </td>
    <td>
      <?php if (count($comments) < 1): ?>
        <p>No comments available.</p>
      <?php else: ?>
        <table class="innerReviews">
          <tr><th scope="col">Date</th><th scope="col">Title</th><th scope="col">User</th></tr>
          <?php foreach ($comments as $current): ?>
            <tr>
              <td><?=$this->escapeHtml($current['Added'])?></td>
              <td>
                <a href="<?=$this->url('series', ['id' => $current['Series_ID']])?>">
                  <?=$this->escapeHtml($this->fixtitle($current['Series_Name']))?>
                </a>
              </td>
              <td>
                <a href="<?=$this->url('user', ['id' => $current['User_ID']])?>">
                  <?=$this->escapeHtml($current['Username'])?>
                </a>
              </td>
            </tr>
          <?php endforeach; ?>
        </table>
      <?php endif; ?>
    </td>
  </tr>
</table>