<?
    $this->headTitle('Recent Reviews - ');
?>
<h1>Recent Reviews</h1>

<table class="reviews">
  <tr><th>New Item Reviews</th><th>New Series Comments</th></tr>
  <tr>
    <td>
      <? if (count($reviews) < 1): ?>
        <p>No reviews available.</p>
      <? else: // TODO ?>
      <? endif; ?>
    </td>
    <td>
      <? if (count($comments) < 1): ?>
        <p>No comments available.</p>
      <? else: // TODO ?>
      <? endif; ?>
    </td>
  </tr>
</table>