<?php $series = false; foreach ($items as $item): ?>
  <?php if ($sort === 'series' && $series !== $item['Series_ID']): $series = $item['Series_ID']; ?>
    <h2 class="series"><a href="<?=$this->url('series', ['id' => $series])?>">
      <?=$this->fixtitle($item['Series_Name']);?>
    </a></h2>
  <?php endif; ?>
  <span class="item">
    <?php if ($sort === 'series'): ?><?=$this->escapeHtml($this->formatItemNumber($item))?><?php endif; ?>
    <a href="<?=$this->url('item', ['id' => $item['Item_ID']])?>">
      <?=$this->fixtitle(
        empty($item['Item_AltName']) ? $item['Item_Name'] : $item['Item_AltName']
      )?>
    </a>
    <br />
  </span>
<?php endforeach; ?>
