<?php
$this->layout()->title = 'Subject/Tag List';
?>
<?php if (count($tags) < 1): ?>
  <p>No subjects/tags listed in this database yet.</p>
<?php else: ?>
  <h2>
    <?=$this->firstLetterMenu($tags, 'Tag'); ?>
  </h2>
  <?php $currentLetter = false;
    foreach ($tags as $i => $current): ?>
    <?php $first = $this->firstletter($current['Tag']); ?>
    <?php if ($currentLetter !== $first): $currentLetter = $first; ?>
      <?php if ($i > 0): ?>
        <a name="<?=$this->escapeHtml($currentLetter)?>"/>
        <h2><?=$this->escapeHtml($currentLetter)?><a href="#" style="float:right">Back to Top &uarr;</a></h2>
      <?php endif; ?>
    <?php endif; ?>
    <a href="<?=$this->url('tag', ['id' => $current['Tag_ID']])?>">
      <?=$this->escapeHtml($current['Tag'])?>
    </a><br />
  <?php endforeach; ?>
<?php endif; ?>
