<?php
    $title = $tag['Tag'];
    $this->layout()->title = 'Subject/Tag - ' . $title;
    $displayedSomething = false;
?>
<table class="item">
  <?php foreach ($tagAttributes as $current): ?>
    <tr>
      <th><?=$this->escapeHtml($current->Tags_Attribute_Name)?>:</th>
      <td>
        <?php $displayedSomething = true; ?>
        <?php if ($current->Allow_HTML == 1): ?>
          <?=$current->Tags_Attribute_Value?>
        <?php else: ?>
          <?=$this->escapeHtml($current->Tags_Attribute_Value)?>
        <?php endif; ?>
      </td>
    </tr>
  <?php endforeach; ?>
  <?php foreach ($this->relationshipsValues as $current): ?>
    <tr>
      <th><?=$this->escapeHtml($current['label'])?>:</th>
      <td>
        <?php foreach ($current['values'] as $value): ?>
          <a href="<?=$this->url('tag', ['id' => $value['Tag_ID']])?>">
            <?=$this->escapeHtml($value['Tag'])?>
          </a><br />
        <?php endforeach; ?>
      </td>
    </tr>
  <?php endforeach; ?>
</table>
<?php if (count($items) > 0): $displayedSomething = true; ?>
  <?php $series = false; foreach ($items as $item): ?>
    <?php if ($series !== $item['Series_ID']): $series = $item['Series_ID']; ?>
      <h2 class="series"><a href="<?=$this->url('series', ['id' => $series])?>">
        <?=$this->fixtitle($item['Series_Name']);?>
      </a></h2>
    <?php endif; ?>
    <span class="item">
      <?=$this->escapeHtml($this->formatItemNumber($item))?>
      <a href="<?=$this->url('item', ['id' => $item['Item_ID']])?>">
        <?=$this->fixtitle(
          empty($item['Item_AltName']) ? $item['Item_Name'] : $item['Item_AltName']
        )?>
      </a>
      <br />
    </span>
  <?php endforeach; ?>
<?php endif; ?>

<?php if (!$displayedSomething): ?>
  <p>No information is available about this subject/tag.</p>
<?php endif; ?>