<?
    $title = $tag['Tag'];
    $this->layout()->title = 'Subject/Tag - ' . $title;
    $displayedSomething = false;
?>
<table class="item">
  <? foreach ($tagAttributes as $current): ?>
    <tr>
      <th><?=$this->escapeHtml($current->Tags_Attribute_Name)?>:</th>
      <td>
        <? $displayedSomething = true; ?>
        <? if ($current->Allow_HTML == 1): ?>
          <?=$current->Tags_Attribute_Value?>
        <? else: ?>
          <?=$this->escapeHtml($current->Tags_Attribute_Value)?>
        <? endif; ?>
      </td>
    </tr>
  <? endforeach; ?>
  <? foreach ($this->relationshipsValues as $current): ?>
    <tr>
      <th><?=$this->escapeHtml($current['label'])?>:</th>
      <td>
        <? foreach ($current['values'] as $value): ?>
          <a href="<?=$this->url('tag', ['id' => $value['Tag_ID']])?>">
            <?=$this->escapeHtml($value['Tag'])?>
          </a><br />
        <? endforeach; ?>
      </td>
    </tr>
  <? endforeach; ?>
</table>
<? if (count($items) > 0): $displayedSomething = true; ?>
  <? $series = false; foreach ($items as $item): ?>
    <? if ($series !== $item['Series_ID']): $series = $item['Series_ID']; ?>
      <h2 class="series"><a href="<?=$this->url('series', array('id' => $series))?>">
        <?=$this->fixtitle($item['Series_Name']);?>
      </a></h2>
    <? endif; ?>
    <span class="item">
      <?=$this->escapeHtml($this->formatItemNumber($item))?>
      <a href="<?=$this->url('item', array('id' => $item['Item_ID']))?>">
        <?=$this->fixtitle(
          empty($item['Item_AltName']) ? $item['Item_Name'] : $item['Item_AltName']
        )?>
      </a>
      <br />
    </span>
  <? endforeach; ?>
<? endif; ?>

<? if (!$displayedSomething): ?>
  <p>No information is available about this subject/tag.</p>
<? endif; ?>