<?php
    $title = $tag['Tag'];
    $this->layout()->title = 'Subject/Tag - ' . $title;
    $this->layout()->toggleLink = $this->toggleLink('edit/tag', $tag['Tag_ID']);
    $displayedSomething = false;
?>
<table class="item">
  <?php foreach ($tagAttributes as $current): ?>
    <tr>
      <th scope="row"><?=$this->escapeHtml($current->Tags_Attribute_Name)?>:</th>
      <td>
        <?php $displayedSomething = true; ?>
        <?php if ($current->Allow_HTML == 1): ?>
          <?=$current->Tags_Attribute_Value?>
        <?php else: ?>
          <?=$this->escapeHtml($current->Tags_Attribute_Value)?>
        <?php endif; ?>
      </td>
    </tr>
  <?php endforeach; ?>
  <?php foreach ($this->relationshipsValues as $current): ?>
    <?php $displayedSomething = true; ?>
    <tr>
      <th scope="row"><?=$this->escapeHtml($current['label'])?>:</th>
      <td>
        <?php foreach ($current['values'] as $value): ?>
          <a href="<?=$this->url('tag', ['id' => $value['Tag_ID']])?>">
            <?=$this->escapeHtml($value['Tag'])?>
          </a><br />
        <?php endforeach; ?>
      </td>
    </tr>
  <?php endforeach; ?>
  <?php $uriCount = count($uris); ?>
  <?php if ($uriCount > 0): $displayedSomething = true; ?>
    <tr>
      <th>External Identifier<?php if ($uriCount > 1): ?>s<?php endif; ?>:</th>
      <td>
        <?php $i = 0; ?>
        <?php foreach ($uris as $uri): $i++ ?>
          <a href="<?=$this->escapeHtmlAttr($uri['URI'])?>"><?=$this->escapeHtml($uri['URI'])?></a><?=$i < $uriCount ? ', ' : ''?>
        <?php endforeach; ?>
      </td>
    </tr>
  <?php endif; ?>
</table>
<?php if (count($items) > 0): $displayedSomething = true; ?>
  <?php $sorts = [ 'series', 'title' ];
  $sort = $this->sort ?? $sorts[0]; ?>
  <div class="pull-right" style="padding:12px 0;">
    Sort by:
    <div class="btn-group" style="margin-top:-4px;">
      <?php foreach ($sorts as $current): ?>
        <a href="?sort=<?=urlencode($current)?>" class="btn btn-<?=$sort == $current ? 'primary' : 'default'?>"><?=ucwords($current)?></a>
      <?php endforeach; ?>
    </div>
  </div>
  <?=$this->render('geeby-deeby/tag/innerList.phtml', compact('title', 'sort', 'items'))?>
<?php endif; ?>

<?php if (!$displayedSomething): ?>
  <p>No information is available about this subject/tag.</p>
<?php endif; ?>
