<? $this->layout()->title = 'Edit Notes' ?>
<? $this->headScript()->appendFile($this->basePath() . '/js/base_editor.js') ?>
<? $this->headScript()->appendFile($this->basePath() . '/js/edit_notes.js') ?>
<p><b>Notes:</b></p>
<button id="add_note" type="button" onclick="Note.edit('NEW');">Add Note</button>
<br /><br />
<div id="note_list"><?=$this->render('geeby-deeby/edit-note/render-notes.phtml')?></div>
