<?php if (count($notes) == 0): ?>
  <p>No notes defined yet.</p>
<?php else: ?>
  <h2>
    <?=$this->firstLetterMenu($notes, 'Note'); ?>
  </h2>
  <?php $currentLetter = false;
    foreach ($notes as $i => $current): ?>
    <?php $first = $this->firstletter($current['Note']); ?>
    <?php if ($currentLetter !== $first): $currentLetter = $first; ?>
      <?php if ($i > 0): ?>
        <a name="<?=$this->escapeHtml($currentLetter)?>"/>
        <h2><?=$this->escapeHtml($currentLetter)?><a href="#" style="float:right">Back to Top &uarr;</a></h2>
      <?php endif; ?>
    <?php endif; ?>
    <a href="#" onClick="Note.edit(<?=$current['Note_ID'] ?>);return false">
      <?=$this->escapeHtml($this->fixtitle($current['Note']))?>
    </a><br />
  <?php endforeach; ?>
<?php endif; ?>