<? $this->layout()->title = 'Edit Tag' ?>
<? $this->scriptManager()->add(['base_editor', 'edit_tags']) ?>
<div class="edit_container">
  <?=$this->render('geeby-deeby/edit-tag/index.phtml')?>
</div>
<hr />
<div class="row">
  <div class="col-md-12">
    <b>URIs (for linked data):</b><br />
    <?=$this->render('geeby-deeby/edit-predicate/select.phtml')?>
    <input type="text" id="uri" />
    <button onclick="Tag.link('URI');">Add URI</button>
    <div id="uri_list">
      <?=$this->render('geeby-deeby/edit-tag/uri-list.phtml')?>
    </div>
  </div>
</div>