<?php if (empty($this->relationshipsValues)): ?>
  <p>No relationships defined.</p>
<?php else: ?>
    <?php foreach ($this->relationshipsValues as $current): ?>
      <h3><?=$this->escapeHtml($current['label'])?>:</h3>
      <table class="list_item">
        <?php foreach ($current['values'] as $value): ?>
          <tr>
            <td>
              <a href="<?=$this->url('edit/tag', ['id' => $value['Tag_ID']])?>">
                <?=$this->escapeHtml($value['Tag'])?>
              </a>
            </td><td>
              <a class="ui-icon ui-icon-trash" href="#" onclick="Tag.unlink('Relationship', <?=$value['Tag_ID']?>, '/<?=$current['relationship_id']?>'); return false;">
              </a>
            </td>
          </tr>
        <?php endforeach; ?>
      </table>
    <?php endforeach; ?>
  </table>
<?php endif; ?>
