<? if (count($tags) < 1): ?>
  <p>No tags listed in this database yet.</p>
<? else: ?>
  <h2>
    <?=$this->firstLetterMenu($tags, 'Publisher_Name'); ?>
  </h2>
  <? $currentLetter = false; foreach ($tags as $i=>$current): ?>
    <? $first = $this->firstletter($current['Publisher_Name']); ?>
    <? if ($currentLetter !== $first): $currentLetter = $first; ?>
      <? if ($i > 0): ?>
        <a name="<?=$this->escapeHtml($currentLetter)?>"/>
        <h2><?=$this->escapeHtml($currentLetter)?><a href="#" style="float:right">Back to Top &uarr;</a></h2>
      <? endif; ?>
    <? endif; ?>
    <a href="#" onclick="editTag(<?=$current['Tag_ID']?>); return false;"><?=$this->escapeHtml($current['Tag'])?></a><br />
  <? endforeach; ?>
<? endif; ?>