<form id="editForm" onsubmit="TagType.save(); return false;">
  <input type="hidden" id="Tag_Type_ID" value="<?=$tagType['Tag_Type_ID']?>" />
  <table class="edit">
    <tr>
      <th scope="row"><label for="Tag_Type">Subject/Tag Type:</label></th>
      <td><input type="text" id="Tag_Type" value="<?=isset($tagType['Tag_Type']) ? $this->escapeHtml($tagType['Tag_Type']) : ''?>" /></td>
    </tr>
  </table>
  <input type="submit" value="Save" />
  <div id="save_tag_type_status"></div>
</form>
