<?php if (isset($tagTypes) && count($tagTypes) > 0): ?>
  <select id="<?=!empty($idPrefix) ? $this->escapeHtml($idPrefix) : ''?>Tag_Type_ID">
    <?php foreach ($tagTypes as $current): ?>
      <option value="<?=$current['Tag_Type_ID']?>"<?=($current['Tag_Type_ID'] == $selected) ? ' selected="selected"' : ''?>>
        <?=$this->escapeHtml($current['Tag_Type'])?>
      </option>
    <?php endforeach; ?>
  </select>
<?php else: ?>
  Please define subject/tag types.
<?php endif; ?>