<div id="editForm">
  <input type="hidden" id="Language_ID" value="<?=$language['Language_ID']?>" />
  <table class="edit">
    <tr>
      <th>Language:</th>
      <td><input type="text" id="Language_Name" value="<?=isset($language['Language_Name']) ? $this->escapeHtml($language['Language_Name']) : ''?>" /></td>
    </tr>
  </table>
  <button id="save_language" onclick="Language.save();">Save</button>
  <div id="save_language_status"></div>
</div>
