<form id="editForm" onsubmit="Language.save(); return false;">
  <input type="hidden" id="Language_ID" value="<?=$language['Language_ID']?>" />
  <table class="edit">
    <tr>
      <th scope="row"><label for="Language_Name">Language:</label></th>
      <td><input type="text" id="Language_Name" value="<?=isset($language['Language_Name']) ? $this->escapeHtml($language['Language_Name']) : ''?>" /></td>
    </tr>
  </table>
  <input type="submit" value="Save" />
  <div id="save_language_status"></div>
</form>
