<? $this->layout()->title = 'Edit Languages' ?>
<? $this->headScript()->appendFile($this->basePath() . '/js/base_editor.js') ?>
<? $this->headScript()->appendFile($this->basePath() . '/js/edit_languages.js') ?>
<p><b>Languages:</b></p>
<button id="add_language" type="button" onclick="Language.edit('NEW');">Add Language</button>
<br /><br />
<div id="language_list"><?=$this->render('geeby-deeby/edit-language/render-languages.phtml')?></div>
