<?php if (isset($languages) && count($languages) > 0): ?>
  <select id="Language_ID">
    <?php foreach ($languages as $current): ?>
      <option value="<?=$current['Language_ID']?>"<?=($current['Language_ID'] == $selected) ? ' selected="selected"' : ''?>>
        <?=$this->escapeHtml($current['Language_Name'])?>
      </option>
    <?php endforeach; ?>
  </select>
<?php else: ?>
  Please define languages.
<?php endif; ?>