<?
    $title = $user['Username'];
    $this->headTitle('Potential Buyers - ' . $title . ' - ');
?>
<h1>Potential Buyers - <?=$this->escapeHtml($title)?></h1>

<p><a href="<?=$this->url('user', array('id' => $user['User_ID']))?>">Get more information on this user.</a></p>

<? if (count($buyers) < 1): ?>
  <p>No buyers available.</p>
<? else: ?>
  <? $series = $seller = false; foreach ($buyers as $extra): ?>
    <? if ($seller !== $extra['User_ID']): $series = false; $seller = $extra['User_ID']; ?>
      <h2 class="user"><a href="<?=$this->url('user', array('id' => $seller))?>">
        <?=$this->fixtitle($extra['Username']);?>
      </a></h2>
    <? endif; ?>
    <? if ($series !== $extra['Series_ID']): $series = $extra['Series_ID']; ?>
      <h3 class="series"><a href="<?=$this->url('series', array('id' => $series))?>">
        <?=$this->fixtitle($extra['Series_Name']);?>
      </a></h3>
    <? endif; ?>
    <p class="extraitem">
      <?=$extra['Position'] > 0 ? $this->escapeHtml($extra['Position']) . '. ' : ''?>
      <a href="<?=$this->url('item', array('id' => $extra['Item_ID']))?>">
        <?=$this->fixtitle($extra['Item_Name'])?>
      </a>
      <? if (!empty($extra['Collection_Note'])): ?><br /><b>Buyer's Note:</b> <?=$this->escapeHtml($extra['Collection_Note'])?><? endif; ?>
      <? if (!empty($extra['Other_Note'])): ?><br /><b>Seller's Note:</b> <?=$this->escapeHtml($extra['Other_Note'])?><? endif; ?>
    </p>
  <? endforeach; ?>
<? endif; ?>