<?
    $title = $user['Username'];
    $this->headTitle('User Comments - ' . $title . ' - ');
?>
<h1>User Comments - <?=$this->escapeHtml($title)?></h1>
<p><a href="<?=$this->url('user', array('id' => $user['User_ID']))?>">Get more information on this user.</a></p>

<? if (count($comments) > 0): ?>
  <? $currentLetter = false; foreach ($comments as $current): ?>
    <? $first = $this->firstletter($current['Series_Name']); if ($currentLetter !== $first): $currentLetter = $first; ?>
      <h2><?=$this->escapeHtml($currentLetter)?></h2>
    <? endif; ?>
    <a href="<?=$this->url('series', array('id' => $current['Series_ID']))?>">
      <?=$this->escapeHtml($this->fixtitle($current['Series_Name']))?>
    </a><br />
  <? endforeach; ?>
<? else: ?>
  <p>No comments listed.</p>
<? endif; ?>
