<?php $this->layout()->title = 'Edit Account' ?>

<p>You can change your account details here; if you wish to retain your current password,
leave the password fields blank.</p>

<h2>Your Information</h2>
<form action="" method="post">
<?php if (isset($error)): ?>
  <div class="error"><?=$this->escapeHtml($error)?></div>
<?php endif; ?>
<table class="signup"><tr>
<th scope="row"><label for="edit_fullname">Full Name:</label></th><td>
<input id="edit_fullname" type="text" name="Fullname" value="<?=$this->escapeHtml($fullname ?? '')?>" size="25" maxlength="50" /></td></tr>
<th scope="row"><label for="edit_email">E-Mail Address (optional):</label></th><td>
<input id="edit_email" type="email" name="Address" value="<?=$this->escapeHtml($address ?? '')?>" size="25" maxlength="50" /></td></tr>
<tr><th scope="row"><label for="edit_password1">Password:</label></th><td>
<input id="edit_password1" type="password" name="Password1" size="25" maxlength="25" /></td></tr>
<tr><th scope="row"><label for="edit_password2">Retype Password:</label></th><td>
<input id="edit_password2" type="password" name="Password2" size="25" maxlength="25" /></td></tr>
<tr><td></td><td><input type="submit" name="submit" value="Update Account" /></td></tr>
</table>
</form>
