<?php $this->layout()->title = 'Edit Account' ?>

<p>You can change your account details here; if you wish to retain your current password,
leave the password fields blank.</p>

<h2>Your Information</h2>
<form action="" method="post">
<?php if (isset($error)): ?>
  <div class="error"><?=$this->escapeHtml($error)?></div>
<?php endif; ?>
<table class="signup"><tr>
<th scope="row">Full Name:</th><td>
<input type="text" name="Fullname" value="<?=$this->escapeHtml($fullname ?? '')?>" size="25" maxlength="50" /></td></tr>
<th scope="row">E-Mail Address (optional):</th><td>
<input type="text" name="Address" value="<?=$this->escapeHtml($address ?? '')?>" size="25" maxlength="50" /></td></tr>
<tr><th scope="row">Password:</th><td>
<input type="password" name="Password1" size="25" maxlength="25" /></td></tr>
<tr><th scope="row">Retype Password:</th><td>
<input type="password" name="Password2" size="25" maxlength="25" /></td></tr>
<tr><td></td><td><input type="submit" name="submit" value="Update Account" /></td></tr>
</table>
</form>
