<?php
    $title = $user['Username'];
    $this->layout()->title = 'Books for Sale/Trade - ' . $title;
?>
<p><a href="<?=$this->url('user', ['id' => $user['User_ID']])?>">Get more information on this user.</a></p>

<?php if (count($extras) < 1): ?>
  <p>No items listed.</p>
<?php else: ?>
  <?=$this->render('geeby-deeby/user/sale-disclaimer.phtml')?>

  <?php $series = false; foreach ($extras as $extra): ?>
    <?php if ($series !== $extra['Series_ID']): $series = $extra['Series_ID']; ?>
      <h2 class="series"><a href="<?=$this->url('series', ['id' => $series])?>">
        <?=$this->fixtitle($extra['Series_Name']);?>
      </a></h2>
    <?php endif; ?>
    <p class="extraitem">
      <?=$this->escapeHtml($this->formatItemNumber($extra))?>
      <a href="<?=$this->url('item', ['id' => $extra['Item_ID']])?>">
        <?=$this->escapeHtml($this->fixtitle(isset($extra['Item_AltName']) && !empty($extra['Item_AltName']) ? $extra['Item_AltName'] : $extra['Item_Name']))?>
      </a>
      <?php if (!empty($extra['Collection_Note'])): ?><br /><?=$this->escapeHtml($extra['Collection_Note'])?><?php endif; ?>
    </p>
  <?php endforeach; ?>
<?php endif; ?>