<?
    $title = $user['Username'];
    $this->headTitle('Books for Sale/Trade - ' . $title . ' - ');
?>
<h1>Books for Sale/Trade - <?=$this->escapeHtml($title)?></h1>

<p><a href="<?=$this->url('user', array('id' => $user['User_ID']))?>">Get more information on this user.</a></p>

<? if (count($extras) < 1): ?>
  <p>No items listed.</p>
<? else: ?>
  <?=$this->render('geeby-deeby/user/sale-disclaimer.phtml')?>

  <? $series = false; foreach ($extras as $extra): ?>
    <? if ($series !== $extra['Series_ID']): $series = $extra['Series_ID']; ?>
      <h2 class="series"><a href="<?=$this->url('series', array('id' => $series))?>">
        <?=$this->fixtitle($extra['Series_Name']);?>
      </a></h2>
    <? endif; ?>
    <p class="extraitem">
      <?=$extra['Position'] > 0 ? $this->escapeHtml($extra['Position']) . '. ' : ''?>
      <a href="<?=$this->url('item', array('id' => $extra['Item_ID']))?>">
        <?=$this->fixtitle($extra['Item_Name'])?>
      </a>
      <? if (!empty($extra['Collection_Note'])): ?><br /><?=$this->escapeHtml($extra['Collection_Note'])?><? endif; ?>
    </p>
  <? endforeach; ?>
<? endif; ?>