<?php
    $title = $user['Username'];
    $this->layout()->title = 'User - ' . $title;
?>

<?php if ($this->auth()->hasIdentity() && $this->auth()->getIdentity() == $user['User_ID']): ?>
  <div class="controls top">
    <?php ob_start(); ?>
    <p>
      <a class="button" href="<?=$this->url('user', ['id' => $user['User_ID'], 'extra' => 'Edit'])?>">
        Edit Account Details
      </a>
    </p>
    <?php $controls = ob_get_flush(); ?>
  </div>
<?php endif; ?>

<p><a href="<?=$this->url('users')?>">[List All Users]</a></p>

<table class="user">
  <tr>
    <th scope="row">Full Name:</th>
    <td>
      <?php if ($user['Person_ID'] > 0): ?>
        <a href="<?=$this->url('person', ['id' => $user['Person_ID']])?>">
      <?php endif; ?>
      <?=$this->escapeHtml($user['Name'])?>
      <?php if ($user['Person_ID'] > 0): ?>
        </a>
      <?php endif; ?>
    </td>
  </tr>
  <?php if (!empty($user['Address'])): ?>
    <tr>
      <th scope="row">Email Address:</th>
      <td>
        <?php if ($this->auth()->hasIdentity()): ?>
          <a href="mailto:<?=$this->escapeHtml($user['Address'])?>"><?=$this->escapeHtml($user['Address'])?></a>
        <?php else: ?>
          Please <a href="<?=$this->url('login')?>">log in</a> to see this user's email address.
        <?php endif; ?>
      </td>
    </tr>
  <?php endif; ?>
  <tr>
    <th scope="row">Collections:</th>
    <td>
      <a href="<?=$this->url('user', ['id' => $user['User_ID'], 'extra' => 'Collection'])?>">View Have/Want Lists</a>
      (<?=$stats['have']?> items owned, <?=$stats['want']?> items wanted)
      [<a href="<?=$this->url('user', ['id' => $user['User_ID'], 'extra' => 'Sellers'])?>">List Potential Sellers</a>]
      <br />
      <a href="<?=$this->url('user', ['id' => $user['User_ID'], 'extra' => 'Extras'])?>">View Sale/Trade Lists</a>
      (<?=$stats['extra']?> items for sale/trade)
      [<a href="<?=$this->url('user', ['id' => $user['User_ID'], 'extra' => 'Buyers'])?>">List Potential Buyers</a>]
    </td>
  </tr>
  <tr>
    <th scope="row">Reviews and Comments:</th>
    <td>
      <?php $revCount = count($reviews);
      if ($revCount > 0): ?>
        <a href="<?=$this->url('user', ['id' => $user['User_ID'], 'extra' => 'Reviews'])?>"><?=$revCount?> item review<?=$revCount > 1 ? 's' : ''?>.</a>
      <?php else: ?>
        0 item reviews.
      <?php endif; ?>
      <br />
      <?php $commentCount = count($comments);
      if ($commentCount > 0): ?>
        <a href="<?=$this->url('user', ['id' => $user['User_ID'], 'extra' => 'Comments'])?>"><?=$commentCount?> series comment<?=$commentCount > 1 ? 's' : ''?>.</a>
      <?php else: ?>
        0 series comments.
      <?php endif; ?>
    </td>
  </tr>
</table>
<?php if (isset($controls)): ?>
  <div class="controls bottom"><?=$controls?></div>
<?php endif; ?>