<?
    $title = $user['Username'];
    $this->headTitle('User - ' . $title . ' - ');
?>
<h1><?=$this->escapeHtml($title)?></h1>

<p><a href="<?=$this->url('users')?>">[List All Users]</a></p>

<table class="user">
  <tr>
    <th>Full Name:</th>
    <td>
      <? if ($user['Person_ID'] > 0): ?>
        <a href="<?=$this->url('person', array('id' => $user['Person_ID']))?>">
      <? endif; ?>
      <?=$this->escapeHtml($user['Name'])?>
      <? if ($user['Person_ID'] > 0): ?>
        </a>
      <? endif; ?>
    </td>
  </tr>
  <? if (!empty($user['Address'])): ?>
    <tr>
      <th>Email Address:</th>
      <td>
        <? if ($this->layout()->loggedIn): ?>
          <a href="mailto:<?=$this->escapeHtml($user['Address'])?>"><?=$this->escapeHtml($user['Address'])?></a>
        <? else: ?>
          Please <a href="<?=$this->url('login')?>">log in</a> to see this user's email address.
        <? endif; ?>
      </td>
    </tr>
  <? endif; ?>
  <tr>
    <th>Collections:</th>
    <td>
      <a href="<?=$this->url('user', array('id' => $user['User_ID'], 'extra' => 'Collection'))?>">View Have/Want Lists</a>
      (<?=$stats['have']?> items owned, <?=$stats['want']?> items wanted)
      [<a href="<?=$this->url('user', array('id' => $user['User_ID'], 'extra' => 'Sellers'))?>">List Potential Sellers</a>]
      <br />
      <a href="<?=$this->url('user', array('id' => $user['User_ID'], 'extra' => 'Extras'))?>">View Sale/Trade Lists</a>
      (<?=$stats['extra']?> items for sale/trade)
      [<a href="<?=$this->url('user', array('id' => $user['User_ID'], 'extra' => 'Buyers'))?>">List Potential Buyers</a>]
    </td>
  </tr>
  <tr>
    <th>Reviews and Comments:</th>
    <td>
      <? $revCount = count($reviews); if ($revCount > 0): ?>
        <a href="<?=$this->url('user', array('id' => $user['User_ID'], 'extra' => 'Reviews'))?>"><?=$revCount?> item review<?=$revCount > 1 ? 's' : ''?>.</a>
      <? else: ?>
        0 item reviews.
      <? endif; ?>
      <br />
      <? $commentCount = count($comments); if ($commentCount > 0): ?>
        <a href="<?=$this->url('user', array('id' => $user['User_ID'], 'extra' => 'Comments'))?>"><?=$commentCount?> series comment<?=$commentCount > 1 ? 's' : ''?>.</a>
      <? else: ?>
        0 series comments.
      <? endif; ?>
    </td>
  </tr>
</table>
<? /* TODO: account management controls */ ?>