<?
    $this->layout()->title = 'User List';
?>
<? if (count($users) < 1): ?>
  <p>No users listed in this database yet.</p>
<? else: ?>
  <h2>
    <?=$this->firstLetterMenu($users, 'Username'); ?>
  </h2>
  <? $currentLetter = false; foreach ($users as $i=>$current): ?>
    <? $first = $this->firstletter($current['Username']); ?>
    <? if ($currentLetter !== $first): $currentLetter = $first; ?>
      <? if ($i > 0): ?>
        <a name="<?=$this->escapeHtml($currentLetter)?>"/>
        <h2><?=$this->escapeHtml($currentLetter)?><a href="#" style="float:right">Back to Top &uarr;</a></h2>
      <? endif; ?>
    <? endif; ?>
    <a href="<?=$this->url('user', array('id' => $current['User_ID']))?>">
      <?=$this->escapeHtml($this->fixtitle($current['Username']))?>
    </a><br />
  <? endforeach; ?>
<? endif; ?>