<?
    $this->layout()->title = 'User List';
?>
<? if (count($users) < 1): ?>
  <p>No users listed in this database yet.</p>
<? else: ?>
  <? $currentLetter = false; foreach ($users as $current): ?>
    <? $first = $this->firstletter($current['Username']); if ($currentLetter !== $first): $currentLetter = $first; ?>
      <h2><?=$this->escapeHtml($currentLetter)?></h2>
    <? endif; ?>
    <a href="<?=$this->url('user', array('id' => $current['User_ID']))?>">
      <?=$this->escapeHtml($this->fixtitle($current['Username']))?>
    </a><br />
  <? endforeach; ?>
<? endif; ?>