<?
    $title = $user['Username'];
    $this->layout()->title = 'User Reviews - ' . $title;
?>
<p><a href="<?=$this->url('user', array('id' => $user['User_ID']))?>">Get more information on this user.</a></p>

<? if (count($reviews) > 0): ?>
  <? $series = false; foreach ($reviews as $review): ?>
    <? if ($series !== $review['Series_ID']): $series = $review['Series_ID']; ?>
      <h2 class="series"><a href="<?=$this->url('series', array('id' => $series))?>">
        <?=$this->fixtitle($review['Series_Name']);?>
      </a></h2>
    <? endif; ?>
    <span class="item">
      <?=$review['Position'] > 0 ? $this->escapeHtml($review['Position']) . '. ' : ''?>
      <a href="<?=$this->url('item', array('id' => $review['Item_ID']))?>">
        <?=$this->escapeHtml($this->fixtitle(isset($review['Item_AltName']) && !empty($review['Item_AltName']) ? $review['Item_AltName'] : $review['Item_Name']))?>
      </a>
      <br />
    </span>
  <? endforeach; ?>
<? else: ?>
  <p>No reviews listed.</p>
<? endif; ?>
