<?php
    $title = $user['Username'];
    $this->layout()->title = 'User Reviews - ' . $title;
?>
<p><a href="<?=$this->url('user', ['id' => $user['User_ID']])?>">Get more information on this user.</a></p>

<?php if (count($reviews) > 0): ?>
  <?php $series = false; foreach ($reviews as $review): ?>
    <?php if ($series !== $review['Series_ID']): $series = $review['Series_ID']; ?>
      <h2 class="series"><a href="<?=$this->url('series', ['id' => $series])?>">
        <?=$this->fixtitle($review['Series_Name']);?>
      </a></h2>
    <?php endif; ?>
    <span class="item">
      <?=$this->escapeHtml($this->formatItemNumber($review))?>
      <a href="<?=$this->url('item', ['id' => $review['Item_ID']])?>">
        <?=$this->escapeHtml($this->fixtitle(isset($review['Item_AltName']) && !empty($review['Item_AltName']) ? $review['Item_AltName'] : $review['Item_Name']))?>
      </a>
      <br />
    </span>
  <?php endforeach; ?>
<?php else: ?>
  <p>No reviews listed.</p>
<?php endif; ?>
