<div class="footer">
  <p>
    <a href="<?=$this->basePath()?>"><?=$this->escapeHtml($this->config('siteTitle'))?></a>
    &copy; 1998-<?=$this->escapeHtml(date('Y'))?> Demian Katz
  </p>
  <p class="fineprint">
    Individual reviews are the property of their authors.<br />
    Trademarks and graphics remain the property of their respective owners and
    are used here solely for the educational purpose of documenting the history
    and scope of interactive storytelling. No infringement is intended.<br />
    If you have any questions or complaints, please contact <a href="mailto:<?=$this->escapeHtml($this->config('siteEmail'))?>"><?=$this->escapeHtml($this->config('siteEmail'))?></a>.
  </p>
</div>
