<br />
<div class="headerControls">
  <? if ($this->auth()->hasIdentity()): ?>
    <a href="<?=$this->url('user', array('id' => $this->auth()->getIdentity()))?>">Account</a> ·
    <a href="<?=$this->url('logout')?>">Log Out</a>
  <? else: ?>
    <a href="<?=$this->url('signup')?>">Sign Up</a> ·
    <a href="<?=$this->url('login')?>">Log In</a>
  <? endif; ?>
</div>
<?=$this->partial('partials/searchbox.phtml')?>
