<a class="siteTitle" href="<?=$this->url('home')?>"><?=$this->escapeHtml($this->config('siteTitle'))?></a>
<div class="headerRight">
  <div class="account-links">
    <? if ($this->auth()->hasIdentity()): ?>
      <a href="<?=$this->url('user', array('id' => $this->auth()->getIdentity()))?>">Account</a> &bull;
      <a href="<?=$this->url('logout')?>">Log Out</a> <span class="last"> &bull;</span>
    <? else: ?>
      <a href="<?=$this->url('signup')?>">Sign Up</a> &bull;
      <a href="<?=$this->url('login')?>">Log In</a><span class="last"> &bull;</span>
    <? endif; ?>
  </div>
  <?=$this->partial('partials/searchbox.phtml')?>
</div>