<? if (count($images) > 0): ?>
    <? foreach ($images as $index=>$image): ?>
      <? if ($index > 0 && $index % 6 == 0): ?>
        </div><div class="row">
      <? endif; ?>
      <?
        if (!isset($linkType) || $linkType == 'image') {
          $path = $image['Image_Path'];
          if (empty($path)) {
            $path = $image['IIIF_URI'] . '/full/full/0/default.jpg';
          }
          $openAnchor = '<a target="_new" href="' . $this->escapeHtml($path) . '">';
        } else if ($linkType == 'item') {
          $openAnchor = '<a href="' . $this->url('item', array('id' => $image['Item_ID'])) . '">';
        } else {
          // unsupported option:
          $openAnchor = '<a>';
        }
        $thumb = $image['Thumb_Path'];
        if (empty($thumb)) {
          $thumb = $image['IIIF_URI'] . '/full/,120/0/default.jpg';
        }
      ?>
      <div class="col-md-2 <?=$index ?>" style="text-align:center">
        <?=$openAnchor?><img class="img-polaroid" src="<?=$this->escapeHtml($thumb)?>" style="display:block;margin:auto"/></a>
        <?
          $note = '';
          if (isset($editions) && count($editions) > 1) {
              $note = $this->fixtitle($image['Edition_Name']);
          }
          if (!empty($image['Note'])) {
              if (!empty($note)) {
                  $note .= ' - ';
              }
              $note .= $image['Note'];
          }
        ?>
        <?=!empty($note) ? '(' . $this->escapeHtml($note) . ')' : '<br />'?>
      </div>
    <? endforeach; ?>
<? endif; ?>
