<? if (count($images) > 0): ?>
  <? foreach ($images as $image): ?>
    <table class="image">
      <tr><td align="center"><a target="_new" href="<?=$this->escapeHtml($image['Image_Path'])?>"><img src="<?=$this->escapeHtml($image['Thumb_Path'])?>" /></a></td></tr>
      <? if (!empty($image['Note'])): ?>
        <tr><td align="center">(<?=$this->escapeHtml($image['Note'])?>)</td></tr>
      <? endif; ?>
    </table>
  <? endforeach; ?>
  <div style="clear: left;"><!-- empty --></div>
<? endif; ?>
