<?php if ($this->pageCount): ?>
  <div class="paginationControl">
    <?php if (isset($this->first) && $this->current > 1): ?>
    <a href="?page=<?=$this->first?>">
      First
    </a> |
    <?php else: ?>
      <span class="disabled">First</span> |
    <?php endif; ?>

    <?php if (isset($this->previous)): ?>
    <a href="?page=<?=$this->previous?>">
      Previous
    </a> |
    <?php else: ?>
      <span class="disabled">Previous</span> |
    <?php endif; ?>

    <?php foreach ($this->pagesInRange as $page): ?>
      <?php if ($page != $this->current): ?>
        <a href="?page=<?=$page?>">
          <?= $page; ?>
        </a> |
      <?php else: ?>
        <?= $page; ?> |
      <?php endif; ?>
    <?php endforeach; ?>

    <?php if (isset($this->next)): ?>
    <a href="?page=<?=$this->next?>">
      Next
    </a> |
    <?php else: ?>
      <span class="disabled">Next |</span>
    <?php endif; ?>

    <?php if (isset($this->last)): ?>
    <a href="?page=<?=$this->last?>">
      Last
    </a>
    <?php else: ?>
      <span class="disabled">Last</span>
    <?php endif; ?>
  </div>
<?php endif; ?>