<div class="searchbox">
  <form action=<?=$this->url('search')?> method="get">
    <b>Search:</b>
    <select name="SearchType">
      <? foreach (array('Title', 'Person', 'Keyword', 'ISBN') as $current): ?>
        <option value="<?=$this->escapeHtml($current)?>"<?=isset($this->layout()->type) && strtolower($this->layout()->type) == strtolower($current) ? ' selected="selected"' : ''?>><?=$this->escapeHtml($current)?></option>
      <? endforeach; ?>
    </select>
    <input type="text" name="SearchQuery" value="<?=isset($this->layout()->query) ? $this->escapeHtml($this->layout()->query) : ''?>" size="35" maxlength="50" />
    <input type="submit" value="Search" />
  </form>
</div>