<?php $this->layout()->title = 'Administration' ?>
<?php if ($contentEditor): ?>
  <h2>Edit Data</h2>
  <ul>
    <li><a target='_categories' href='<?=$this->url('edit/category_list')?>'>Categories</a></li>
    <li><a target='_citations' href='<?=$this->url('edit/citation_list')?>'>Citations</a></li>
    <li><a target='_editionattributes' href='<?=$this->url('edit/editionattribute_list')?>'>Edition Attributes</a></li>
    <li><a target='_files' href='<?=$this->url('edit/file_list')?>'>Files</a></li>
    <li><a target='_fulltext' href='<?=$this->url('edit/fulltextsource_list')?>'>Full Text Sources</a></li>
    <li><a target='_itemattributes' href='<?=$this->url('edit/itemattribute_list')?>'>Item Attributes</a></li>
    <li><a target='_itemrelationships' href='<?=$this->url('edit/itemrelationship_list')?>'>Item Relationships</a></li>
    <li><a target='_materials' href='<?=$this->url('edit/language_list')?>'>Languages</a></li>
    <li><a target='_links' href='<?=$this->url('edit/link_list')?>'>Links</a></li>
    <li><a target='_materials' href='<?=$this->url('edit/material_list')?>'>Material Types</a></li>
    <li><a target='_notes' href='<?=$this->url('edit/note_list')?>'>Notes</a></li>
    <li><a target='_people' href='<?=$this->url('edit/person_list')?>'>People</a></li>
    <li><a target='_places' href='<?=$this->url('edit/country_list')?>'>Places</a></li>
    <li><a target='_platforms' href='<?=$this->url('edit/platform_list')?>'>Platforms</a></li>
    <li><a target='_predicates' href='<?=$this->url('edit/predicate_list')?>'>Predicates</a></li>
    <li><a target='_publishers' href='<?=$this->url('edit/publisher_list')?>'>Publishers</a></li>
    <li><a target='_series' href='<?=$this->url('edit/series_list')?>'>Series</a></li>
    <li><a target='_seriesattributes' href='<?=$this->url('edit/seriesattribute_list')?>'>Series Attributes and Relationships</a></li>
    <li><a target='_tags' href='<?=$this->url('edit/tag_list')?>'>Subjects/Tags</a></li>
    <li><a target='_tagsattributes' href='<?=$this->url('edit/tagattribute_list')?>'>Subjects/Tags Attributes and Relationships</a></li>
  </ul>
<?php endif; ?>

<?php if ($approver || $userEditor || $dataManager): ?>
  <h2>Extra Tools</h2>
  <ul>
    <?php if ($approver): ?>
      <li><a target='_approve' href='<?=$this->url('edit/approve')?>'>Approve Users / Content Submissions</a></li>
    <?php endif; ?>
    <?php if ($dataManager): ?>
      <li><a target='_cleanup' href='<?=$this->url('edit/cleanup')?>'>Data Cleanup</a></li>
    <?php endif; ?>
    <?php if ($userEditor): ?>
      <li><a target='_users' href='<?=$this->url('edit/user_list')?>'>Edit Users</a></li>
    <?php endif; ?>
    <?php if ($dataManager): ?>
      <li><a target='_migrate' href='<?=$this->url('edit/migrate')?>'>Migrate Old Data</a></li>
    <?php endif; ?>
  </ul>
<?php endif; ?>

<?php if (!$contentEditor && !$approver && !$userEditor): ?>
  <p>You do not have permission to access this page.</p>
<?php endif; ?>