<? $this->layout()->title = 'Administration' ?>
<? if ($contentEditor): ?>
  <h2>Edit Data</h2>
  <ul>
    <li><a target='_categories' href='<?=$this->url('edit/category_list')?>'>Categories</a></li>
    <li><a target='_files' href='<?=$this->url('edit/file_list')?>'>Files</a></li>
    <li><a target='_fulltext' href='<?=$this->url('edit/fulltextsource_list')?>'>Full Text Sources</a></li>
    <li><a target='_materials' href='<?=$this->url('edit/language_list')?>'>Languages</a></li>
    <li><a target='_links' href='<?=$this->url('edit/link_list')?>'>Links</a></li>
    <li><a target='_materials' href='<?=$this->url('edit/material_list')?>'>Material Types</a></li>
    <li><a target='_notes' href='<?=$this->url('edit/note_list')?>'>Notes</a></li>
    <li><a target='_people' href='<?=$this->url('edit/person_list')?>'>People</a></li>
    <li><a target='_places' href='<?=$this->url('edit/country_list')?>'>Places</a></li>
    <li><a target='_platforms' href='<?=$this->url('edit/platform_list')?>'>Platforms</a></li>
    <li><a target='_publishers' href='<?=$this->url('edit/publisher_list')?>'>Publishers</a></li>
    <li><a target='_series' href='<?=$this->url('edit/series_list')?>'>Series</a></li>
    <li><a target='_seriesattributes' href='<?=$this->url('edit/seriesattribute_list')?>'>Series Attributes</a></li>
    <li><a target='_tags' href='<?=$this->url('edit/tag_list')?>'>Subjects/Tags</a></li>
  </ul>
<? endif; ?>

<? if ($approver || $userEditor || $dataManager): ?>
  <h2>Extra Tools</h2>
  <ul>
    <? if ($approver): ?>
      <li><a target='_approve' href='<?=$this->url('edit/approve')?>'>Approve Users / Content Submissions</a></li>
    <? endif; ?>
    <? if ($dataManager): ?>
      <li><a target='_cleanup' href='<?=$this->url('edit/cleanup')?>'>Data Cleanup</a></li>
    <? endif; ?>
    <? if ($userEditor): ?>
      <li>Edit Users (not implemented yet)</li>
    <? endif; ?>
    <? if ($dataManager): ?>
      <li><a target='_migrate' href='<?=$this->url('edit/migrate')?>'>Migrate Old Data</a></li>
    <? endif; ?>
  </ul>
<? endif; ?>

<? if (!$contentEditor && !$approver && !$userEditor): ?>
  <p>You do not have permission to access this page.</p>
<? endif; ?>