<div id="editForm">
  <input type="hidden" id="Person_Authority_ID" value="<?=$this->escapeHtml($authority['Authority_ID'])?>" />
  <table class="edit">
    <tr>
      <th>Authority:</th>
      <td><input type="text" id="Authority_Name" value="<?=$this->escapeHtml($authority['Authority_Name'] ?? '')?>" /></td>
    </tr>
  </table>
  <button id="save_person_authority" onclick="PersonAuthority.save();">Save</button>
  <div id="save_person_authority_status"></div>
</div>
