<?php
$this->layout()->title = 'Edit Person';
$this->layout()->toggleLink = $this->toggleLink('person', $person['Person_ID']);
$this->scriptManager()->add(['base_editor', 'vendor/autocomplete', 'autocomplete', 'edit_people']);
?>
<div class="edit_container">
  <?=$this->render('geeby-deeby/edit-person/index.phtml')?>
</div>
<hr />
<div>
  <form onsubmit="Person.link('Alias'); return false;">
    <label>
      <span class="sr-only">Relationship Type:</span>
      <select id="pseudo_type">
        <option value='realname'>Pseudonym For</option>
        <option value='pseudonym'>Pseudonym:</option>
      </select>
    </label>
    <label><span class="sr-only">Target:</span><input id="pseudo_name" /></label>
    <input type="submit" value="Add Relationship" />
  </form>
</div>
<hr/>
<div class="row">
  <div class="col-md-3">
    <b>Pseudonym For:</b>
    <div id="aliasrealname_list">
      <?=$this->render('geeby-deeby/edit-person/realname-list.phtml')?>
    </div>
  </div>
  <div class="col-md-3">
    <b>Pseudonym(s):</b>
    <div id="aliaspseudonym_list">
      <?=$this->render('geeby-deeby/edit-person/pseudonym-list.phtml')?>
    </div>
  </div>
</div>
<hr />
<div class="row">
  <div class="col-md-12">
    <b>URIs (for linked data):</b>
    <form onsubmit="Person.link('URI'); return false;">
      <?=$this->render('geeby-deeby/edit-predicate/select.phtml')?>
      <label>URI: <input type="text" id="uri" /></label>
      <input type="submit" value="Add URI" />
    </form>
    <div id="uri_list">
      <?=$this->render('geeby-deeby/edit-person/uri-list.phtml')?>
    </div>
  </div>
</div>