<? $this->headScript()->prependFile($this->basePath() . '/js/edit_person.js') ?>
<h1>Edit Person</h1>
<div class="edit_container">
  <?=$this->render('geeby-deeby/edit-person/index.phtml')?>
</div>
<hr />
<div>
<select id="pseudo_type">
  <option value='realname'>Pseudonym For</option>
  <option value='pseudonym'>Pseudonym:</option>
</select>
<input id="pseudo_name" />
<button onclick="saveRelationship();">Add Relationship</button>
</div>
<table>
  <tr>
    <td>
      <b>Pseudonym For:</b>
      <div id="realname_list">
        <?=$this->render('geeby-deeby/edit-person/realname-list.phtml')?>
      </div>
    </td>
    <td>
      <b>Pseudonym(s):</b>
      <div id="pseudonym_list">
        <?=$this->render('geeby-deeby/edit-person/pseudonym-list.phtml')?>
      </div>
    </td>
  </tr>
</table>
