<? $this->layout()->title = 'Edit Person' ?>
<? $this->headScript()->prependFile($this->basePath() . '/js/edit_person.js') ?>
<div class="edit_container">
  <?=$this->render('geeby-deeby/edit-person/index.phtml')?>
</div>
<hr />
<div>
<select id="pseudo_type">
  <option value='realname'>Pseudonym For</option>
  <option value='pseudonym'>Pseudonym:</option>
</select>
<input id="pseudo_name" />
<button onclick="saveRelationship();">Add Relationship</button>
</div>
<hr/>
<div class="row">
  <div class="col-md-3">
    <b>Pseudonym For:</b>
    <div id="realname_list">
      <?=$this->render('geeby-deeby/edit-person/realname-list.phtml')?>
    </div>
  </div>
  <div class="col-md-3">
    <b>Pseudonym(s):</b>
    <div id="pseudonym_list">
      <?=$this->render('geeby-deeby/edit-person/pseudonym-list.phtml')?>
    </div>
  </div>
</div>
<hr />
<div class="row">
  <div class="col-md-12">
    <b>URIs (for linked data owl:sameAs):</b><br />
    <input type="text" id="uri" />
    <button onclick="addURI();">Add URI</button>
    <div id="uri_list">
      <?=$this->render('geeby-deeby/edit-person/uri-list.phtml')?>
    </div>
  </div>
</div>