<?php $this->layout()->title = 'Edit Person' ?>
<?php $this->scriptManager()->add(['base_editor', 'edit_people']) ?>
<div class="row">
  <div class="col-md-6">
    <h3>People:</h3>
    <button id="add_person" type="button" onclick="Person.edit('NEW');">Add Person</button>
    <br /><br />
    <div id="person_list"><?=$this->render('geeby-deeby/edit-person/render-people.phtml')?></div>
  </div>
  <div class="col-md-3">
    <p><b>Authorities:</b></p>
    <button id="add_person_authority" type="button" onclick="PersonAuthority.edit('NEW');">Add Authority</button>
    <br /><br />
    <div id="person_authority_list"><?=$this->render('geeby-deeby/edit-person/render-authorities.phtml')?></div>
  </div>
  <div class="col-md-3">
    <p><b>Roles:</b></p>
    <button id="add_person_role" type="button" onclick="PersonRole.edit('NEW');">Add Role</button>
    <br /><br />
    <div id="person_role_list"><?=$this->render('geeby-deeby/edit-person/render-roles.phtml')?></div>
  </div>
</div>