<?php if (isset($pseudonyms) && count($pseudonyms) > 0): ?>
  <?php foreach ($pseudonyms as $current): ?>
    <table class="list_item">
      <tr>
        <td>
          <a href="<?=$this->url('edit/person', ['id' => $current['Person_ID']])?>">
            <?=$this->showPerson($current)?>
          </a>
        </td>
        <td>
          <a class="ui-icon ui-icon-trash" href="#" onclick="Person.unlink('Alias', <?=$current['Person_ID']?>, 'pseudonym'); return false;">
          </a>
        </td>
      </tr>
    </table>
  <?php endforeach; ?>
<?php else: ?>
  No relevant names.
<?php endif; ?>