<? if (isset($pseudonyms) && count($pseudonyms) > 0): ?>
  <? foreach ($pseudonyms as $current): ?>
    <table class="list_item">
      <tr>
        <td>
          <a href="<?=$this->url('edit/person', array('id' => $current['Person_ID']))?>">
            <?=$this->showPerson($current)?>
          </a>
        </td>
        <td>
          <a class="ui-icon ui-icon-trash" href="#" onclick="deletePseudonym(<?=$current['Person_ID']?>); return false;">
          </a>
        </td>
      </tr>
    </table>
  <? endforeach; ?>
<? else: ?>
  No relevant names.
<? endif; ?>