<?php if (isset($realnames) && count($realnames) > 0): ?>
  <?php foreach ($realnames as $current): ?>
    <?php $currentName = $this->showPerson($current); ?>
    <table class="list_item">
      <tr>
        <td>
          <a href="<?=$this->url('edit/person', ['id' => $current['Person_ID']])?>">
            <?=$this->escapeHtml($currentName)?>
          </a>
        </td>
        <td>
          <?=
            $this->iconButton(
                'trash',
                "Person.unlink('Alias', " . $current['Person_ID'] . ", 'realname')",
                'Unlink real name: ' . $currentName
            )
      ?>
        </td>
      </tr>
    </table>
  <?php endforeach; ?>
<?php else: ?>
  No relevant names.
<?php endif; ?>