<?php if (isset($realnames) && count($realnames) > 0): ?>
  <?php foreach ($realnames as $current): ?>
    <table class="list_item">
      <tr>
        <td>
          <a href="<?=$this->url('edit/person', ['id' => $current['Person_ID']])?>">
            <?=$this->showPerson($current)?>
          </a>
        </td>
        <td>
          <a class="ui-icon ui-icon-trash" href="#" onclick="Person.unlink('Alias', <?=$current['Person_ID']?>, 'realname'); return false;">
          </a>
        </td>
      </tr>
    </table>
  <?php endforeach; ?>
<?php else: ?>
  No relevant names.
<?php endif; ?>