<?php if (isset($roles) && count($roles) > 0): ?>
  <select id="<?=!empty($idPrefix) ? $this->escapeHtml($idPrefix) : ''?>Role_ID">
    <?php foreach ($roles as $current): ?>
      <option value="<?=$current['Role_ID']?>"<?=(isset($selected) && $current['Role_ID'] == $selected) ? ' selected="selected"' : ''?>>
        <?=$this->escapeHtml($current['Role_Name'])?>
      </option>
    <?php endforeach; ?>
  </select>
<?php else: ?>
  Please define roles.
<?php endif; ?>