<div id="editForm">
  <input type="hidden" id="Person_Role_ID" value="<?=$this->escapeHtml($role['Role_ID'])?>" />
  <table class="edit">
  <tr>
      <th scope="row">Role:</th>
      <td><input type="text" id="Role_Name" value="<?=$this->escapeHtml($role['Role_Name'] ?? '')?>" /></td>
    </tr>
    <tr>
      <th scope="row">Item Creator Predicate:</th>
      <td><input type="text" id="Item_Creator_Predicate" value="<?=$this->escapeHtml($role['Item_Creator_Predicate'] ?? '')?>" /></td>
    </tr>
    <tr>
      <th scope="row">Edition Credit Predicate:</th>
      <td><input type="text" id="Edition_Credit_Predicate" value="<?=$this->escapeHtml($role['Edition_Credit_Predicate'] ?? '')?>" /></td>
    </tr>
  </table>
  <button id="save_person_role" onclick="PersonRole.save();">Save</button>
  <div id="save_person_role_status"></div>
</div>
