<div id="editForm">
  <input type="hidden" id="City_ID" value="<?=$this->escapeHtml($city['City_ID'])?>" />
  <table class="edit">
    <tr>
      <th>City:</th>
      <td><input type="text" id="City_Name" value="<?=isset($city['City_Name']) ? $this->escapeHtml($city['City_Name']) : ''?>" /></td>
    </tr>
  </table>
  <button id="save_city" onclick="saveCity();">Save</button>
  <div id="save_city_status"></div>
</div>
