<form id="editForm" onsubmit="City.save(); return false;">
  <input type="hidden" id="City_ID" value="<?=$this->escapeHtml($city['City_ID'])?>" />
  <table class="edit">
    <tr>
      <th scope="row"><label for="City_Name">City:</label></th>
      <td><input type="text" id="City_Name" value="<?=isset($city['City_Name']) ? $this->escapeHtml($city['City_Name']) : ''?>" /></td>
    </tr>
  </table>
  <input type="submit" id="save_city" value="Save" />
  <div id="save_city_status"></div>
</form>
