<?php if (isset($cities) && count($cities) > 0): ?>
  <select id="<?=!empty($idPrefix) ? $this->escapeHtml($idPrefix) : ''?>City_ID">
    <option value="">-- no city set --</option>
    <?php foreach ($cities as $current): ?>
      <option value="<?=$current['City_ID']?>"<?=(isset($selected) && $current['City_ID'] == $selected) ? ' selected="selected"' : ''?>>
        <?=$this->escapeHtml($current['City_Name'])?>
      </option>
    <?php endforeach; ?>
  </select>
<?php else: ?>
  Please define cities.
<?php endif; ?>