<?php if (isset($uris) && count($uris) > 0): ?>
  <?php foreach ($uris as $current): ?>
    <table class="list_item">
      <tr>
        <td><?=$this->escapeHtml($current['URI'])?> (<?=$this->escapeHtml($current['Predicate_Abbrev'])?>)</td>
        <td>
          <?=$this->iconButton(
            'trash',
            "City.unlink('URI', '" . addslashes($current['URI']) . "')",
            'Unlink ' . $current['URI']
          )?>
        </td>
      </tr>
    </table>
  <?php endforeach; ?>
<?php else: ?>
  No URIs defined.
<?php endif; ?>