<?php
  $this->layout()->title = 'Main Menu';
  $this->layout()->toggleLink = $this->toggleLink('edit', null);
?>
<div class="row">
  <div class="col-md-8">
    <h2>Welcome!</h2>
    <p>The Edward T. LeBlanc Dime Novel Bibliography project aims to create a comprehensive online database of dime novels, story papers, reprint libraries and related materials. <a href="<?=$this->url('about')?>">Learn More &rarr;</a></p>
    <h2>Browse</h2>
    <div class="row">
      <div class="col-sm-6">
        <h3>Series</h3>
        <ul>
          <li><a href="<?=$this->url('series')?>">by name</a></li>
          <li><a href="<?=$this->url('categories')?>">by category</a></li>
          <li><a href="<?=$this->url('cities')?>">by city</a></li>
          <li><a href="<?=$this->url('countries')?>">by country</a></li>
          <li><a href="<?=$this->url('languages')?>">by language</a></li>
          <!--  <li><a href="<?=$this->url('materials')?>">by material type</a></li> -->
          <li><a href="<?=$this->url('publishers')?>">by publisher</a></li>
          <li><a href="<?=$this->url('series', ['extra' => 'Comments'])?>">with comments</a></li>
          <li><a href="<?=$this->url('series', ['extra' => 'New'])?>">recently added</a></li>
        </ul>
        <h3>Users</h3>
        <ul>
          <li><a href="<?=$this->url('users')?>">List Registered Users</a></li>
          <li><a href="<?=$this->url('reviews')?>">Browse Recent Reviews</a></li>
        </ul>
      </div>
      <div class="col-sm-6">
        <h3>Items</h3>
        <ul>
          <li><a href="<?=$this->url('items')?>">by name</a></li>
          <!--  <li><a href="<?=$this->url('platforms')?>">by platform</a></li> -->
          <li><a href="<?=$this->url('tags')?>">by subject/tag</a></li>
          <li><a href="<?=$this->url('items', ['extra' => 'ByYear'])?>">by year</a></li>
          <li><a href="<?=$this->url('items', ['extra' => 'FullText'])?>">with full text</a></li>
          <li><a href="<?=$this->url('items', ['extra' => 'Reviews'])?>">with reviews</a></li>
          <li><a href="<?=$this->url('items', ['extra' => 'New'])?>">recently added</a></li>
        </ul>
        <h3>People</h3>
        <ul>
          <li><a href="<?=$this->url('people')?>">by name</a></li>
          <li><a href="<?=$this->url('people', ['extra' => 'Bios'])?>">with biographical notes</a></li>
          <li><a href="<?=$this->url('people', ['extra' => 'New'])?>">recently added</a></li>
        </ul>
        <!--
        <p><a href="<?=$this->url('files')?>">List Files</a></p>
        <p><a href="<?=$this->url('links')?>">List Links</a></p>
        -->
      </div>
    </div>

    <h2>Podcast: The Spare Change Library</h2>
    <div class="row">
      <div class="col-sm-12">
        <?php $this->latest = current($episodes) ?>
        <?=$this->partial('geeby-deeby-local/podcast/episode.phtml')?>
        <p><a href="<?=$this->url('podcast')?>">About The Spare Change Library</a></p>
      </div>
    </div>

    <!--
    <h2>Frequently Asked Questions</h2>
    <p>
      <a href="<?=$this->url('faqs')?>">List All</a>
    </p>
    -->
  </div>
  <div class="col-md-4">
    <a class="twitter-timeline" data-height="550" data-theme="light" href="https://twitter.com/DimeNovelBiblio">Tweets by DimeNovelBiblio</a> <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

    <!--
    <a href="https://widgetic.com/widgets/photo/mosaic-gallery/" class="widgetic-composition" data-autoscale="on" data-id="585c1c2cecb2a1453a8b456b" data-width="350" data-height="500" data-resize="fill">Mosaic Gallery</a><script async src="https://widgetic.com/sdk/sdk.js"></script>

    <button>Auth</button>
    <script src="https://widgetic.com/sdk/sdk.js"></script>
    <a class="twitter-grid" data-limit="5" data-partner="tweetdeck" href="https://twitter.com/crhallberg/timelines/765561012632297472">@DimeNovelBiblio</a> <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
    -->
  </div>
</div>
