<?php
    $this->layout()->title = 'FAQs';
?>
<?php if (count($faqs) < 1): ?>
  <p>No FAQs listed in this database yet.</p>
<?php else: ?>
  <?php $currentCat = false; foreach ($faqs as $current): ?>
    <?php $cat = $current['FAQ_Category_Name']; if ($currentCat !== $cat): $currentCat = $cat; ?>
      <h2><?=$cat?></h2>
    <?php endif; ?>
    <p><b><?=$current['FAQ_Category_ID'] . '.' . $current['FAQ_ID'] . ' ' . $current['FAQ_Name']?></b></p><blockquote><?=$current['FAQ_Body']?></blockquote>
  <?php endforeach; ?>
<?php endif; ?>