name: CI

on: [push, pull_request]

jobs:
  run-tests:
    name: Tests with PHP ${{ matrix.php-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['7.3', '7.4', '8.0']
        include:
          - php-version: 7.3
            phing_tasks: "startup"
          - php-version: 7.4
            phing_tasks: "startup"
          - php-version: 8.0
            phing_tasks: "startup phpcs-console php-cs-fixer-dryrun"

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: intl, xsl

      - name: Checkout
        uses: actions/checkout@v2

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Cache php-cs-fixer data
        uses: actions/cache@v2
        with:
          path: .php_cs_cache
          key: "php-${{ matrix.php-version }}-php-cs-fixer-${{ github.sha }}"
          restore-keys: "php-${{ matrix.php-version }}-php-cs-fixer-"

      - name: Install composer dependencies
        run: composer install

      - name: Run tests
        run: vendor/bin/phing ${{ matrix.phing_tasks }}
